### ISSUE TITLE
Supplemental GID without defined name causes segfault

### ISSUE THREAD

**Issue by m0zes** [apptainer/singularity#231] opened 2016-09-25 03:33 UTC
SGE adds a supplemental GID to processes within a job. SGE uses these GIDs to track processes that it should kill at the end of a job. It isn't strictly necessary to have a name provided with this supplemental GID. Without a name provide, sexec silently segfaults when trying to write the group information into the container's overlay for /etc/group

This issue may not affect many people, but it is something that should either be fixed or documented.

This is definitely affecting version 2.1, I've not tried code from master.

**Comment by bbockelm** [comment] 2016-09-25 12:27
Hi Adam,

Apologies for the issue - yes, this was already fixed in master.

Greg - would it make sense to backport this to a 2.1.3?

 Brian

**Comment by gmkurtzer** [comment] 2016-09-25 23:51
Hi @m0zes, how can I replicate this? I've tried creating a group entry for myself without a name, but it is not causing a segfault in either 2.1.x or master.

@bbockelm Yep, I'd be happy to make the fix available in 2.1.3 and release it this week (before the 2.2 release gets out there).

Thanks!

**Comment by bbockelm** [comment] 2016-09-27 21:03
I believe the issue is here:

https://github.com/gmkurtzer/singularity/blob/2.1.2/src/container_files.c#L109

(and other functions there and in the passwd handling -- I fixed a bunch as part of 893f7e3fa56356a008aacf3b83af5627046a05a1).

The only easy way I can think of to reproduce this is:
1.  Add a group named `foo`.
2.  Execute `runuser -u bbockelm -g bbockelm -G foo -`.  This should open a session with user `bbockelm`, group `bbockelm`, and supplementary group `foo`.
3.  In a separate shell, remove group `foo` from the system.
4.  In the session from (2), run singularity.

SGE will use the `setgroups` syscall directly to add a supplementary GID that is not mapped to a group name in the system; that's about what steps (1) through (3) will emulate.  I hope.

**Comment by bbockelm** [comment] 2016-10-30 19:00
Closing issue as I believe this is fixed in the latest 2.2 release.

**Closed as completed by bbockelm** 2016-10-30 19:00 UTC
