### ISSUE TITLE
Potential kernel panic when running a container with corrupted ext filesystem 

### ISSUE THREAD

**Issue by kcgthb** [apptainer/singularity#180] opened 2016-08-03 21:07 UTC
Hi Greg!

We realized a potential issue when running a container based on a corrupted ext filesystem. 

Ext filesystems can be created (or modified) to generate a kernel panic when they encounter an error. Form `ext4(5)`:

```
errors={continue|remount-ro|panic}
              Define the behavior when an error is encountered.  (Either
              ignore errors and just mark the filesystem erroneous and
              continue, or remount the filesystem read-only, or panic and
              halt the system.)  The default is set in the filesystem
              superblock, and can be changed using tune2fs(8).
```

So if somebody ever (intentionally or not) alters an existing container with `tune2fs -e panic` and corrupts the filesystem, there is a potential for a regular user to generate a kernel panic on the host. 

This could be easily fixed by forcingly mounting the filesystem with the `errors=remount-ro` option in [mounts.c](https://github.com/gmkurtzer/singularity/blob/master/src/mounts.c#L72)

**Comment by martinetd** [comment] 2016-08-03 21:54
Because giving references never hurt, original idea from http://www.openwall.com/lists/oss-security/2016/03/29/4
Reproducer image (48MB compressed) at http://asmadeus.notk.org/CEA/ext4-errors=panic-crash.img.xz (made with singularity create/bootstrap + debugfs on the filesystem making `/lib/x86_64-linux-gnu/libc-2.19.so` mode invalid with "`mi`") - panics system with `singularity shell -w image`

**Comment by gmkurtzer** [comment] 2016-08-03 22:18
Oh, good catch! did you get a chance to test with "errors=remount-ro" in mount.c?

**Comment by kcgthb** [comment] 2016-08-03 23:11
Yes! And it works, meaning the ext errors don't trigger a kernel panic, whatever the filesystem error options are.

**Comment by gmkurtzer** [comment] 2016-08-04 14:41
I'm curious (didn't mean to close this issue), how did you run the command that generated the panic? Does it happen only when using the --writable flag, or does it also happen in the default read-only mount?

Thanks!

**Comment by gmkurtzer** [comment] 2016-08-04 14:55
BTW, I have a new release drafted for 2.1.2 to include this fix. I will publish it when this ticket is closed.

**Comment by kcgthb** [comment] 2016-08-04 15:52
We only managed to get the panic happen with the --writable flag. I don't think it can happen in the default read-only mode, because in that case, well, the image is read-only already so what further damage can be done by accessing it? So my guess is that the `errors=panic` option is ignored when the filesystem is mounted with the `MS_RDONLY`flag.

But in case we missed something, it probably doesn't hurt to add the `errors=remount-ro` option in every case

And yay for 2.1.2!

**Comment by gmkurtzer** [comment] 2016-08-04 16:22
Excellent information, thank you! I will close this ticket and publish the release for 2.1.2.

**Closed as completed by gmkurtzer** 2016-08-04 16:22 UTC
