### ISSUE TITLE
MPI does not work as documented

### ISSUE THREAD

**Issue by cameronkennedy** [apptainer/singularity#165] opened 2016-07-27 20:09 UTC
You have an HPC example here http://singularity.lbl.gov/#hpc
It does not work for me.    http://pastebin.com/V5u13wjQ

This line is particular suggests  users should be able to run mpi jobs
$ mpirun -np 20 singularity exec /tmp/Centos-7.img /usr/bin/ring

This response suggests this is expected to fail, despite the documentation.  
http://pastebin.com/jRiYcH0R

**Comment by gmkurtzer** [comment] 2016-07-27 21:14
Hi @cameronkennedy 

You are right, it should work as advertised. Did you use the commands exactly as they are defined on the Singularity HPC page? If so, I will try and reproduce the issue.

Thanks!

**Comment by gmkurtzer** [comment] 2016-07-27 21:15
Oh, I should have asked this as well. What version of Singularity are you testing with?

**Comment by gmkurtzer** [comment] 2016-07-27 21:53
It looks like it is a bug in OMPI in the master branch. I am getting it as well, and this used to work just fine.

Here is what I am getting: http://pastebin.com/pJwrxvAL

@rhc54 Any ideas, or should I file a bug report to OMPI?

**Comment by rhc54** [comment] 2016-07-27 22:30
this looks like something mixed new/old versions. Does the daemon on the outside of the container "match" the version used by the app on the "inside"? If not, then boom.

**Comment by gmkurtzer** [comment] 2016-07-27 22:46
Ahh, good call @rhc54! I was running too old an OMPI on my host. So after fixing that, I can't even run an MPI program on my host:

```
$ mpirun -np 1 ./ring 
[centos7-x64:38716] *** Process received signal ***
[centos7-x64:38716] Signal: Segmentation fault (11)
[centos7-x64:38716] Signal code: Address not mapped (1)
[centos7-x64:38716] Failing at address: 0xffffffff07b2ffff
Segmentation fault
```

Is that me?!?! :-o

**Comment by rhc54** [comment] 2016-07-27 22:48
probably is you, dude - what version of OMPI are you trying to use?

**Comment by gmkurtzer** [comment] 2016-07-27 22:49
That is a clone from Github master as of 30 minutes ago. lol

```
$ git describe
dev-4467-g1eb4ef4
```

**Comment by rhc54** [comment] 2016-07-27 22:54
hmmm...what kind of system?

**Comment by gmkurtzer** [comment] 2016-07-27 22:56
Centos7. Nothing special:

```
$ git clone https://github.com/open-mpi/ompi.git
$ cd ompi
$ ./autogen.pl && ./configure --prefix=/usr/local && make && sudo make install
$ mpicc examples/ring_c.c -o ring
$ mpirun -np 2 ./ring
```

**Comment by rhc54** [comment] 2016-07-27 22:59
Huh - building now

**Comment by gmkurtzer** [comment] 2016-07-27 23:00
Let's race... I'm rebuilding now too... Just in case. lol

**Comment by rhc54** [comment] 2016-07-27 23:06
looks okay to me:

``` shell
examples$ mpirun -n 3 ./ring_c
Process 0 sending 10 to 1, tag 201 (3 processes in ring)
Process 0 sent to 1
Process 0 decremented value: 9
Process 0 decremented value: 8
Process 0 decremented value: 7
Process 0 decremented value: 6
Process 0 decremented value: 5
Process 0 decremented value: 4
Process 0 decremented value: 3
Process 0 decremented value: 2
Process 0 decremented value: 1
Process 0 decremented value: 0
Process 0 exiting
Process 1 exiting
Process 2 exiting
$
```

**Comment by gmkurtzer** [comment] 2016-07-27 23:20
Working for me now too... I had a previous MPI install causing problems. Thanks for the help and sorry to bug ya @rhc54!

Now on to testing @cameronkennedy's issue again...

**Comment by gmkurtzer** [comment] 2016-07-27 23:26
@cameronkennedy Now that I ensured that I am using the same version of MPI on the host as I am inside the container (as I understand, you can use newer on the host, but not newer in the container), it is working fine for me:

```
$ mpirun -np 4 singularity exec ../Centos7.img /usr/bin/ring
Process 0 sending 10 to 1, tag 201 (4 processes in ring)
Process 0 sent to 1
Process 1 exiting
Process 2 exiting
Process 3 exiting
Process 0 decremented value: 9
Process 0 decremented value: 8
Process 0 decremented value: 7
Process 0 decremented value: 6
Process 0 decremented value: 5
Process 0 decremented value: 4
Process 0 decremented value: 3
Process 0 decremented value: 2
Process 0 decremented value: 1
Process 0 decremented value: 0
Process 0 exiting
```

I should probably add a note to the website to ensure that one is using the same or newer MPI on the host as they are inside the container...

**Comment by gmkurtzer** [comment] 2016-08-02 15:22
@cameronkennedy I am closing the ticket as I can no longer replicate the problem. Please feel free to comment on the issue and let me know if this is still an issue for you and I can reopen it.

Thank you!

**Closed as completed by gmkurtzer** 2016-08-02 15:22 UTC

**Comment by cameronkennedy** [comment] 2016-08-04 19:01
Not sure what changed, but everything is working as described.  Thanks.
