### ISSUE TITLE
Pull with Library Broken in 3.2.1

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#3815] opened 2019-06-27 19:28 UTC
## Version of Singularity:

3.2.1

### Expected behavior

For 3.1, I could pull a container from a custom library (here I am pulling with the singularity Docker image for previous version 3.1):

```bash
$ docker run -it singularityware/singularity:3.1-slim --debug pull --library https://xxxxxxxxxxx collection/container:shadoop
Unable to find image 'singularityware/singularity:3.1-slim' locally
3.1-slim: Pulling from singularityware/singularity
48ecbb6b270e: Pull complete 
2ceaa3199c9d: Pull complete 
d653269fbd57: Pull complete 
Digest: sha256:5253c519697a1489d0bf98c8f3fedefba6beb97e17014a00d4e5e6bda631b59e
Status: Downloaded newer image for singularityware/singularity:3.1-slim
WARNING [U=0,P=1]          sylabsToken()                 Authentication token file not found : Only pulls of public images will succeed
DEBUG   [U=0,P=1]          apiGet()                      apiGet calling https://xxxxxxxxxxxxxx/v1/images//collection/container:shadoop
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /root/.singularity/cache
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /root/.singularity/cache/library/sha256.a904e546638a8778d1c89c79d721aec76bd315b882a253df6875aa0b5f0ec637
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library/sha256.a904e546638a8778d1c89c79d721aec76bd315b882a253df6875aa0b5f0ec637
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library/sha256.a904e546638a8778d1c89c79d721aec76bd315b882a253df6875aa0b5f0ec637
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library
INFO    [U=0,P=1]          pullRun()                     Downloading library image
DEBUG   [U=0,P=1]          DownloadImage()               Pulling from URL: https://xxxxxxxxxxxxxx/v1/imagefile/collection/container:shadoop
DEBUG   [U=0,P=1]          DownloadImage()               OK response received, beginning body download
DEBUG   [U=0,P=1]          DownloadImage()               Created output file: /root/.singularity/cache/library/sha256.a904e546638a8778d1c89c79d721aec76bd315b882a253df6875aa0b5f0ec637/container_shadoop.sif
 764.00 KiB / 764.00 KiB [=====================================================================================] 100.00% 7.93 MiB/s 0s
DEBUG   [U=0,P=1]          DownloadImage()               Download complete

```

### Actual behavior

And now with 3.2.1, I cannot:

```bash
$ singularity --debug pull --library https://xxxxxxxxxxxxxx collection/container:shadoop
DEBUG   [U=1000,P=12506]   createConfDir()               /home/vanessa/.singularity already exits. Not creating.
FATAL   [U=1000,P=12506]   pullRun()                     While pulling library image: image does not exist in the library: collection/container:shadoop
```

What changed?

**Comment by vsoch** [comment] 2019-06-27 19:29
You also removed the debug statements that provided the URL, which only serves to make debugging harder :(

**Comment by vsoch** [comment] 2019-06-27 19:43
I think I see the bug - you define two variables `PushLibraryURI` and `pullLibraryURIFlag` flag, and you used to provide this to the getImage function, but no longer do.

 - The flag is [here](https://github.com/sylabs/singularity/blob/f826291f8d1b26df71f8989d910ff6469b74f21c/cmd/internal/cli/pull.go#L54) and do a Control F to see that it's fed into the client as an arg, but the other one (`pullLibraryURI`) without the flag seems to be fed into the function. So no matter what, the getImage uses the sylabs library.

I can confirm this by setting a custom library, and then (it still) returns the sylabs busybox:

```bash
$ singularity --debug pull --library xxxxxxxxx busybox
(works)
```

**Comment by Flamefire** [comment] 2019-06-28 06:57
You are right. This is a C&P bug which I'm wondering why this even compile: https://github.com/sylabs/singularity/blob/d6b1425aa4f37834232c31d4570fba099bc6dc62/cmd/internal/cli/pull.go#L56 The `pullLibraryURIFlag` references the variable `PushLibraryURI` instead of `PullLibraryURI`

Bug was introduced by https://github.com/sylabs/singularity/pull/3230

However this affects 3.3. The current 3.2.1 should still work: https://github.com/sylabs/singularity/blob/v3.2.1/cmd/internal/cli/pull.go#L56

**Comment by Flamefire** [comment] 2019-06-28 07:46
I can confirm, that pull works for a custom library with 3.2.1

**Comment by cclerget** [comment] 2019-06-28 07:53
Thanks @Flamefire , will fix that and add it to the list of fixes for 3.3.0-rc1

**Comment by vsoch** [comment] 2019-06-28 12:07
I am using the 3.2.1 from @cclerget branch with the networking fixes, so it must be a variation of 3.2.1 after the bug was introduced, `singularity version 3.2.1-691.g4bb8833ba`. It doesn't work for me with a custom library, as shown above.

**Comment by Flamefire** [comment] 2019-06-28 12:17
@vsoch Can't you simply check that one file at https://github.com/sylabs/singularity/blob/d6b1425aa4f37834232c31d4570fba099bc6dc62/cmd/internal/cli/pull.go#L56 in whatever modified version you are using to verify that it is the same issue that will be fixed with #3825? Obviously a bug introduced after 3.2.1 and in preparation of 3.3.x is "a variation of 3.2.1" but it is NOT 3.2.1 and as you didn't link a commit you are using it is impossible to tell what your specific bug is.

**Comment by vsoch** [comment] 2019-06-28 12:24
@Flamefire, I believe that @cclerget knows the networking issue he helped with about a week ago: https://github.com/sylabs/singularity/pull/3771. That should be the one that I still have installed.

As for the commit, should it not be enough for the user to provide the complete version string? `singularity version 3.2.1-691.g4bb8833ba` What's the point if you can't find the commit from that? (Note that I tried it once, and couldn't).

**Comment by Flamefire** [comment] 2019-06-28 12:33
> That should be the one that I still have installed.

So you are using an unreleased, unmerged commit from someone else (so the version reported is rather meaningless) but declared it as 3.2.1 in your report. The cause as well as the fix were already linked here so you could have easily checked and confirmed that it is the same.

As you already noticed: 
>singularity version 3.2.1-691.g4bb8833ba What's the point if you can't find the commit from that? (Note that I tried it once, and couldn't).

I couldn't either because that hash no longer (seems to) exist and the version is most likely wrong (it should already be a 3.3 as I think the master used is based of the 3.3 rc tag)

**Comment by vsoch** [comment] 2019-06-28 12:35
Yes @Flamefire, that is correct. And thank you for being so kind in your interactions with me.

**Closed as completed** 2019-06-28 16:51 UTC
Labels: Bug, Regression, CLI, Release 3.3.0

**Comment by vsoch** [comment] 2019-06-28 16:52
Thanks for the speedy fix @ikaneshiro and @cclerget !
