### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by mshaikh786** [apptainer/singularity#6048] opened 2021-06-17 14:57 UTC
Hi folks:
We rebooted our cluster and have started seeing this error with singularity run  command with version 3.5 and 3.6:
```
panic: runtime error: index out of range [9] with length 9
goroutine 7 [running]:
github.com/sylabs/singularity/pkg/util/fs/proc.parseMountInfoLine(0xc0000d86e0, 0x43, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/sylabs/singularity/pkg/util/fs/proc/proc.go:113 +0x581
github.com/sylabs/singularity/pkg/util/fs/proc.GetMountInfoEntry(0xab9890, 0x14, 0x0, 0x0, 0x0, 0x0, 0x0)
        github.com/sylabs/singularity/pkg/util/fs/proc/proc.go:145 +0x1f6
github.com/sylabs/singularity/internal/pkg/runtime/engine/singularity.(*EngineOperations).prepareAutofs(0xc0000fefd0, 0xc000010678, 0x0, 0xab019c)
        github.com/sylabs/singularity/internal/pkg/runtime/engine/singularity/prepare_linux.go:399 +0x4b
github.com/sylabs/singularity/internal/pkg/runtime/engine/singularity.(*EngineOperations).prepareContainerConfig(0xc0000fefd0, 0xc000010678, 0x0, 0x0)
        github.com/sylabs/singularity/internal/pkg/runtime/engine/singularity/prepare_linux.go:596 +0x8a7
github.com/sylabs/singularity/internal/pkg/runtime/engine/singularity.(*EngineOperations).PrepareConfig(0xc0000fefd0, 0xc000010678, 0x5, 0xab7415)
        github.com/sylabs/singularity/internal/pkg/runtime/engine/singularity/prepare_linux.go:128 +0x5d8
github.com/sylabs/singularity/internal/app/starter.StageOne(0xc000010678, 0xc00000f340)
        github.com/sylabs/singularity/internal/app/starter/stage_linux.go:27 +0x8c
main.startup()
        command-line-arguments/main_linux.go:56 +0x2fb
created by main.main
        command-line-arguments/main_linux.go:102 +0x35
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------------------------
```

**Comment by ikaneshiro** [comment] 2021-06-17 16:21
Hi @mshaikh786, this looks like an issue with parsing `/proc/self/mountinfo`. Can you include a run with full debug info `singularity -d ...`, your kernel version, and the output of your `/proc/self/mountinfo`? It looks like there is a standard format for entries in that file that we are either incorrectly parsing or incorrectly output on your system

**Comment by mshaikh786** [comment] 2021-06-18 07:46
Hi @ikaneshiro 
Thanks for a prompt response. 
Attached is the output of the two actions you suggested. 
[slurm-15895470.txt](https://github.com/hpcng/singularity/files/6675470/slurm-15895470.txt)

**Comment by DrDaveD** [comment] 2021-06-21 20:02
The last line of the mountinfo
```
/ /dev/shm rw,relatime - tmpfs  rw,mode=750,uid=174988
```
has only 9 whitespace-separated fields instead of the usual 10.  The 9th field is empty, with two spaces in a row.  So the splitting should be done based on a single blank rather than on whitespace.

**Comment by mshaikh786** [comment] 2021-06-27 13:01
Hi @DrDaveD , is this something Sylabs will fix?

**Comment by DrDaveD** [comment] 2021-06-27 21:43
Anybody can fix this, it is trivial.  I marked it as a 3.8.1 item for HPCng singularity.  I can't speak for Sylabs.

**Comment by sandynomad** [comment] 2021-06-28 10:06
The issue reported by @mshaikh786 was due to mounting a tmpfs file system when launching jobs. The mount line was:

    if ( mount( "", mounts[ i ], "tmpfs", 0, opts ) < 0 ) {

. . which is accepted by the OS but caused an issue with singularity.

It was changed to:

    if ( mount( "tmpfs", mounts[ i ], "tmpfs", 0, opts ) < 0 ) {

.. and now both the OS and Singularity are ok.

**Comment by DrDaveD** [comment] 2021-06-28 12:06
Good catch.  Please submit that fix as a pull request.   I think it would also be good to change the parsing of the mountinfo line to be based on a blank rather than whitespace, to avoid any future such problems caused by other programs.

**Comment by sandynomad** [comment] 2021-06-28 12:16
Hi @DrDaveD - Apologies it wasn't clear but the mount line was in some software we are using to setup a private tmpfs area in for a slurm job - I just included it to highlight valid "mount" usage that singularity had difficulty with. The code shown wasn't from singularity.

**Comment by DrDaveD** [comment] 2021-06-28 13:25
Oh, now I understand.  So good, you have a workaround for now, but we should still have a fix in singularity.

**Comment by mshaikh786** [comment] 2021-06-28 13:30
@DrDaveD and @sandynomad , yes, the workaround worked for us but it will be nice if the parser in singularity tolerates a whitespace instead of a full on string currently expected by it in place of `mount source` attribute of `cat /proc/self/mountinfo` output.
You may close the issue should you wish to.

**Closed as completed** 2021-08-03 22:27 UTC
Labels: Bug
