### ISSUE TITLE
singularity remote build upload fails with correct token

### ISSUE THREAD

**Issue by hassanfa** [apptainer/singularity#3923] opened 2019-07-12 13:09 UTC
## Version of Singularity:
`singularity version 3.1.1-1.el7`

### Expected behavior
When building image using the following command:

```
singularity  --tokenfile my.token build \
--remote my_image.sif my_image.def
```

Image should be uploaded after successful build.

### Actual behavior
Container builds successfully but upload fails with the following error:

```
INFO:    Adding help info
INFO:    Adding labels
INFO:    Adding environment to container
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete: /tmp/image-856160216
INFO:    Now uploading /tmp/image-856160216 to the library
 3.31 GiB / 3.31 GiB  100.00% 34.02 MiB/s 1m39sss19s
FATAL:   Error uploading file to server: Post https://library.sylabs.io/v1/imagefile/5d2884fa20da19c686b0b0a2: EOF
FATAL:   While performing build: build image size <= 0
```

### Steps to reproduce behavior
```
singularity  --tokenfile my.token build \
--remote my_image.sif my_image.def
```

I have successfully built and uploaded other containers. And this container with current settings was also successfully built on shub. I wonder if this is singularity's issue or cloud, but I couldn't find much online about the error message.

**Comment by rherban** [comment] 2019-07-12 14:44
We've since beefed up this portion of the codebase in newer versions of Singularity, but the gist is the upload failed for some reason (network hiccup, timeout, etc) and that version didn't attempt a retry.

You can attempt the upload again until it succeeds, or use a newer version of Singularity (>=3.3.0rc1).

**Comment by hassanfa** [comment] 2019-07-12 20:34
Thanks for the tip.

Meanwhile, I tried building it online on [https://cloud.sylabs.io/builder](https://cloud.sylabs.io/builder), but it gives the same error. 
Here is the attached log from above: [build.log](https://github.com/sylabs/singularity/files/3387911/build.log)

If it fails online after successful build, I guess it might not be singularity version.

**Comment by rherban** [comment] 2019-07-15 13:07
Can we get a copy of the definition file you are building from?

**Comment by hassanfa** [comment] 2019-07-15 13:19
Of course. Here is the def file that's failing: https://github.com/Clinical-Genomics/BALSAMIC/blob/develop/BALSAMIC/containers/BALSAMIC.develop

And here is a def file that succeeds:
https://github.com/Clinical-Genomics/BALSAMIC/blob/develop/BALSAMIC/containers/Singularity.miniconda3_4_6_14

It just occurred to me, could it be because of file size? The second def file's image is ~170MB and built/uploaded just fine. First one, on the other hand, is ~3GB.

Thank you for looking into this.

**Comment by rherban** [comment] 2019-07-15 22:20
It looks like the same root cause, the upload is failing and not retrying (further exasperated by the size difference).  We'll look at ways to better deal with that from the server side as well.

Thanks

**Comment by rherban** [comment] 2019-07-18 20:48
@hassanfa When you get a chance, can you try your build again?  Either remotely or through the UI.

Thanks

**Comment by hassanfa** [comment] 2019-07-19 09:31
I tried remote builder on cloud.sylabs.io, and it was successful 👍 

The remote builder through cli, gave the following error:
```
WARNING [U=3112,P=38054]   Build()                       failed to post request to remote build service: Post https://build.sylabs.io/v1/build: dial tcp: lookup build.sylabs.io on 130.237.80.10:53: server misbehaving
FATAL   [U=3112,P=38054]   run()                         While performing build: failed to post request to remote build service: Post https://build.sylabs.io/v1/build: dial tcp: lookup build.sylabs.io on 130.237.80.10:53: server misbehaving
```

I am not sure if this from our side (the server is behind a firewall), or is it sylabs. I've tried using Vagrant on my local machine with Singularity 3.2.0-1:

```
$ singularity remote login SylabsCloud --tokenfile tokenfile
$ singularity --debug --verbose  build --remote BALSAMIC_develop.sif BALSAMIC/containers/BALSAMIC.develop
```
I didn't encounter the error above, and now I'm waiting to build to finish. I'll update as soon as it is done. Update: remote build on Singularity 3.2.0-1 and Vagrant worked and it was successful 👍 .  I'm still unsure if error on "server misbehaving" is on my side or Sylabs. I guess it doesn't matter.

Thank you for following up @rherban . Out of curiosity, what was the issue?

**Comment by rherban** [comment] 2019-07-19 17:57
To the original error, we found a configuration optimization to better handle large uploads.  The load balancer fronting the services would occasionally timeout (most often seen on larger containers) and the client would error out.  

To the "server misbehaving" error, it's most likely on our side and we've gone ahead and refreshed the instances in case any were misbehaving.  Seeing as how you saw a successful upload afterwards, I'd suspect it's a transient issue that cropped up.  

I'm going to close the issue, but please feel free to re-open if you have further questions/comments on this thread.

**Closed as completed by rherban** 2019-07-19 17:57 UTC
Labels: Question
