### ISSUE TITLE
SLES11 failure due to PID namespace support

### ISSUE THREAD

**Issue by AdamSimpson** [apptainer/singularity#777] opened 2017-06-28 15:52 UTC
## Version of Singularity:

2.3.1

### Expected behavior

Singularity works on Cray's stuck with SLES11

### Actual behavior

Singularity fails under SLES11 due to the following combination of support and features:
```
checking for namespace: CLONE_NEWPID... yes
checking for namespace: CLONE_PID... no
checking for namespace: CLONE_FS... yes
checking for namespace: CLONE_NEWNS... yes
checking for namespace: CLONE_NEWUSER... yes
checking for namespace: CLONE_NEWIPC... yes
checking for feature: NO_NEW_PRIVS... no
```
Although CLONE_NEWPID is detected as available under SLES11, as it is defined and the configure test compile works, it is not supported in unshare() so it fails at runtime. Since NO_NEW_PRIVS is unsupported there is no way, that I can see, to short circuit the code in pid.c using singularity.conf

### Steps to reproduce behavior

Install on SLESS11 and run:
```
$ singularity -vvv --debug exec UbuntuTitan.img ls 
Increasing verbosity level (4)
Enabling debugging
Ending argument loop
Singularity version: 2.3.1-dist
Exec'ing: /usr/lib64/singularity/cli/exec.exec
Evaluating args: 'UbuntuTitan.img ls'
VERBOSE [U=0,P=29379]      message_init()                            Set messagelevel to: 5
VERBOSE [U=0,P=29379]      singularity_config_parse()                Initialize configuration file: /etc/singularity/singularity.conf
DEBUG   [U=0,P=29379]      singularity_config_parse()                Starting parse of configuration file /etc/singularity/singularity.conf
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key allow setuid = 'yes'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key allow pid ns = 'no'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key allow user image = 'yes'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key protected image mode = 'none'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key enable overlay = 'yes'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key config passwd = 'no'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key config group = 'yes'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key config resolv_conf = 'yes'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key mount proc = 'yes'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key mount sys = 'yes'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key mount dev = 'yes'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key mount home = 'no'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key mount tmp = 'yes'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key mount hostfs = 'no'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key bind path = '/etc/hosts'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key bind path = '/opt/cray'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key bind path = '/var/spool/alps'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key bind path = '/var/opt/cray'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key bind path = '/lustre/atlas'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key bind path = '/lustre/atlas1'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key bind path = '/lustre/atlas2'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key user bind control = 'yes'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key mount slave = 'yes'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key container dir = '/var/lib/singularity/mnt'
VERBOSE [U=0,P=29379]      singularity_config_parse()                Got config key singularity user = 'singularity'
DEBUG   [U=0,P=29379]      singularity_config_parse()                Finished parsing configuration file '/etc/singularity/singularity.conf'
VERBOSE [U=0,P=29379]      singularity_registry_init()               Initializing Singularity Registry
VERBOSE [U=0,P=29379]      singularity_registry_set()                Adding value to registry: 'LIBEXECDIR' = '/usr/lib64'
DEBUG   [U=0,P=29379]      singularity_registry_set()                Returning singularity_registry_set(libexecdir, /usr/lib64) = 0
VERBOSE [U=0,P=29379]      singularity_registry_set()                Adding value to registry: 'COMMAND' = 'exec'
DEBUG   [U=0,P=29379]      singularity_registry_set()                Returning singularity_registry_set(COMMAND, exec) = 0
VERBOSE [U=0,P=29379]      singularity_registry_set()                Adding value to registry: 'MESSAGELEVEL' = '5'
DEBUG   [U=0,P=29379]      singularity_registry_set()                Returning singularity_registry_set(MESSAGELEVEL, 5) = 0
VERBOSE [U=0,P=29379]      singularity_registry_set()                Adding value to registry: 'VERSION' = '2.3.1-dist'
DEBUG   [U=0,P=29379]      singularity_registry_set()                Returning singularity_registry_set(version, 2.3.1-dist) = 0
VERBOSE [U=0,P=29379]      singularity_registry_set()                Adding value to registry: 'LOCALSTATEDIR' = '/var'
DEBUG   [U=0,P=29379]      singularity_registry_set()                Returning singularity_registry_set(localstatedir, /var) = 0
VERBOSE [U=0,P=29379]      singularity_registry_set()                Adding value to registry: 'SYSCONFDIR' = '/etc'
DEBUG   [U=0,P=29379]      singularity_registry_set()                Returning singularity_registry_set(sysconfdir, /etc) = 0
VERBOSE [U=0,P=29379]      singularity_registry_set()                Adding value to registry: 'BINDIR' = '/usr/bin'
DEBUG   [U=0,P=29379]      singularity_registry_set()                Returning singularity_registry_set(bindir, /usr/bin) = 0
VERBOSE [U=0,P=29379]      singularity_registry_set()                Adding value to registry: 'IMAGE' = 'UbuntuTitan.img'
DEBUG   [U=0,P=29379]      singularity_registry_set()                Returning singularity_registry_set(IMAGE, UbuntuTitan.img) = 0
DEBUG   [U=0,P=29379]      singularity_registry_get()                Returning NULL on 'HOME'
DEBUG   [U=0,P=29379]      singularity_registry_get()                Returning NULL on 'TARGET_UID'
DEBUG   [U=0,P=29379]      singularity_registry_get()                Returning NULL on 'TARGET_GID'
DEBUG   [U=0,P=29379]      singularity_priv_init()                   Initializing user info
DEBUG   [U=0,P=29379]      singularity_priv_init()                   Set the calling user's username to: atj
DEBUG   [U=0,P=29379]      singularity_priv_init()                   Marking uinfo structure as ready
DEBUG   [U=0,P=29379]      singularity_priv_init()                   Obtaining home directory
VERBOSE [U=0,P=29379]      singularity_priv_init()                   Set home (via getpwuid()) to: /ccs/home/atj
VERBOSE [U=0,P=29379]      singularity_suid_init()                   Running SUID program workflow
VERBOSE [U=0,P=29379]      singularity_suid_init()                   Checking program has appropriate permissions
VERBOSE [U=0,P=29379]      singularity_suid_init()                   Checking configuration file is properly owned by root
VERBOSE [U=0,P=29379]      singularity_suid_init()                   Checking if singularity.conf allows us to run as suid
DEBUG   [U=0,P=29379]      singularity_config_get_bool_char_impl()   Called singularity_config_get_bool(allow setuid, yes)
DEBUG   [U=0,P=29379]      singularity_config_get_value_impl()       Returning configuration value allow setuid='yes'
DEBUG   [U=0,P=29379]      singularity_config_get_bool_char_impl()   Return singularity_config_get_bool(allow setuid, yes) = 1
DEBUG   [U=0,P=29379]      singularity_registry_get()                Returning NULL on 'NOSUID'
VERBOSE [U=0,P=29379]      singularity_priv_userns()                 Invoking the user namespace
DEBUG   [U=0,P=29379]      singularity_config_get_bool_char_impl()   Called singularity_config_get_bool(allow user ns, yes)
DEBUG   [U=0,P=29379]      singularity_config_get_value_impl()       No configuration entry found for 'allow user ns'; returning default value 'yes'
DEBUG   [U=0,P=29379]      singularity_config_get_bool_char_impl()   Return singularity_config_get_bool(allow user ns, yes) = 1
VERBOSE [U=0,P=29379]      singularity_priv_userns()                 Not virtualizing USER namespace: running as SUID
DEBUG   [U=0,P=29379]      singularity_priv_userns()                 Returning singularity_priv_init(void)
DEBUG   [U=0,P=29379]      singularity_priv_drop()                   Dropping privileges to UID=5059, GID=6913 (16 supplementary GIDs)
DEBUG   [U=0,P=29379]      singularity_priv_drop()                   Restoring supplementary groups
DEBUG   [U=5059,P=29379]   singularity_priv_drop()                   Confirming we have correct UID/GID
DEBUG   [U=5059,P=29379]   singularity_registry_get()                Returning NULL on 'CLEANUPDIR'
DEBUG   [U=5059,P=29379]   singularity_registry_get()                Returning NULL on 'NOSESSIONCLEANUP'
DEBUG   [U=5059,P=29379]   singularity_registry_get()                Returning NULL on 'NOCLEANUP'
DEBUG   [U=5059,P=29379]   singularity_cleanupd()                    Not running a cleanup thread, no 'SINGULARITY_CLEANUPDIR' defined
DEBUG   [U=5059,P=29379]   singularity_runtime_ns()                  Calling: _singularity_runtime_ns_pid()
DEBUG   [U=5059,P=29379]   singularity_runtime_ns_pid()              Using PID namespace: CLONE_NEWPID
DEBUG   [U=5059,P=29379]   singularity_priv_escalate()               Temporarily escalating privileges (U=5059)
DEBUG   [U=0,P=29379]      singularity_priv_escalate()               Clearing supplementary GIDs.
DEBUG   [U=0,P=29379]      singularity_runtime_ns_pid()              Virtualizing PID namespace
ERROR   [U=0,P=29379]      singularity_runtime_ns_pid()              Could not virtualize PID namespace: Invalid argument
ABORT   [U=0,P=29379]      singularity_runtime_ns_pid()              Retval = 255
```

**Comment by bauerm97** [comment] 2017-06-29 09:32
>Although CLONE_NEWPID is detected as available under SLES11, as it is defined and the configure test compile works, it is not supported in unshare() so it fails at runtime. Since NO_NEW_PRIVS is unsupported there is no way, that I can see, to short circuit the code in pid.c using singularity.conf

The fact that you can't "short circuit" the code in pid.c is by design. A system which does not support PR_SET_NO_NEW_PRIVS must not be allowed to run unless it can run inside a PID namespace.

The question now is why `unshare` is telling you that this is an invalid argument. According to http://man7.org/linux/man-pages/man2/unshare.2.html , CLONE_NEWPID is supported by `unshare()`. I wonder if for some reason your machine has a modified unshare.c source file which still defines the CLONE_NEWPID flag but is manually modified to throw EINVAL and not actually create the PID NS. Is there any chance this could be going on?

**Comment by AdamSimpson** [comment] 2017-06-29 11:59
SLES11, at least the release we have on Titan, has a kernel older than 3.8 and so CLONE_NEWPID is not supported by `unshare()`. CLONE_NEWPID has been supported by other functions such as `clone()` since kernel 2.6 and so the singularity configure test compiles fine and assumes support for `unshare()`.

Singularity/2.2 worked however because there was no `#ifdef SINGULARITY_NO_NEW_PRIVS` in pid.c and so PID namespacing was just disabled, running with debug and verbose under singularity/2.2 looked like this:

```
DEBUG   [U=5059,P=20949]   config_parser.c:104:singularity_config_get_bool(): Called singularity_config_get_bool(allow pid ns, 1)
DEBUG   [U=5059,P=20949]   config_parser.c:80:singularity_config_get_value(): Called singularity_config_get_value(allow pid ns)
VERBOSE [U=5059,P=20949]   config_parser.c:88:singularity_config_get_value(): Got config key allow pid ns (= 'yes')
DEBUG   [U=5059,P=20949]   config_parser.c:110:singularity_config_get_bool(): Return singularity_config_get_bool(allow pid ns, 1) = 1
DEBUG   [U=5059,P=20949]   util/util.c:92:envar_defined()             : Checking if environment variable is defined: SINGULARITY_UNSHARE_PID
VERBOSE [U=5059,P=20949]   util/util.c:94:envar_defined()             : Environment variable is undefined: SINGULARITY_UNSHARE_PID
VERBOSE [U=5059,P=20949]   pid.c:59:singularity_ns_pid_unshare()      : Not virtualizing PID namespace on user request
```

**Comment by bauerm97** [comment] 2017-06-29 12:42
>Singularity/2.2 worked however because there was no #ifdef SINGULARITY_NO_NEW_PRIVS in pid.c and so PID namespacing was just disabled, running with debug and verbose under singularity/2.2 looked like this:

This is by design, so I don't know if there's a way around this at this moment in time. It is necessary for security reasons to run in a PID namespace if PR_SET_NO_NEW_PRIVS is not available on the host machine. @gmkurtzer do you have any suggestions for a workaround? The only thing that I can think about would be to attempt to use `clone` as a last resort if and only if everything else has already failed.

**Comment by gmkurtzer** [comment] 2017-07-01 18:41
@AdamSimpson Are you running an older, unpatched kernel on your SLES11 system? I thought CLONE_NEWPID was supported on this version of SLES, and the user space suggests so.

Maybe a SuSE person can help. @craiggardner, do you have any insights by chance?

Thanks!

**Comment by AdamSimpson** [comment] 2017-07-01 23:58
Hi Greg, 

It's certainly old although due to Cray's glacial update schedule it's what we're stuck with for the foreseeable future I believe:
```
$ uname -a
Linux titan-login1 3.0.101-0.46.1_1.0502.8871-cray_gem_s #1 SMP Sat Oct 22 15:27:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
$ cat /etc/SuSE-release 
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
```

When i test for CLONE_NEWPID with the following:
```
#define _GNU_SOURCE
#include <sched.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>

int main(int argc, char **argv) {
  int err = unshare(CLONE_NEWPID);
  if(err != 0)
    printf("error: %s\n", strerror(errno));  

  return 0;
}
```
It compiles fine, as CLONE_NEWPID is defined and available for use in `clone()` for example, but fails at runtime: `error: Invalid argument`

If there is any other information I can provide just let me know, Thanks!

**Comment by bauerm97** [comment] 2017-07-02 00:05
Adam, we could potentially add some support for older systems by enabling the use of `clone()` instead of `unshare()` if the flag is only supported by `clone()`. Do you guys think this would be an acceptable workaround for the time being?

**Comment by AdamSimpson** [comment] 2017-07-02 00:23
Hi Michael, the implementation details of this are out of my wheelhouse but I can say it would be very very welcome if a workaround could be made available.

**Comment by gmkurtzer** [comment] 2017-07-02 00:51
I don't know if this is correct, but based on https://www.novell.com/support/kb/doc.php?id=3594951 it looks like the latest kernel for SLES11.3 is `3.0.101-0.47.90`. But, I don't have the ability to determine if that kernel (or a later version) properly supports the PID namespace.

@craiggardner, can you confirm what version (if any) SLES11 is supposed to support the PID namespace? Thank you!

@AdamSimpson, can you confirm that this is the latest version of the kernel you have access to?

**Comment by AdamSimpson** [comment] 2017-07-02 13:42
@gmkurtzer, Our kernel is  listed as `3.0.101-0.46.1_1.0502.8871-cray_gem_s`

**Comment by bauerm97** [comment] 2017-07-02 15:36
@gmkurtzer Would you like me to prototype a workaround in the meantime while you guys investigate the upstream support of the `CLONE_NEWPID` flag for the `unshare()` call?

**Comment by bbockelm** [comment] 2017-07-03 16:56
@bauerm97 - for prototyping, you might be interested in copying the `fork_ns` function here: https://github.com/bbockelm/lcmaps-plugins-namespace/blob/master/src/lcmaps_namespace.c.in#L204

Acts a lot like the POSIX `fork` (with a custom stack / no stack-guard) but can take additional flags like `CLONE_NEWPID`.

**Comment by bauerm97** [comment] 2017-07-05 15:11
@bbockelm Thanks, this looks perfect. @AdamSimpson I'll see what I can quickly throw together for testing for you.

**Comment by AdamSimpson** [comment] 2017-07-05 16:00
@bauerm97 Awesome, I appreciate the work very much! We're looking at having SLESS11 around for several more years with minimal updates so this will really help out.

**Comment by bauerm97** [comment] 2017-07-05 16:05
@AdamSimpson OK I think I have something written that should solve your issue. It works fine on my computer when I manually force it to use the clone pathway instead of the unshare + fork pathway. Can you possibly test this for me?

https://github.com/bauerm97/singularity/tree/pidns_workaround

**Comment by AdamSimpson** [comment] 2017-07-05 20:21
@bauerm97 It appears to work! The following was printed in the debug so it appears your code was involved:

```
DEBUG   [U=0,P=4799]       singularity_runtime_ns_pid()              unshare(CLONE_NEWPID) unavailable, falling back to clone instead
```

**Comment by gmkurtzer** [comment] 2017-07-06 16:52
Excellent work everyone!

**Comment by bbockelm** [comment] 2017-07-07 02:23
@AdamSimpson - is support for Titan planned?  I might know some users who would be interested in giving it a whirl...

**Comment by AdamSimpson** [comment] 2017-07-07 11:22
@bbockelm It is indeed planned and in fact we already have a few pilot projects using it succesfully. Once this issue gets worked out we should be able to release the documentation and make it available for general use. Thanks for all the work you all have been doing, it's enabling a lot of cool stuff here.

**Comment by bauerm97** [comment] 2017-07-20 05:26
@AdamSimpson Closing this issue since #803 was merged into development branch and should have fixed your issue. Please re-open and mention me if this isn't the case.

**Comment by bauerm97** [comment] 2017-07-20 05:27
@AdamSimpson closing this issue since #803 was merged into the development branch and should have fixed your issue. Please re-open and mention me if that's not the case.

**Closed as completed by bauerm97** 2017-07-20 05:27 UTC
