### ISSUE TITLE
Bootstrap fails with overly long string

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#456] opened 2017-01-16 22:06 UTC
When the last line in the bootstrap file is long. eg:

      sed -i 's|PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin|PATH="/Software/rtg-core-non-commercial-3.6.2:/Software/brew/bin:/Software/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"|' /environment

I get the following error:

	apt-get update
	apt-get install -y apt-transport-https build-essential cmake curl libsm6 libxrender1 libfontconfig1 wget vim git unzip python-setuptools ruby
	apt-k(TRUNCATED...)DEBUG   [U=0,P=13505]      bootdef_parser.c:202:singularity_bootdef_section_get(): Reading line: 	sed -i 's|PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin|PATH="/Software/rtg-core-non-commercial-3.6.2:/Software/brew/bin:/Software/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"|' /environment
	ERROR   [U=0,P=13505]      util/util.c:159:strjoin()                  : Overly-long string encountered.

The line is too long, which I'm guessing has to do with some limit with C/strjoin? In this case, it's a sed, so it would be hard to split up. I'll also point out this is a hack to try and change the /environment file, so if/when we have support to customize that, it wouldn't be needed.

**Comment by gmkurtzer** [comment] 2017-01-18 03:22
Yes, I don't like how the bootdef parser is currently working. @bauerm97 and I spoke about this a few weeks ago and we know it needs to be changed to something more similar to how it works in the GA release of 2.2 (uses line by line STDIN pipe buffering).

**Comment by hyperbolicTom** [comment] 2017-01-27 16:47
It's not just the last line. It's just if the %post is big.
The flaw is in src/util/util.c. Just change the line
      int len = strlength(str1, 2048) + strlength(str2, 2048) + 1;
replace the 2048s with something larger. I doubled them and it worked fine.
Perhaps only one needs to be bigger.
I have a fairly long .def file, more than 2K.

**Comment by jcbowden** [comment] 2017-02-01 04:33
I changed the 2048 to 8192 and so far my "Overly-long string encountered" problem has gone. 
Nice find hyperbolicTom, that issue was driving me silly.

**Comment by gmkurtzer** [comment] 2017-02-01 17:03
I am assuming this issue is only in the master branch and not in 2.2?

BTW, while the update that @hyperbolicTom references is indeed a workaround at present, it is a bandaid as the line limit still exists and that was introduced after the 2.2. The 2.3 release will not have this limitation. Apologies for the bug!

**Comment by satra** [comment] 2017-02-13 16:52
one thought is whether the bootstrap file should just be changed to yaml? and simply use a yaml c parser.

**Comment by gmkurtzer** [comment] 2017-02-13 17:07
While, we could consider different bootstrap definition file formats, the cause of this particular bug is a temporary limitation that only exists in master (not in 2.x nor in lib-refactor).

**Comment by alexhrescale** [comment] 2017-02-18 23:15
Confirming encountering this on 2.2 and 2.2.99 (current master), and that the `util.c` modification works. Using multiple bootstrap defs also seems to be a usable workaround.

**Comment by gmkurtzer** [comment] 2017-02-19 01:01
Hi @alexhrescale, you are seeing this on the GA 2.2(.1) release too? If so, can you test the lib-refactor branch and let me know?

Thanks!

**Comment by alexhrescale** [comment] 2017-02-20 22:45
Looks like the current download link (2.2.1) stable tarball has this fixed. lib-refactor looks fixed too, thanks.

**Comment by gmkurtzer** [comment] 2017-02-21 18:27
Fantastic, thank you!

**Comment by gmkurtzer** [comment] 2017-03-26 02:12
This is fixed in development branch. Closing.

**Closed as completed by gmkurtzer** 2017-03-26 02:12 UTC
