### ISSUE TITLE
ERROR:   Network bridge is not permitted for unprivileged users.

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/singularity#5936] opened 2021-04-15 12:11 UTC
### Version of Singularity:

rpm generated from the master branch plus PR #5934

### Expected behavior

Doing singularity exec prints no warnings.

### Actual behavior

If I do singularity exec on any image I get an error message but it still continues to run:
```
ERROR:   Network bridge is not permitted for unprivileged users.
```
I didn't check if networking still worked or not.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

```
singularity exec docker://centos:7 bash
```

### What OS/distro are you running

CentOS7

### How did you install Singularity

Rpm built from source

**Comment by dtrudg** [comment] 2021-04-15 13:51
This is a duplicate of https://github.com/hpcng/singularity/issues/5929 which has now been patched.

**Closed as completed by dtrudg** 2021-04-15 13:51 UTC
