### ISSUE TITLE
./test.sh fails for unlucky me ; No runscript found, executing /bin/sh /bin/true: /bin/true: cannot execute binary file

### ISSUE THREAD

**Issue by yarikoptic** [apptainer/singularity#142] opened 2016-07-14 23:19 UTC
``` shell
 + sudo singularity copy container.img singularity /            (retval=0) OK
 + singularity run container.img true                           (retval=126) ERROR
No runscript found, executing /bin/sh
/bin/true: /bin/true: cannot execute binary file
Full output in: /tmp/tmp.cbKPbZOdQZ
./test.sh  20.57s user 1.76s system 48% cpu 46.243 total

$> umask         
077

$> cat /tmp/tmp.cbKPbZOdQZ
No runscript found, executing /bin/sh
/bin/true: /bin/true: cannot execute binary file

$> git describe
fatal: No annotated tags can describe '08b8baceb7b7b2728aafce29d1af2998caf3d3e2'.
However, there were unannotated tags: try --tags.

$> git describe --tags
v2.1-testing-16-g08b8bac
```

**Comment by gmkurtzer** [comment] 2016-07-14 23:25
At the top of the test output, you will see the SINGULARITY_CACHEDIR (should be tmpdir, but...) in that directory you will find the container.img. Can you look inside and see if that copy command worked properly and there is a file /singularity that is executable in there? If not, we need to debug the copy...

Thanks!

**Comment by gmkurtzer** [comment] 2016-07-15 01:45
haha, setting my umask replicates the issue for me.... deugging now!

**Comment by yarikoptic** [comment] 2016-07-15 01:48
On Thu, 14 Jul 2016, Gregory M. Kurtzer wrote:

>    haha, setting my umask replicates the issue for me.... deugging now!

please add into the tests collection -- the more the merrier! ;)

**Comment by gmkurtzer** [comment] 2016-07-15 02:15
Hopefully this is all fixed in [master 1c316cd]. Let me know if not. Thanks!

**Comment by yarikoptic** [comment] 2016-07-15 02:30
On Thu, 14 Jul 2016, Gregory M. Kurtzer wrote:

>    Hopefully this is all fixed in [master 1c316cd]. Let me know if not.
>    Thanks!

Done. All tests completed successfully

;)  Just FYI if you run into such one:

Building test container...
- sudo singularity create -s 568 container.img                    (retval=0) OK
- sudo singularity bootstrap container.img /home/yoh/deb/persp    (retval=0) OK

Running container shell tests...
- singularity shell container.img -c true                       (retval=255) ERROR
  ERROR  : Failed to mount (ro) '/dev/loop2' at '/var/singularity/mnt': Invalid argument
  Full output in: /tmp/tmp.UoDyv4VwNy
  ./test.sh  20.80s user 1.93s system 40% cpu 56.132 total

I think was just due to  me running out of space in /tmp/ ;)  having more
descriptive error msg might be of value ;)

**Comment by gmkurtzer** [comment] 2016-07-16 16:05
Interesting... This is what I just got when running by hand in a small tmpfs partition:

```
Traceback (most recent call last):
  File "/bin/yum", line 29, in <module>
    yummain.user_main(sys.argv[1:], exit_code=True)
  File "/usr/share/yum-cli/yummain.py", line 365, in user_main
    errcode = main(args)
  File "/usr/share/yum-cli/yummain.py", line 271, in main
    return_code = base.doTransaction()
  File "/usr/share/yum-cli/cli.py", line 773, in doTransaction
    resultobject = self.runTransaction(cb=cb)
  File "/usr/lib/python2.7/site-packages/yum/__init__.py", line 1816, in runTransaction
    self.skipped_packages, rpmdb_problems, cmdline)
  File "/usr/lib/python2.7/site-packages/yum/history.py", line 956, in beg
    self._trans_cmdline(cmdline)
  File "/usr/lib/python2.7/site-packages/yum/history.py", line 918, in _trans_cmdline
    if cur is None or not self._update_db_file_2():
  File "/usr/lib/python2.7/site-packages/yum/history.py", line 1592, in _update_db_file_2
    executeSQL(cur, "PRAGMA table_info(trans_skip_pkgs)")
  File "/usr/lib/python2.7/site-packages/yum/sqlutils.py", line 166, in executeSQLQmark
    return cursor.execute(query)
sqlite3.OperationalError: disk I/O error
[gmk@centos7-x64 ~]$ echo $?
1
[gmk@centos7-x64 ~]$ df -h /tmp1/
Filesystem      Size  Used Avail Use% Mounted on
none             98M   98M     0 100% /tmp1
[gmk@centos7-x64 ~]$ 
```

I wonder if the version of YUM that Debian includes just didn't error out properly compared to what I'm running.

**Comment by yarikoptic** [comment] 2016-07-16 16:11
Or it happened at a different spot. Iirc wasn't 100% full, but just too little left

**Comment by gmkurtzer** [comment] 2016-07-16 16:16
Indeed... I will keep an eye out for this.

I am going to close the ticket, both because the initial issue has been resolved and I can't replicate. With that said, if you see it happen again or can identify the cause please do comment on the ticket (and I will reopen it), or create a new ticket.

Thanks!

**Closed as completed by gmkurtzer** 2016-07-16 16:16 UTC
