### ISSUE TITLE
Document release tarball modifications

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#1252] opened 2018-01-13 03:45 UTC
## Version of Singularity:

Any. 

### Expected behavior

Source tag contents, i.e. archives such as:
https://github.com/singularityware/singularity/archive/2.4.2.tar.gz
(or built via `git archive`) are identical to release tarballs such as:
https://github.com/singularityware/singularity/releases/download/2.4.2/singularity-2.4.2.tar.gz
or the differences are well documented to allow to reproduce the release tarballs. 

### Actual behavior

It seems at least `autoreconf` / `./autogen.sh` has been run for the release tarball, since there is additional cruft in the release tarballs. 

The documentation could be part of the release checklist, so it's also not forgotten what exactly needs to be done for a new release. 
It should also contain which exact environment, automake version etc. is used to allow for reproducibility.

**Comment by jmstover** [comment] 2018-01-15 19:35
`git archive` behaves differently... it's not what one would consider a "distribution" release but a copy of the git repo at a point in time. From `man git-archive`:

```
Creates an archive [...] containing the tree structure for the named tree [...]
```

In the good old days, in a distribution archive one did not get the files to rebuild the `Makefile.in` or `configure` script (i.e. `Makefile.am`, `configure.ac`, etc...). What was distributed was just what was needed to run: `./configure && make && make install`

You could get a full source archive, or checkout from revision control a copy, if you needed to customize building the configure scripts. But that was different from the release distribution file.

So, for the release tar ball, I'm expecting what is ran is:

`./autogen.sh && ./configure && make dist-gzip`

The `make dist` targets are going to grab pretty much everything in the structure. By the point it's ran that's going to include `Makefile.in` or `Makefile.am` files ... since nothing is being explicitly added or excluded.

So, in general, you can look at it like:

`make clean` - Clean structure back to where `make` needs to be ran
`make distclean` - Clean structure back to where `./configure` needs to be ran
`make maintainer-clean` - Clean structure back to where `autoreconf` (or the like) needs to be ran.

**Comment by olifre** [comment] 2018-01-15 21:58
> ./autogen.sh && ./configure && make dist-gzip

If this is the case, then I think the best would be to document it in:
https://github.com/singularityware/singularity/blob/master/.github/RELEASE_CHECKLIST.md
to ensure:
- Everybody doing a release at any point in time will use the same procedure. 
- Others know exactly how to reproduce those tarballs uploaded on github releases. 

All this automake stuff is surely confusing compared to other, more modern build systems. 
For cmake, waf, meson and anything recently modern, there's just no difference needed between release and git tree. This simplifies life a lot, since build instructions from git and release are exactly the same, and also packaging of live packages from git can do exactly the same as packaging from a release. It also allows to just tag a release and github offers the tarball for you. 

But well, it seems singularity has chosen to have a fresh start with automake, and embrace the disadvantages, especially configure overhead, that come with autohell ( http://www.shlomifish.org/open-source/anti/autohell/ ) while large projects have already moved on from that dead end in 2006 ( https://lwn.net/Articles/188693/ ). 

But let's not enter a philosophical discussion here - so I'm only asking here to get the "making releases" procedure documented so it's reproducible. Adding a line like:

```
Finally, build a release tarball with
 ./autogen.sh && ./configure && make dist-gzip
```
in https://github.com/singularityware/singularity/blob/master/.github/RELEASE_CHECKLIST.md
should do the trick. 

Does this sound fine?

**Comment by jmstover** [comment] 2018-01-15 22:09
@gmkurtzer @GodloveD @vsoch Speak up here if you would ... =)

@olifre The issue I see, is that file (`RELEASE_CHECKLIST.md`) is what is done for prepping the _repository_ for release. It's not about what steps are done for the release package tarball. 

I would assume adding that in would be okay... but, someone else is going to need to speak up on it. I personally wouldn't with how that file is currently written... but, that's me.

**Comment by olifre** [comment] 2018-01-15 22:13
> I would assume adding that in would be okay... but, someone else is going to need to speak up on it. I personally wouldn't with how that file is currently written... but, that's me.

Reading through it, it also contains the "announcement" part, which surely happens after building the release tarball, so from my point of view, I'd say it's the missing link in the document at the moment :wink:. 

Of course, if there is another more relevant place, I'll not speak up against it, my main concern / wish is to have a cleanly documented way on how to reproduce the release tarballs (and ensure the technique to produce them will stay stable / documented no matter who does the actual release in ten years from now).

**Comment by vsoch** [comment] 2018-01-15 22:34
I think the `RELEASE_CHECKLIST.md` is a "human friendly" list for us to look over before a Github release (+1 @jmstover) and I agree that the actual generation of the tarball needs to be reproducible (+1 @olifre). I would say that our current checklist should have a bullet something along the lines of "build release tarball according to X" where X is a reproducible set of instructions for the tarball. I would even say that it should be an actual script, and perform some sanity checks.

**Comment by olifre** [comment] 2018-01-15 22:35
> I would even say that it should be an actual script, and perform some sanity checks.

+1 on this! 👍 
Especially, it could check that for example the version in debian changelog, tarball name, spec file etc. all agree and things like that.

**Comment by jscook2345** [comment] 2018-10-23 16:21
I believe this is fixed with our new build system / build process. Please reopen if you have any issues. Thanks!

**Closed as completed by jscook2345** 2018-10-23 16:21 UTC
