### ISSUE TITLE
Can create invalid app names (containing "-" characters)

### ISSUE THREAD

**Issue by alhirzel** [apptainer/singularity#5091] opened 2020-03-04 19:55 UTC
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
bf6bdb5
```

### Expected behavior

Work or throw an informative error.

### Actual behavior

Error when launching the container:

```
/.singularity.d/env/94-appsbase.sh: line 3: SCIF_APPDATA_a-b=/scif/data/a-b: No such file or directory
/.singularity.d/env/94-appsbase.sh: line 4: SCIF_APPMETA_a-b=/scif/apps/a-b/scif: No such file or directory
/.singularity.d/env/94-appsbase.sh: line 5: SCIF_APPROOT_a-b=/scif/apps/a-b: No such file or directory
/.singularity.d/env/94-appsbase.sh: line 6: SCIF_APPBIN_a-b=/scif/apps/a-b/bin: No such file or directory
/.singularity.d/env/94-appsbase.sh: line 7: SCIF_APPLIB_a-b=/scif/apps/a-b/lib: No such file or directory
/.singularity.d/env/94-appsbase.sh: line 9: export: `SCIF_APPDATA_a-b': not a valid identifier
/.singularity.d/env/94-appsbase.sh: line 9: export: `SCIF_APPMETA_a-b': not a valid identifier
/.singularity.d/env/94-appsbase.sh: line 9: export: `SCIF_APPROOT_a-b': not a valid identifier
/.singularity.d/env/94-appsbase.sh: line 9: export: `SCIF_APPBIN_a-b': not a valid identifier
/.singularity.d/env/94-appsbase.sh: line 9: export: `SCIF_APPLIB_a-b': not a valid identifier
/.singularity.d/env/94-appsbase.sh: line 10: export: `SCIF_APPLABELS_a-b=/scif/apps/a-b/scif/labels.json': not a valid identifier
/.singularity.d/env/94-appsbase.sh: line 11: export: `SCIF_APPRUN_a-b=/scif/apps/a-b/scif/runscript': not a valid identifier
```

### Steps to reproduce this behavior

Try to make an image with an app named with a dash, e.g. `a-b`. Here is a recipe:

```
Bootstrap: docker
From: centos:centos8
%apprun a-b
	echo "Hello, World!"
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

### How did you install Singularity

Unsure - please comment if this info is needed.

**Comment by cclerget** [comment] 2020-03-05 08:21
Hi @alhirzel , I'm closing this one as duplicate of #4799, please follow up #4799. Thanks !

**Closed as completed by cclerget** 2020-03-05 08:21 UTC
