### ISSUE TITLE
`> /dev/stdout` denied on MacOS

### ISSUE THREAD

**Issue by bjarthur** [apptainer/singularity#4446] opened 2019-09-15 12:22 UTC
here is another difference between running a container on linux vs mac.  i can't explicitly pipe to /dev/stdout on the latter.

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132

$ singularity --version
singularity version 3.3.0-rc.1.658.g7427b73f1.dirty

$ singularity shell library://sylabsed/examples/lolcow
Singularity lolcow_latest.sif:~> echo foo
foo
Singularity lolcow_latest.sif:~> echo foo > /dev/stdout
bash: /dev/stdout: Permission denied
Singularity lolcow_latest.sif:~> exit
[   72.047648] reboot: Power down
```

```
$ cat /etc/*-release
NAME="Scientific Linux"
VERSION="7.4 (Nitrogen)"
ID="rhel"
ID_LIKE="scientific centos fedora"
VERSION_ID="7.4"
PRETTY_NAME="Scientific Linux 7.4 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.4:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.4
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.4"
Scientific Linux release 7.4 (Nitrogen)
Scientific Linux release 7.4 (Nitrogen)
Scientific Linux release 7.4 (Nitrogen)

$ singularity --version
singularity version 3.2.1-1.1.el7

$ singularity shell library://sylabsed/examples/lolcow
Singularity lolcow_latest.sif:~> echo foo
foo
Singularity lolcow_latest.sif:~> echo foo > /dev/stdout
foo
Singularity lolcow_latest.sif:~> exit
```

**Comment by jmstover** [comment] 2019-09-16 16:52
A duplicate of #3606 ... 

Ugh... I don't know what we're doing wrong that's breaking the I/O handling since input/output is working right...

**Closed as completed by jmstover** 2019-09-16 16:52 UTC
