### ISSUE TITLE
name of container from singularity hub

### ISSUE THREAD

**Issue by jokedurnez** [apptainer/singularity#573] opened 2017-04-07 20:26 UTC
Not sure if this goes here, but...
It would be cool when pulling from singularity hub if the name of the container would include the hash and the date of the latest commit.

**Comment by vsoch** [comment] 2017-04-07 22:57
Hey @jokedurnez ! It's funny, because the initial version used the hash or commit id as the container name, but we changed it to be something that was more human friendly given the common use case of pull to be like "give me this container on my Desktop so I can run it" as opposed to "hide this container in some folder I don't know about it and call it when I issue a command."

I'm guessing you are working in Python? You can use the Singularity Hub API to get these metrics, and embarrassingly I don't expose the build date, oups.

```python
import requests

container = "https://singularity-hub.org/api/container/jokedurnez/HCPPipelines"
response = requests.get(container)

manifest = response.json()
version = manifest['version'] # this is the commit

import demjson
metrics = demjson.decode(manifest['metrics'])


# To get the latest version of a collection, across all tags (branches)
container = "https://singularity-hub.org/api/container/jokedurnez/HCPPipelines:latest"

# What we did above for the first call is equivalent to this
container = "https://singularity-hub.org/api/container/jokedurnez/HCPPipelines:master"

# Or you can get a custom tag like
container = "https://singularity-hub.org/api/container/vsoch/singularity-images:mongo"
response = requests.get(container)
```

For future reference, singularity hub issues can go [here](https://github.com/singularityhub/singularityhub.github.io/issues)

And I've added the request to add the date to the manifest above! The hash (of the file) is also kept, although not properly exposed.

**Comment by vsoch** [comment] 2017-04-07 23:04
Oh, and there is also now a client for singularity python that is just for working with Singularity Hub, and it will be properly released with Singularity 2.3. Right now it lives on [this branch](https://github.com/vsoch/singularity-python/tree/add/client) of my fork. It lets you do stuff like:

```python
from singularity.hub.client import Client

shub = Client()    # Singularity Hub Client
container_id = 60

# Get container manifest
manifest = shub.get_container(container_id)

image = shub.pull_container(manifest,
                           download_folder="/home/vanessa/Desktop",
                           name="zomg-so-cool-container.img.gz")       

metrics = shub.load_metrics(manifest)


# And assess container similarity based on different hash filters
from singularity.reproduce import (
    assess_differences,
    get_levels
)

levels = get_levels()
container1='image1.img'
container1='image2.img'
diffs = assess_differences(container1,container2,levels=levels)

# Package Trees
from singularity.views.trees import make_package_tree
fig = make_package_tree(matrix=diffs,title="Singularity Hub Replication Scores")
fig.savefig('treee.png' %base)

# Interactive tree
tree = make_interactive_tree(matrix=diffs)
```

And a whole bunch of other stuff I haven't pushed up yet - the reproducibility metrics should be submit in a paper this weekend, they are super cool!!

**Comment by gmkurtzer** [comment] 2017-04-07 23:17
Hi @jokedurnez, are you thinking of the name used at the shell prompt?

**Comment by jokedurnez** [comment] 2017-04-08 00:22
Yeah, I mean it's so little effort I could rename the files myself, but I *think* this filename structure (with hash) was implemented in docker2singularity and I miss it :-).
We're sharing singularity containers with a bunch of people and that was handy to quickly (1) store different versions that are used for different projects and (2) see if the latest version is on our system.
Again: it's easy to do this ourselves, but it was a nice feature that now has disappeared :-)

**Comment by vsoch** [comment] 2017-04-08 00:32
ah, sorry. If you want, you can just use the download code and roll the pull yourself, naming the container whatever you like! @gmkurtzer what do you think about giving the user the option to specify a custom name via an environment variable, or an environment variable that if present, names based on the commit?

For reference if you want a solution asap, [here is the code](https://github.com/singularityware/singularity/blob/development/libexec/python/shub/main.py#L65).

**Comment by gmkurtzer** [comment] 2017-04-08 00:38
Nice features should always stay, it's just the bad features (otherwise known as bugs) that we want to squish! Heh

Is it possible to download the tag too? If not, sure, we can offer an option to include a name. :)

**Comment by vsoch** [comment] 2017-04-08 00:43
The commit can be accessed via the manifest, which yes means we could name the images based on it.

**Comment by vsoch** [comment] 2017-04-08 00:56
Give me a few minutes :)

**Comment by vsoch** [comment] 2017-04-08 01:48
done! See https://github.com/singularityware/singularity/pull/574

btw, I had a rather glorious bug when I was coding this up...

![image](https://cloud.githubusercontent.com/assets/814322/24824316/27ae45fe-1bd7-11e7-9d1f-42f773aa17ab.png)

**Comment by gmkurtzer** [comment] 2017-04-08 14:52
@vsoch Eatballs?! Uhmm... V?!!

**Comment by jokedurnez** [comment] 2017-04-08 17:30
Wuuhuu :-)
Thanks!

**Comment by vsoch** [comment] 2017-04-08 17:39
lol it was a total accident! The best of my coding career, lol.

**Comment by vsoch** [comment] 2017-04-08 22:57
PR is merged - @jokedurnez you can use the development branch, and do like:

```bash
singularity pull --hash shub://vsoch/singularity-images
singularity pull --commit shub://vsoch/singularity-images
singularity pull --name "meatballs.img" shub://vsoch/singularity-images
```
for hash (of file), commit, and name, respectively! I'm going to close issue, please re-open if necessary!

**Closed as completed by vsoch** 2017-04-08 22:57 UTC
