### ISSUE TITLE
SINGULARITYENV  PATH environment variables ignored during exec of container downloaded from shub and library repositories

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#2731] opened 2019-02-18 22:59 UTC
## Version of Singularity:

master

### Expected behavior

<pre>
$ SINGULARITYENV_APPEND_PATH="/foo" singularity exec library://default/alpine printenv PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/foo
</pre>

### Actual behavior

<pre>
$ SINGULARITYENV_APPEND_PATH="/foo" singularity exec library://default/alpine printenv PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
</pre>

### Steps to reproduce behavior

See expected / actual behavior. Also fails for `SINGULARITYENV_PREPEND_PATH` and `SINGULARITYENV_PATH`. This not only fails for `library://` transport but also `shub://`. Probably because we do an actual build when we use `docker://` but follow a different execution path with the other two.

**Comment by ikaneshiro** [comment] 2019-02-19 22:37
@jscook2345 Looks like this is caused by `SINGULARITYENV_[APPEND/PREPEND]_PATH` functionality relying on a script at `/.singularity.d/env/99-runtimevars.sh` within the container. This script was introduced by #2045 so for images built before this PR we can't do anything unless we want to change the implementation to be handled purely by the runtime. @GodloveD Am I correct?

**Comment by GodloveD** [comment] 2019-02-19 22:45
Yes, you are correct @ikaneshiro.  I think the solution is to re-introduce `/.singularity.d/env/99-runtimevars.sh` within the container.  It's my understanding that this file is not being created with new containers built using 3.x.  Is that correct?

**Comment by GodloveD** [comment] 2019-02-21 01:12
This is basically fixed now (at least as best as it can be without doing things that are unsustainable).

**Closed as completed by GodloveD** 2019-02-21 01:12 UTC
Labels: Bug, env
