### ISSUE TITLE
Singularity for interactive jobs with HTCondor: "openpty: No such file or directory"

### ISSUE THREAD

**Issue by olifre** [apptainer/singularity#857] opened 2017-08-04 13:15 UTC
## Version of Singularity:

Singularity 2.3.1. 

### Expected behavior

sshd running in container started with `singularity -C` works fine. 

### Actual behavior

sshd cannot allocate a tty due to missing `/dev/ptmx`? (at least). 

### Steps to reproduce behavior

Run an interactive job with htcondor. 

Hi,

I am not at all sure this is an actual "bug" or something which requires an elaborate workaround. 

I am trying to use singularity 2.3.1 on CentOS 7.3 with HTCondor 8.6.5. 
For interactive jobs, HTCondor performs the following magic:
- sshd is started on the worker node with a special configuration and a job-specific host-keypair. 
- The execute node connects to that, effectively entering the job environment. 

Using singularity, this means sshd will be running inside the container. I am using a container with sshd and a configuration with `UsePrivilegeSeparation no` to let sshd running as user work fine. 
However, since `/dev/ptmx` is missing (HTCondor singularity integration calls `singularity -C` internally), sshd can not allocate a ptty. 

Are there best practices / any good idea to work around this issue? Would it technically be possible to have singularity create the ncessary files for ptty allocation in a `-C` container?

For reference, here is the information I already collected for the HTCondor mailing list (which, up to now, did not give me new ideas):
https://www-auth.cs.wisc.edu/lists/htcondor-users/2017-August/msg00029.shtml
https://www-auth.cs.wisc.edu/lists/htcondor-users/2017-August/msg00033.shtml

Cheers and all the best,
Oliver

**Comment by hollowec** [comment] 2017-08-07 15:30
One potential solution to this issue would be mount a new instance of devpts in the container when -C is passed to shell/exec.  This should preserve isolation from the host, while allowing applications performing pseudoterminal allocation to function.  I've submitted PR #863 as a possible fix, and have tested it successfully with xterm pty allocation.

**Comment by olifre** [comment] 2017-08-07 16:05
> One potential solution to this issue would be mount a new instance of devpts in the container when -C is passed to shell/exec.

Sounds good! I will also give the PR a spin, many thanks!

**Comment by olifre** [comment] 2017-08-07 18:39
@hollowec I get very strange behaviour - I have applied that patch to 2.3.1. 

First, a test without singularity, i.e. I made condor forget about singularity for now to perform some debugging. 

Running `condor_submit -interactive` connecting to a fresh workernode, all is fine, i.e. condor runs sshd as the uid of a normal user and openpty works. 

Now, I run once (on the worker):
```
singularity exec -B /usr/libexec/condor/ -B /home/olifre/sshd --pwd /srv -S /var/tmp -S /tmp -C /scratch/foo.img strace /usr/sbin/sshd -d -e -f /home/olifre/sshd/sshd_config -p 10000
```
and connect to that via `ssh localhost -p 10000`. 
Even though I can confirm ptmx exists inside the container, I get:
```
write(2, "debug1: Allocating pty.\r\n", 25debug1: Allocating pty.
) = 25
open("/dev/ptmx", O_RDWR)               = -1 EACCES (Permission denied)
open("/dev/ptyp0", O_RDWR)              = -1 ENOENT (No such file or directory)
write(2, "openpty: No such file or directo"..., 36openpty: No such file or directory
) = 36
write(2, "session_pty_req: session 0 alloc"..., 41session_pty_req: session 0 alloc failed
```

After this has happened, also the host is broken, i.e. rerunning `condor_submit -interactive` which starts sshd as user fails to allocate a pty with "permission denied". 

Technically, that's reproducibe without condor by just running sshd as user. 
1. Run on the host, all is well. 
2. Run in the container, permission denied. 
3. Run again in the host, permission denied. 

It seems there is some ugly crosstalk...

**Comment by hollowec** [comment] 2017-08-07 19:01
Well that's odd.  This didn't occur for me during testing (Host Fedora 26, 
container Fedora 25).  However, I had also built against development (not the 2.3.1 release).  I'll try to reproduce with sshd.  What OS are you using, and can you
send the output of: ls -ld /dev/ptmx /dev/pts ; ls -l /dev/pts ; grep devpts /proc/mounts from the host?

**Comment by olifre** [comment] 2017-08-07 19:17
The host here is a CentOS 7.3 machine, the container was an Ubuntu 16.04 LTS. 

After a fresh boot, I get:
```
[root@wn001 ~]# ls -ld /dev/ptmx /dev/pts ; ls -l /dev/pts ; grep devpts /proc/mounts
crw-rw-rw-. 1 root tty  5, 2  7. Aug 21:09 /dev/ptmx
drwxr-xr-x. 2 root root    0  7. Aug 21:08 /dev/pts
insgesamt 0
crw--w----. 1 root tty  136, 0  7. Aug 21:09 0
c---------. 1 root root   5, 2  7. Aug 21:08 ptmx
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
```
After running singularity with sshd inside, the host looks like: 
```
[root@wn001 ~]# ls -ld /dev/ptmx /dev/pts ; ls -l /dev/pts ; grep devpts /proc/mounts
crw-rw-rw-. 1 root tty  5, 2  7. Aug 21:15 /dev/ptmx
drwxr-xr-x. 2 root root    0  7. Aug 21:08 /dev/pts
insgesamt 0
crw--w----. 1 root tty  136, 0  7. Aug 21:15 0
c---------. 1 root root   5, 2  7. Aug 21:08 ptmx
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,mode=600,ptmxmode=666 0 0
```
It seems the mount permissions have changed... 

On a side-note:  I currently have SELinux disabled on the machine.

**Comment by hollowec** [comment] 2017-08-07 19:41
OK, so I tried on an CentOS 7 system.  Unlike in newer kernels, apparently the CentOS 7 kernel (3.10.0-XYZ) doesn't automatically create a new instance of devpts when mounting.  It is necessary to pass the "newinstance" flag to the mount.  Without it, the modes of the new mount are apparently bleeding through to the original mount (and there is no containment), which can obviously be very bad.  I'll modify the patch to include the "newinstance" parameter, but I think it should also check if the running kernel supports new instances of devpts before trying to mount, to be safe.

**Comment by olifre** [comment] 2017-08-07 20:06
> OK, so I tried on an CentOS 7 system. Unlike in newer kernels, apparently the CentOS 7 kernel (3.10.0-XYZ) doesn't automatically create a new instance of devpts when mounting. It is necessary to pass the "newinstance" flag to the mount.

Thanks a lot for doing this research! This for sure explains it, and I guess it also explains why sshd won't start in the container in the first place. 
Take your time for the updated patch, checking for kernel support for sure is the safest option, bleeding mount modes for programs a user can call for sure are a bad thing.

**Comment by olifre** [comment] 2017-08-09 13:42
In the meantime, I tried the patch with "newinstance", but got (inside sshd debug log):
```
chown(/dev/pts/0, 4519, 5) failed: Operation not permitted
```
4519 is my user ID. Running sshd as my user works fine outside the container, but not inside. 
I'll investigate a bit further (using gdb on sshd to see what the stat of /dev/pts reveals), but maybe you already have an idea on this...

**Comment by olifre** [comment] 2017-08-09 14:22
Testing with a CentOS 7 container, things fail even earlier (in a chown called via openpty). Reason is the same. 

The problem appears to be that the newly created `/dev/pts/0` has wrong permissions and ssh / openpty tries to fix that:
```
$ ls -lan /dev/pts/0
crw-------. 1 4519 4519 136, 0 Aug  9 14:16 /dev/pts/0
```
4519 is my user ID, ssh / openpty try to enforce "tty" to be the associated group. 

The difference is also seen in the mount options. On the CentOS 7 host:
```
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,gid=5,mode=620,ptmxmode=000)
```
while in the container:
```
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,seclabel,mode=600,ptmxmode=666)
```
Group ID 5 is the group "tty". 

What's the correct way to fix that? Potentially call `getgrpnam("tty")` and use the resulting gid in the devpts mount options explicitly?

Many thanks for your support!
Oliver

**Comment by hollowec** [comment] 2017-08-09 14:54
Yes, I noticed during some more recent testing that sshd is attempting to chown the group of the pty device, causing it to fail.  xterm does not do this, so I initially didn't run into this problem.  Unfortunately, some applications performing pseudoterminal allocation expect the pty to be group owned by "tty", and sshd is one of them.  As you mentioned, I believe the best/safest solution is likely to assign the gid mount parameter the tty group gid from the host (i.e via getgrpnam()), and mount with mode=0620 (still with ptmxmode=0666).  This won't work if the container has a different gid for "tty", but it is typically the same in distributions I've seen.  This resolved the problem during my tests, and allowed sshd to function properly.

In the meantime, I believe I've identified a way to determine if multiple instance devpts is supported by the kernel.  I'm continuing some tests, and will likely submit a new PR in the next day or two.

**Comment by olifre** [comment] 2017-08-09 15:08
> In the meantime, I believe I've identified a way to determine if multiple instance devpts is supported by the kernel. I'm continuing some tests, and will likely submit a new PR in the next day or two.

Perfect, many thanks! Then I will just wait for this - we are still in the process of setting up our new HPC cluster, and there are many other open issues to attack in the meanwhile.

**Comment by hollowec** [comment] 2017-08-14 15:47
I just submitted PR #871 as a potential solution to this after some more testing.  Besides checking for kernel support for multi-instance devpts, it also adds a new configuration option (mount devpts) which must be enabled.

**Comment by olifre** [comment] 2017-08-14 17:14
@hollowec: Many thanks, I can confirm this works in our setup with CentOS 7!

Sadly, HTCondor interactive jobs still suffer several other severe issues with singularity:
https://www-auth.cs.wisc.edu/lists/htcondor-users/2017-August/msg00078.shtml
but this needs to be fixed on the HTCondor end  - unless: Would it technically be possible to:
```
singularity exec -C someimage somexecutable
singularity exec -C someimage anotherexecutable
```
and have the second instance run within in the same namespace / container (i.e. "attach" and see the same PIDs?). If yes, I'd open that as a feature request (unless already possible). If no, HTCondor needs to solve this somehow differently (they run a job, then on-demand execute sshd in the same environment to let users look at the job, the same technique is used for interactive jobs).

**Comment by hollowec** [comment] 2017-08-14 17:44
> singularity exec -C someimage somexecutable
> singularity exec -C someimage anotherexecutable
> and have the second instance run within in the same namespace / container

While I'm not familiar with this functionality, a few days ago I noticed that a lot of code which may provide this was recently merged into development: PR #839 (adds --join).

**Comment by olifre** [comment] 2017-08-14 18:03
@hollowec: Many thanks for the link, didn't notice that! While it seems to be meant for use with services, indeed that seems to match my idea. 
I'll try to get into deeper contact with the HTCondor guys, maybe they'll pick up on that. In any case, singularity support in HTCondor is very lacking right now (and it's not the fault of singularity).

**Comment by olifre** [comment] 2017-10-14 22:59
I can confirm things work fine out of the box with Singularity 2.4, so I think this can be closed. 
The remaining issues related to interactive jobs are all on the HTCondor end. Thanks again!

**Comment by olifre** [comment] 2017-10-26 12:42
Hi @hollowec , 
I sadly have to re-open. 
Testing with user namespaces (i.e. no SUID, no overlay options), I again see:
```
debug1: Allocating pty.
openpty: No such file or directory
session_pty_req: session 0 alloc failed
```
in my sshd logfiles. 

Checking from inside the container, I see:
```
Singularity> ls -lrta /dev/pts/
total 0
drwxr-xr-x. 2 olifre olifre  40 Oct 26 14:40 .
drwxr-xr-x. 4 olifre olifre 180 Oct 26 14:40 ..
Singularity> ls -lrta /dev/tty 
crw-rw-rw-. 1 65534 65534 5, 0 Oct 26 12:30 /dev/tty
Singularity> 
```
Are these the expected permissions and owners? I am running as myself (`olifre`) and 65534 is the default overflow UID / GID of the kernel used for user namespaces.

**Comment by hollowec** [comment] 2017-10-26 17:36
Unfortunately, mounting a new instance of devpts fails when using user namespaces (non-setuid) due to a permission issue associated with the 'gid=' flag being passed (if you run with verbose output, you should see a "Couldn't mount /dev/pts, continuing" message).  I have a fork that I've been testing that doesn't pass 'gid=' to the mount when setuid is disabled, but sshd will still complain that the pts devices are not group owned by the 'tty' group.  I'll look into a solution to this, but it may not be possible to solve this for the non-setuid use case (just like you cannot use overlays in this mode).

**Comment by olifre** [comment] 2017-10-26 18:57
> I'll look into a solution to this, but it may not be possible to solve this for the non-setuid use case (just like you cannot use overlays in this mode).

Many thanks for looking into it!
In case it really turns out there is no non-SUID solution possible within Singularity, the essence would be:
- HTCondor interactive jobs can not be used with username namespaces. 
- Connecting to HTCondor jobs running in (non-SUID-started) containers for debugging will not be possible. 

Since most cluster sysadmins will avoid SUID if possible, and I'd even guess that it becomes a WLCG requirement, and at the same time HTCondor appears to be come the most wide-spread batch system (with also CERN switching to it), I'd expect a different solution has to be found:
- Teaching OpenSSH to (be able to, i.e. configurably) ignore the the `pts` device ownership (if that is sufficient to let things work). OpenSSH upstream is very sensitive to potential security-implications of such features, but it would likely be possible to reason with them that running sshd within a user namespace is worthwhile. 
- Teaching the kernel to treat the `devpts` namespace special within a user namespace, e.g. by doing a special owner mapping for the devices. I'm not sure how high the probability for such a request to success is, but if sshd will not run without such a modification, that might be a good point. 

Let me know what you find and what you think - missing the overlay-feature for sure is something sites can live without, but I'm pretty sure HTCondor sites will not be happy without `sshd` working inside the containers (and at the same time, most sites will not want SUID binaries). 

Many thanks! :)

**Comment by DrDaveD** [comment] 2017-11-28 21:31
There's a little more info on devpts with unprivileged namespaces on el7 in #944.

**Comment by olifre** [comment] 2017-11-28 22:10
Thanks for pointing me to this!

EDIT: I added a comment to the mentioned PR with a correct fix (instead of silently disabling the feature) that could be applied.

**Comment by olifre** [comment] 2017-12-01 02:02
@hollowec Should we close this issue (general implemenation) in favour of the new one (missing support for user namespaces)?

**Comment by hollowec** [comment] 2017-12-01 15:34
Yes, I think you can go ahead and close this one.

**Closed as completed** 2017-12-01 15:41 UTC
