### ISSUE TITLE
No longer binding my work directory

### ISSUE THREAD

**Issue by thomas-robinson** [apptainer/singularity#5851] opened 2021-02-24 16:28 UTC
### Version of Singularity:

singularity version 3.7.1

### Expected behavior
When I ran singularity before upgrading to 3.7.1, the directory that I ran singularity in would be bound to my container.  After they updated, the directory is no longer bound automatically.  They suggested I opened an issue with you to see if this is an issue.
```sh
$ pwd
/work/noaa/gfdlscr/trobinso/awg/xanadu/c96L33_am4p0_cmip6Diag/orion.intel18-prod-openmp-sing/scripts/run
$ singularity exec docker://ubuntu:latest pwd
INFO:    Using cached SIF image
/work/noaa/gfdlscr/trobinso/awg/xanadu/c96L33_am4p0_cmip6Diag/orion.intel18-prod-openmp-sing/scripts/run
```

### Actual behavior

```bash
$ pwd
/work/noaa/gfdlscr/trobinso/awg/xanadu/c96L33_am4p0_cmip6Diag/orion.intel18-prod-openmp-sing/scripts/run
$ singularity exec docker://ubuntu:latest pwd
INFO:    Using cached SIF image
/home/trobinso
```

### Steps to reproduce this behavior

Go to a file system folder that isn't in your home and run the singularity command
`singularity exec docker://ubuntu:latest pwd`

### What OS/distro are you running

```
$ cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

I am not a sys admin, but they assured me nothing changed with their new install.

**Comment by dtrudg** [comment] 2021-02-24 17:10
This is an intended behaviour change. See also: https://github.com/hpcng/singularity/issues/5846 which is a duplicate of this issue

The CWD (current working directory) will only be available if it is bound in by another method (e.g. if it is under your home directory, or a system or user bind).

If you are under `/work` than you can add `-B /work` to bind it.

**Closed as completed by dtrudg** 2021-02-24 17:10 UTC
Labels: wontfix
