### ISSUE TITLE
exec /.singularity.d/actions/shell failed: no such file or directory

### ISSUE THREAD

**Issue by jameshclrk** [apptainer/singularity#2383] opened 2018-11-20 18:03 UTC
## Version of Singularity:

3.0.1

### Expected behavior

Get a shell or run a container

### Actual behavior

Get an error message when trying to use `singularity exec` or `singularity shell`

### Steps to reproduce behavior
Tried with alpine from library and ubuntu from docker

I have looked at the other issues, but the fixes there do not seem to work.

```
[jclark ~]$ singularity -vd shell library://library/default/alpine
WARNING [U=1000,P=1768]    sylabsToken()                 Authentication token file not found : Only pulls of public images will succeed
DEBUG   [U=1000,P=1768]    apiGet()                      apiGet calling https://library.sylabs.io/v1/images/library/default/alpine:latest
DEBUG   [U=1000,P=1768]    initCacheDir()                Creating cache directory: /home/jclark/.singularity/cache/library/sha256.69ce2a3dcc6d3e559e20ced0df251046ee6ecff390a945d856fe0dcb3bcb3ce8
DEBUG   [U=1000,P=1768]    updateCacheSubdir()           Caching directory set to /home/jclark/.singularity/cache/library/sha256.69ce2a3dcc6d3e559e20ced0df251046ee6ecff390a945d856fe0dcb3bcb3ce8
DEBUG   [U=1000,P=1768]    updateCacheSubdir()           Caching directory set to /home/jclark/.singularity/cache/library
DEBUG   [U=1000,P=1768]    updateCacheSubdir()           Caching directory set to /home/jclark/.singularity/cache/library/sha256.69ce2a3dcc6d3e559e20ced0df251046ee6ecff390a945d856fe0dcb3bcb3ce8
DEBUG   [U=1000,P=1768]    updateCacheSubdir()           Caching directory set to /home/jclark/.singularity/cache/library
INFO    [U=1000,P=1768]    handleLibrary()               Downloading library image
DEBUG   [U=1000,P=1768]    DownloadImage()               Pulling from URL: https://library.sylabs.io/v1/imagefile/library/default/alpine:latest
DEBUG   [U=1000,P=1768]    DownloadImage()               OK response received, beginning body download
DEBUG   [U=1000,P=1768]    DownloadImage()               Created output file: /home/jclark/.singularity/cache/library/sha256.69ce2a3dcc6d3e559e20ced0df251046ee6ecff390a945d856fe0dcb3bcb3ce8/alpine_latest.sif
 2.08 MiB / 2.08 MiB [=================================================================================================================================================================================================] 100.00% 3.22 MiB/s 0sDEBUG   [U=1000,P=1768]    DownloadImage()               Download complete
VERBOSE [U=0,P=1768]       print()                       Set messagelevel to: 5
DEBUG   [U=0,P=1768]       init()                        PIPE_EXEC_FD value: 10
VERBOSE [U=0,P=1768]       init()                        Container runtime
VERBOSE [U=0,P=1768]       is_suid()                     Check if we are running as setuid
DEBUG   [U=0,P=1768]       init()                        Overlay seems supported by kernel
DEBUG   [U=0,P=1768]       init()                        Drop privileges
DEBUG   [U=1000,P=1768]    init()                        Read json configuration from pipe
DEBUG   [U=1000,P=1768]    init()                        Set child signal mask
DEBUG   [U=1000,P=1768]    init()                        Create socketpair for smaster communication channel
DEBUG   [U=1000,P=1768]    init()                        Wait C and JSON runtime configuration from scontainer stage 1
DEBUG   [U=1000,P=1786]    set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1000,P=1786]    init()                        Spawn scontainer stage 1
VERBOSE [U=1000,P=1786]    priv_escalate()               Get root privileges
DEBUG   [U=0,P=1786]       set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=1786]       prepare_scontainer_stage()    Entering in scontainer stage 1
DEBUG   [U=1000,P=1786]    set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1000,P=1786]    startup()                     Execute scontainer stage 1
DEBUG   [U=1000,P=1786]    SContainer()                  Entering scontainer stage 1
DEBUG   [U=1000,P=1786]    Init()                        Entering image format intializer
DEBUG   [U=1000,P=1786]    Init()                        Check for image format sif
DEBUG   [U=1000,P=1768]    init()                        Receiving configuration from scontainer stage 1
DEBUG   [U=1000,P=1768]    init()                        Wait completion of scontainer stage1
VERBOSE [U=1000,P=1768]    priv_escalate()               Get root privileges
VERBOSE [U=0,P=1768]       create_namespace()            Create mount namespace
DEBUG   [U=0,P=1768]       init()                        Create RPC socketpair for communication between scontainer and RPC server
VERBOSE [U=0,P=1768]       init()                        Spawn smaster process
DEBUG   [U=0,P=1793]       set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=0,P=1793]       init()                        Spawn scontainer stage 2
VERBOSE [U=0,P=1793]       create_namespace()            Create mount namespace
VERBOSE [U=0,P=1794]       init()                        Spawn RPC server
VERBOSE [U=1000,P=1768]    startup()                     Execute smaster process
DEBUG   [U=1000,P=1768]    setupSessionLayout()          Attempting to use overlayfs (enable overlay = try)
DEBUG   [U=1000,P=1768]    setupOverlayLayout()          Creating overlay SESSIONDIR layout
DEBUG   [U=1000,P=1768]    addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=1000,P=1768]    addRootfsMount()              Mounting block [squashfs] image: /home/jclark/.singularity/cache/library/sha256.69ce2a3dcc6d3e559e20ced0df251046ee6ecff390a945d856fe0dcb3bcb3ce8/alpine_latest.sif
DEBUG   [U=1000,P=1768]    addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=1000,P=1768]    addKernelMount()              Adding proc to mount list
DEBUG   [U=1000,P=1768]    addKernelMount()              Checking configuration file for 'mount sys'
DEBUG   [U=1000,P=1768]    addKernelMount()              Adding sysfs to mount list
DEBUG   [U=1000,P=1768]    addDevMount()                 Checking configuration file for 'mount dev'
DEBUG   [U=1000,P=1768]    addDevMount()                 Adding dev to mount list
DEBUG   [U=1000,P=1768]    addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=1000,P=1768]    addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=1000,P=1768]    addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=1000,P=1768]    addHomeStagingDir()           Staging home directory (/home/jclark) at /var/singularity/mnt/session/home/jclark
DEBUG   [U=1000,P=1768]    addHomeMount()                Adding home directory mount [/var/singularity/mnt/session/home/jclark:/home/jclark] to list using layer: overlay
DEBUG   [U=1000,P=1768]    isLayerEnabled()              Using Layer system: overlay
DEBUG   [U=1000,P=1768]    addTmpMount()                 Checking for 'mount tmp' in configuration file
DEBUG   [U=1000,P=1768]    addScratchMount()             Not mounting scratch directory: Not requested
DEBUG   [U=1000,P=1768]    addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=1000,P=1768]    addResolvConfMount()          Adding /etc/resolv.conf to mount list
DEBUG   [U=1000,P=1768]    addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=1000,P=1768]    create()                      Mount all
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting tmpfs to /var/singularity/mnt/session
VERBOSE [U=0,P=1794]       startup()                     Serve RPC requests
DEBUG   [U=1000,P=1768]    mountImage()                  Mounting loop device /dev/loop0 to /var/singularity/mnt/session/rootfs
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting overlay to /var/singularity/mnt/session/final
DEBUG   [U=1000,P=1768]    setSlaveMount()               Set RPC mount propagation flag to SLAVE
VERBOSE [U=1000,P=1768]    Passwd()                      Checking for template passwd file: /var/singularity/mnt/session/rootfs/etc/passwd
VERBOSE [U=1000,P=1768]    Passwd()                      Creating passwd content
VERBOSE [U=1000,P=1768]    Passwd()                      Creating template passwd file and appending user data: /var/singularity/mnt/session/rootfs/etc/passwd
DEBUG   [U=1000,P=1768]    addIdentityMount()            Adding /etc/passwd to mount list
VERBOSE [U=1000,P=1768]    Group()                       Checking for template group file: /var/singularity/mnt/session/rootfs/etc/group
VERBOSE [U=1000,P=1768]    Group()                       Creating group content
DEBUG   [U=1000,P=1768]    addIdentityMount()            Adding /etc/group to mount list
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting /dev to /var/singularity/mnt/session/final/dev
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting /etc/localtime to /var/singularity/mnt/session/final/etc/localtime
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting /etc/hosts to /var/singularity/mnt/session/final/etc/hosts
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting /etc/singularity/actions to /var/singularity/mnt/session/final/.singularity.d/actions
DEBUG   [U=1000,P=1768]    mountGeneric()                Remounting /var/singularity/mnt/session/final/.singularity.d/actions
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting /proc to /var/singularity/mnt/session/final/proc
DEBUG   [U=1000,P=1768]    mountGeneric()                Remounting /var/singularity/mnt/session/final/proc
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting sysfs to /var/singularity/mnt/session/final/sys
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting /home/jclark to /var/singularity/mnt/session/home/jclark
DEBUG   [U=1000,P=1768]    mountGeneric()                Remounting /var/singularity/mnt/session/home/jclark
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting /var/singularity/mnt/session/home/jclark to /var/singularity/mnt/session/final/home/jclark
DEBUG   [U=1000,P=1768]    mountGeneric()                Remounting /var/singularity/mnt/session/final/home/jclark
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting /tmp to /var/singularity/mnt/session/final/tmp
DEBUG   [U=1000,P=1768]    mountGeneric()                Remounting /var/singularity/mnt/session/final/tmp
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting /var/tmp to /var/singularity/mnt/session/final/var/tmp
DEBUG   [U=1000,P=1768]    mountGeneric()                Remounting /var/singularity/mnt/session/final/var/tmp
DEBUG   [U=1000,P=1768]    mountGeneric()                Skipping mount /var/singularity/mnt/session/final/home/jclark, /var/singularity/mnt/session/final/home/jclark already mounted
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting /var/singularity/mnt/session/etc/resolv.conf to /var/singularity/mnt/session/final/etc/resolv.conf
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting /var/singularity/mnt/session/etc/passwd to /var/singularity/mnt/session/final/etc/passwd
DEBUG   [U=1000,P=1768]    mountGeneric()                Mounting /var/singularity/mnt/session/etc/group to /var/singularity/mnt/session/final/etc/group
DEBUG   [U=1000,P=1768]    create()                      Chroot into /var/singularity/mnt/session/final
DEBUG   [U=0,P=1794]       Chroot()                      Change current directory to /var/singularity/mnt/session/final
DEBUG   [U=0,P=1794]       Chroot()                      Hold reference to host / directory
DEBUG   [U=0,P=1794]       Chroot()                      Called pivot_root on /var/singularity/mnt/session/final
DEBUG   [U=0,P=1794]       Chroot()                      Change current directory to host / directory
DEBUG   [U=0,P=1794]       Chroot()                      Apply slave mount propagation for host / directory
DEBUG   [U=0,P=1794]       Chroot()                      Called unmount(/, syscall.MNT_DETACH)
DEBUG   [U=0,P=1794]       Chroot()                      Changing directory to / to avoid getpwd issues
DEBUG   [U=1000,P=1768]    create()                      Chdir into / to avoid errors
DEBUG   [U=0,P=1793]       set_parent_death_signal()     Set parent death signal to 9
DEBUG   [U=0,P=1793]       prepare_scontainer_stage()    Entering in scontainer stage 2
DEBUG   [U=1000,P=1793]    set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1000,P=1793]    startup()                     Execute scontainer stage 2
FATAL   [U=1000,P=1793]    SContainer()                  exec /.singularity.d/actions/shell failed: no such file or directory
DEBUG   [U=1000,P=1768]    PostStartProcess()            Post start process
DEBUG   [U=1000,P=1768]    CleanupContainer()            Cleanup container
DEBUG   [U=1000,P=1768]    SMaster()                     Child exited with exit status 255
```

**Comment by cclerget** [comment] 2018-11-20 18:51
@jameshclrk Looks like `/etc/singularity/actions` is empty, is it the case ? it should contains `shell/exec/start/run/test` shell scripts

**Comment by jameshclrk** [comment] 2018-11-20 21:50
No, I have all of those scripts. I just realised I haven't checked the permissions, I will check when I am able to access the machine.

**Comment by jameshclrk** [comment] 2018-11-21 15:45
Yep, the files are there and appear to have the correct permissions.

```
[jclark ~]$ ls -la /etc/singularity/actions/
total 20
drwxr-xr-x. 2 root root  67 Nov 20 16:13 .
drwxr-xr-x. 6 root root 160 Nov 20 17:53 ..
-rwxr-xr-x. 1 root root 131 Nov 20 16:05 exec
-rwxr-xr-x. 1 root root 607 Nov 20 16:05 run
-rwxr-xr-x. 1 root root 617 Nov 20 16:05 shell
-rwxr-xr-x. 1 root root 287 Nov 20 16:05 start
-rwxr-xr-x. 1 root root 588 Nov 20 16:05 test
```

**Comment by cclerget** [comment] 2018-11-21 16:45
@jameshclrk Have you try by building an image rather ? You run image on an x86_64 or x86 platform ?

```
singularity build /tmp/test.sif docker://busybox
singularity shell /tmp/test.sif
```

**Comment by jameshclrk** [comment] 2018-11-23 15:02
Yes, I got the same thing.
I originally built singularity via `rpmbuild -tb singularity-3.0.1.tar.gz` and installed with my package manager.

I then built singularity according to:
```
$ cd $GOPATH/src/github.com/sylabs/singularity
$ ./mconfig -p /some/path
$ cd ./builddir
$ make
$ sudo make install
```
which results in a working installation.

**Comment by jscook2345** [comment] 2018-11-25 17:44
@jameshclrk Are you saying building from the latest source fixed it? It is very possible this is fixed by a PR.

**Comment by jmstover** [comment] 2018-11-25 18:50
There was a umask fix recently. See #2382 as a reference; merged 4 days ago.

I don't see what the permissions *in* the container were for the files in `/.singularity.d/actions/` (would have needed to manually mount the image). So, it's possible there was a `umask` setting, which carried into the container and that made it unusable because of of the permissions that got set on the files.

**Comment by jameshclrk** [comment] 2018-11-26 20:45
I just tried again on a different Fedora 29 machine from the latest `master` commit a50b5b350334978291d705749ca49cc8c7175df8.

```
$ cd $GOPATH/src/github.com/sylabs/singularity
$ ./mconfig -p /opt/singularity
$ cd ./builddir
$ make
$ sudo make install
$ /opt/singularity/bin/singularity -vd shell library://library/default/alpine
```

Still works.

This might be overkill but I then removed `$GOPATH/src/github.com/sylabs/singularity`, cloned the repo again and checked out a50b5b350334978291d705749ca49cc8c7175df8. Finally, I built and installed the RPM:

```
$ cd $GOPATH/src/github.com/sylabs
$ git clone https://github.com/sylabs/singularity.git
$ cd singularity
$ git checkout a50b5b350334978291d705749ca49cc8c7175df8
$ ./mconfig
$ make -C builddir rpm
$ sudo dnf install $HOME/rpmbuild/RPMS/x86_64/singularity-3.0.1-73.ga50b5b35.fc29.x86_64.rpm
$ /usr/bin/singularity -vd shell library://library/default/alpine
```

The version built from the RPM did not work and I get the same error as in the original message.

**Comment by jmstover** [comment] 2018-11-26 21:42
> The version built from the RPM did not work and I get the same error as in the original message.

Ehh? That... doesn't make sense. That commit is the same as what the master branch is pointing at. So, in theory `master` and the commit checkout *should* be identical. Do a `git describe` on both the `master` checkout, and the checkout of a50b5b35 ... :/

On the commit checkout, instead of doing `make -C builddir rpm` ... Lets try breaking that into two separate steps.

```
make -C builddir/ dist
rpmbuild -tb singularity-3.0.1.tar.gz
```

That _should_ be the same steps that the `rpm` target is doing... but _something_ isn't clicking here. Does the output from the following look close to what the PR diff is (should be identical)?

```
git diff a50b5b3~ a50b5b3
```

**Comment by jscook2345** [comment] 2018-11-27 04:36
@jameshclrk @cclerget 

I was able to reproduce this with my own Fedora 29 VM. It appears that when the RPM is created, the action shell scripts she-bang line is changed.

The RPM build sets them to `#!/usr/bin/sh` rather than `#!/bin/sh` and since on Alpine that first `sh` binary path does not exist, there is a 'no such file or directory' error.

I don't yet know why. I'm going to look over the `make rpm` log and see if that is useful.

**Comment by jscook2345** [comment] 2018-11-27 04:57
@jameshclrk @cclerget @jmstover 

Here is the section from the RPM log where things are being changed:

<pre>
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
mangling shebang in /usr/bin/run-singularity from /bin/sh to #!/usr/bin/sh
mangling shebang in /etc/singularity/actions/start from /bin/sh to #!/usr/bin/sh
mangling shebang in /etc/singularity/actions/run from /bin/sh to #!/usr/bin/sh
mangling shebang in /etc/singularity/actions/test from /bin/sh to #!/usr/bin/sh
mangling shebang in /etc/singularity/actions/shell from /bin/sh to #!/usr/bin/sh
mangling shebang in /etc/singularity/actions/exec from /bin/sh to #!/usr/bin/sh
</pre>

To fix this, we will need to either remove executable permissions from the action scripts until they are installed in the image or modify the spec file to exclude them.

See more info here including macros to change: https://fedoraproject.org/wiki/Packaging:Guidelines#Shebang_lines

**Comment by cclerget** [comment] 2018-11-27 10:15
@jscook2345 @jmstover A side effect of symlinking `/bin` -> `/usr/bin` in those RH derived distributions, a false good idea ...

**Closed as completed** 2018-11-30 04:37 UTC
Labels: Bug, Packaging
