### ISSUE TITLE
scary recipe that screws up computer

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#3632] opened 2019-05-27 14:55 UTC
## Version of Singularity:

3.1.0-rc2.1476.g1364a45b8

### Expected behavior

```
sudo singularity build uwsgi.sif Singularity
```
Container is built!

### Actual behavior

There is a quick stream of error messages about removing content in the temporary build folder, and then the entire computer doesn't seem to have bash, all of /dev is cleared, and nothing works (git, opening a terminal, etc.) I was able to use open terminals to start a shell and then reinstall bash and then a restart restored /dev. There are a lot of other "system internal errors" that have popped up and I've debugged manually (usually by reinstalling something).

### Steps to reproduce behavior

Build a recipe like this, if you dare...
```
Bootstrap: docker
From: python:3.5.1 

%setup
    mkdir -p "${SINGULARITY_ROOTFS}/code"
    cp -R . "${SINGULARITY_ROOTFS}/code/"

%environment
    PYTHONUNBUFFERED=1
    export PYTHONUNBUFFERED


%files
    requirements.txt /tmp/requirements.txt

################################################################################
# CORE

%post
    apt-get update && apt-get install -y \
       pkg-config \
        cmake \
        openssl \
        wget \
        git \
        vim

    pip install --upgrade pip
    pip install -r /tmp/requirements.txt

################################################################################
# Storage Locations

    mkdir -p /code/images && \
    mkdir -p /var/www/images && \
    chmod -R 0755 /code/images/ && \
    # Create hashed temporary upload locations
    mkdir -p /var/www/images/_upload/{0..9} && chmod 777 -R /var/www/images/_upload

################################################################################
# Clean Up

    apt-get autoremove -y && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# application runs on port 3031
%startscript
    cd /code
    exec /code/run_uwsgi.sh
```

**Comment by jscook2345** [comment] 2019-06-03 19:25
@vsoch What's in `/code/run_uwsgi.sh` ? Do you have a copy of the project I can pop in a VM and test this with? I'd at least need the correct `requirements.txt` assuming the problem is not in the `run_uwsgi.sh` script.

**Comment by vsoch** [comment] 2019-06-03 19:27
@jscook2345 it's got nothing to do with that, because when I remove the cleaning up of /tmp, etc (before we even get to adding a file) the machine gets screwed up. All the build does is copy the file to a spot in the container, so it's not logical that it has something to do with the file (which is never executed).

**Comment by vsoch** [comment] 2019-06-03 19:28
But if you want to see all the code, I won't disappoint! The recipe is a derivation of the Dockerfile here: https://github.com/singularityhub/sregistry I'm working on it for another project that I haven't put code online yet for.

**Comment by jscook2345** [comment] 2019-06-06 13:30
@vsoch 

@rherban mentioned that you and him hashed this out on Slack and that the issue was removing data in `tmp` directories. What do you think would be best here? To document that as a good practice or close the issue?

**Comment by vsoch** [comment] 2019-06-06 14:35
I think given that it's standard (and even suggested) practice in Docker (to make images smaller) I think the warning (in an alert colored section) should be written across docs that show a user how to build / write recipes. It's going to still happen, but at least new users that are introduced by way of reading the docs will get a heads up. We used to have a [best practices](http://singularity.lbl.gov/docs-docker#best-practices) section for building containers and recipes, and so if you've ported that to the new docs, it would also be a good place for it. If not, I'd say it would be a good addition.

**Comment by jscook2345** [comment] 2019-06-12 01:59
@vsoch @rherban 

So I see that `sbuild-*` shows up under `/tmp` when `%post` runs, so my guess is deleting that is causing the problem.

Cleaning up `/tmp` files seems like a logical thing to do to shrink your container (outside of a multi-stage build anyways). Perhaps this directory should live somewhere else?

**Comment by vsoch** [comment] 2019-06-12 02:10
I don’t think it’s limited to just that directory, because otherwise we wouldn’t have such terrible issues on the host after the build fails.  It must be related to other files in temp that are on the host outside of sbuild

**Comment by vsoch** [comment] 2019-06-12 02:11
I think we’re fairly decided that this is solved, and the next thing to do is decide how to warn users to not do a common practice of cleaning up, and carry through with said action.

**Comment by jscook2345** [comment] 2019-06-12 03:18
I opened a documentation bug for this. Thanks for the discussion!

**Closed as completed by jscook2345** 2019-06-12 03:18 UTC
Labels: ImageBuilding, NeedsInvestigation
