### ISSUE TITLE
Building rpm with rpmbuild on Fedora 29 produces non-working install

### ISSUE THREAD

**Issue by acdcfanbill** [apptainer/singularity#2357] opened 2018-11-10 00:46 UTC
## Version of Singularity:

3.0.1

### Expected behavior

Expected output from running container

### Actual behavior

FATAL:   exec /.singularity.d/actions/run failed: no such file or directory

### Steps to reproduce behavior

I used rpmbuild to build the singularity 3.0.1 on Fedora 29.  
`rpmbuild -tb singularity-3.0.1.tar.gz`
Then I installed the rpm.
`sudo rpm -i ~/rpmbiuld/RPMS/x86_64/singularity-3.0.1-1.fc29.x86_64.rpm`
Finally I run lolcow to test the install.
`singularity --debug run library://sylabsed/examples/lolcow`

If I build the rpm on CentOS7 and then install the rpm on Fedora 29, I get expected output from running singularity containers.

CentOS7 is using rpmbuild version 4.11.3
Fedora 29 is using rpmbuild version 4.14.2.1

**Comment by DrDaveD** [comment] 2018-11-12 20:35
I was able to reproduce this under docker command
```
docker run -it --rm --privileged fedora:29 bash
```

Here is the [debug output](https://github.com/sylabs/singularity/files/2573513/f29-singularity.debug.txt).

**Comment by DrDaveD** [comment] 2018-11-16 19:41
@cclerget can you take a look at this?  I believe you have solved similar issues.

**Comment by jscook2345** [comment] 2018-11-27 08:21
@DrDaveD @acdcfanbill @jmstover 

I believe this is a duplicate of #2383

**Comment by DrDaveD** [comment] 2018-11-28 22:40
Yeah and although this one came first there's more discussion over there so this one should probably be closed.

**Comment by jscook2345** [comment] 2018-11-30 17:07
Closing. See discussion of #2383 .

**Closed as completed by jscook2345** 2018-11-30 17:07 UTC
