### ISSUE TITLE
singularity (git version) bootstrapping CentOS-7 container from debian jessie or ubuntu trusty

### ISSUE THREAD

**Issue by truatpasteurdotfr** [apptainer/singularity#241] opened 2016-10-02 20:53 UTC
reported on #singularity irc channel and reproduced locally.

```
sudo singularity create a.img
sudo singularity bootstrap a.img ~/git/singularity/examples/centos.def
singularity exec a.img rpm -q centos-release
```

bootstrap fails during %post when yum install vim-minimal with:

```
+ yum -y install vim-minimal
Loaded plugins: fastestmirror


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/$releasever/x86_64
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=$releasever&arch=x86_64&repo=os&infra=stock error was
14: curl#56 - "Recv failure: Connection reset by peer"
ERROR: Aborting with RETVAL=255
package centos-release is not installed
```

imho /var/lib/rpm is not populated correctly, shell inside the container hosted on jessie/trusty verify that content of /var/lib/rpm is smaller than what I get from a centos-7 hosted host.

**Comment by vsoch** [comment] 2016-10-02 21:12
@gmkurtzer can comment on building from scratch, but I'd recommend just bootstrapping a docker image. Here is what I started with, first for centos.def

```
  Bootstrap: docker
  From: centos:latest
  IncludeCmd: yes
```

and then the commands:

```
  sudo singularity create centos.img
  sudo singularity bootstrap centos.img centos.def
```

then for any post install you can just add that in the post section, so the entire file should look like:

```
  Bootstrap: docker
  From: centos:latest
  IncludeCmd: yes

  %post

  yum install vim-minimal         
```

Give that a go, let me know how it goes! If you need a different version of centos, then check out the different tags here: https://hub.docker.com/_/centos/

**Comment by truatpasteurdotfr** [comment] 2016-10-02 21:35
something is not right on my jessie build? "./configure --prefix=/"

```
tru@jessie:~$ cat ./singularity-2.2-centos-docker.def
# docker bootstrap

Bootstrap: docker
From: centos:latest
IncludeCmd: yes

tru@jessie:~$ cat ./singularity-2.2-centos-docker.sh
#!/bin/sh
O=~/singularity-2.2-centos-docker.img
D=~/singularity-2.2-centos-docker.def
sudo rm -f $O
sudo singularity create $O
sudo singularity bootstrap $O  $D
sudo singularity exec $O rpm -q centos-release
tru@jessie:~$ ./singularity-2.2-centos-docker.sh
Creating a new image with a maximum size of 768MiB...
Executing image create helper
Formatting image with ext3 file system
Done.
Bootstrap initialization
Checking bootstrap definition
Executing Prebootstrap module
Executing Setup module
Executing Bootstrap 'docker' module
From: centos:latest
IncludeCmd: yes
library/centos:latest
Traceback (most recent call last):
  File "//libexec/singularity/python/cli.py", line 198, in <module>
    main()
  File "//libexec/singularity/python/cli.py", line 146, in main
    auth=doauth)
  File "/libexec/singularity/python/docker/api.py", line 154, in get_manifest
    permission="pull")
  File "/libexec/singularity/python/docker/api.py", line 63, in get_token
    response = api_get(base,default_header=False)
  File "/libexec/singularity/python/utils.py", line 140, in api_get
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 104] Connection reset by peer>
Executing Postbootstrap module
ERROR: Container does not contain the valid minimum requirement of /bin/sh
WARNING: Bind file destination does not exist in container: /var/singularity/mnt/final/etc/resolv.conf
WARNING: Non existant bind point (file) in container: '/etc/hosts'
WARNING: Not mounting /proc, container has no bind directory
WARNING: Not mounting /sys, container has no bind directory
WARNING: Not mounting home directory: bind point does not exist in container: /root
WARNING: Could not obtain pwinfo for uid: 0
ERROR  : Failed to execvp() /.exec: No such file or directory
ABORT  : Retval = 255
tru@jessie:~$ 
```

**Comment by vsoch** [comment] 2016-10-02 21:38
could you show me the contents of your libexec/python folder?

**Comment by gmkurtzer** [comment] 2016-10-03 02:56
2 things,... We need to properly catch the python error and ABORT and I think the first issue referenced is due to incompatible RPM DBs based on the version of the DB installed by the rpmlib on the host versus the rpmlib inside the container. Aside from exporting and importing the database, I don't think it is fixable.

**Comment by truatpasteurdotfr** [comment] 2016-10-03 06:32
```
tru@jessie:~$ ls -l /libexec/singularity/python
total 28
-rwxr-xr-x 1 root root 6922 Oct  2 23:30 cli.py
drwxr-xr-x 2 root root 4096 Oct  2 23:31 docker
-rwxr-xr-x 1 root root    0 Oct  2 23:30 __init__.py
-rwxr-xr-x 1 root root 7999 Oct  2 23:30 utils.py
-rw-r--r-- 1 root root 7478 Oct  2 23:31 utils.pyc
```

**Comment by truatpasteurdotfr** [comment] 2016-10-03 06:36
centos7 container hosted on centos7:

```
Singularity.centos-local-http.img> rpm -qa \*rpm\*
rpm-libs-4.11.3-17.el7.x86_64
rpm-build-libs-4.11.3-17.el7.x86_64
rpm-4.11.3-17.el7.x86_64
rpm-python-4.11.3-17.el7.x86_64
```

my centos7 host:

```
[tru@hpe840g1-1 singularity-img]$ rpm -qa \*rpm\*
redhat-rpm-config-9.1.0-68.el7.centos.noarch
rpm-build-libs-4.11.3-17.el7.x86_64
rpm-4.11.3-17.el7.x86_64
rpm-devel-4.11.3-17.el7.x86_64
python-deltarpm-3.6-3.el7.x86_64
rpm-python-4.11.3-17.el7.x86_64
rpm-sign-4.11.3-17.el7.x86_64
rpm-libs-4.11.3-17.el7.x86_64
pcp-pmda-rpm-3.10.6-2.el7.x86_64
perl-srpm-macros-1-8.el7.noarch
deltarpm-3.6-3.el7.x86_64
rpm-build-4.11.3-17.el7.x86_64
```

jessie (host of failed container bootstrap from scratch):

```
tru@jessie:~$ dpkg -l|grep rpm
ii  librpm3                        4.11.3-1.1                  amd64        RPM shared library
ii  librpmbuild3                   4.11.3-1.1                  amd64        RPM build shared library
ii  librpmio3                      4.11.3-1.1                  amd64        RPM IO shared library
ii  librpmsign1                    4.11.3-1.1                  amd64        RPM signing shared library
ii  python-rpm                     4.11.3-1.1                  amd64        Python bindings for RPM
ii  rpm                            4.11.3-1.1                  amd64        package manager for RPM
ii  rpm-common                     4.11.3-1.1                  amd64        common files for RPM
ii  rpm2cpio                       4.11.3-1.1                  amd64        tool to convert RPM package to CPIO archive
ii  yum                            3.4.3-3                     all          Advanced front-end for rpm
```

**Comment by gmkurtzer** [comment] 2016-10-04 00:50
/me shrugs... Maybe a different version of bdb that RPM got linked to?

**Comment by truatpasteurdotfr** [comment] 2016-10-04 08:52
CentOS-7:

```
$ rpm -qa libdb\*
libdb-utils-5.3.21-19.el7.x86_64
libdb-5.3.21-19.el7.x86_64
libdb-devel-5.3.21-19.el7.x86_64
libdb-5.3.21-19.el7.i686
```

jessie:

```
ii  libdb5.3:amd64 5.3.28-9     amd64        Berkeley v5.3 Database Libraries 
```

trusty:

```
ii  libdb5.3:amd64 5.3.28-3ubun amd64        Berkeley v5.3 Database Libraries 
```

**Comment by gmkurtzer** [comment] 2016-10-04 14:15
Can you build a chroot from scratch using YUM and make it work? I'm still somewhat convinced this is not a Singularity issue as opposed to a RPM DB mismatch somehow. I've seen similar creating a C6 image from C7 host. When you shell into the image you can not run RPM commands within the host. 

Have you tried running RPM commands from outside the container? Mount up the image and use the --root RPM command to see if that works. 

Greg

**Comment by truatpasteurdotfr** [comment] 2016-10-04 15:52
I confirme your suspected rpm compatibility issues: bootstrapping (from scratch) a Centos6 container from a CentOS-7 host yields an non working one :(

```
BootStrap: redhat
OSVersion: 6
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum
%runscript
    echo "This is what happens when you run the container..."
%post
    echo "Hello from inside the container"
        rpm -q centos-release
```

error:

```
Executing Postbootstrap module
+ echo 'Hello from inside the container'
Hello from inside the container
+ rpm -q centos-release
rpmdb: /var/lib/rpm/Name: unexpected file type or format
error: cannot open Name index using db3 - Invalid argument (22)
rpmdb: /var/lib/rpm/Name: unexpected file type or format
package centos-release is not installed
ERROR: Aborting with RETVAL=255
```

**Comment by truatpasteurdotfr** [comment] 2016-10-04 15:55
After mounting the container:

```
[tru@hpe840g1-1 singularity.d]$ sudo singularity mount ~/singularity-img/singularity-2.2-centos6.img 
...
/home/tru/singularity-img/singularity-2.2-centos6.img:/var/singularity/mnt/final> rpm -qa --root=/var/singularity/mnt/final
error: db5 error(-30969) from dbenv->open: BDB0091 DB_VERSION_MISMATCH: Database environment version mismatch
error: cannot open Packages index using db5 -  (-30969)
error: cannot open Packages database in /var/singularity/mnt/final/var/lib/rpm
error: db5 error(-30969) from dbenv->open: BDB0091 DB_VERSION_MISMATCH: Database environment version mismatch
error: cannot open Packages database in /var/singularity/mnt/final/var/lib/rpm
```

**Comment by truatpasteurdotfr** [comment] 2016-10-04 15:57
Bottom line, imho, boostrap from scratch only works fine when RHEL's clone versions are the same on host and container, or you can bootstrap from a docker image/tarball to work around the bootstrap from scratch issue cause by rpm, ymmv.

**Comment by bbockelm** [comment] 2016-10-04 16:18
Oh!  I've seen this error before.

It's something to do with the fact that overlayfs is non-POSIX and RPM expects POSIX-like behavior.

Here's a relevant-looking conversation:
https://bugzilla.redhat.com/show_bug.cgi?id=1213602

(there are a few others).  Seems that you can workaround this by doing the following:

```
touch /var/lib/rpm/*
```

**Comment by gmkurtzer** [comment] 2016-10-04 16:23
@bbockelm: Yeah, this is an old RPM DB compatibility issue with bootstrapping. There are some shortcuts that sometimes work: `touch /var/lib/rpm/*` and `rm /var/lib/rpm/_*`, but if the BDB format itself is non-compatible (e.g. creating an RPM DB with a newer version of BDB then what is in the chroot/container) then it is a harder problem to solve. It usually involves exporting and re-importing the database.

@truatpasteurdotfr: I don't think this can be fixed within Singularity unless we can come up with a method to reliably script the export/import of the BDB after bootstrap of the core OS. Thoughts?

**Comment by truatpasteurdotfr** [comment] 2016-10-04 17:26
followup: this recipe works on c7 host to bootstrap a c6 container:

```

BootStrap: redhat
OSVersion: 6
MirrorURL: http://mirror.centos.org/centos-%{OSVERSION}/%{OSVERSION}/os/$basearch/
Include: yum
%post
    echo "Hello from inside the container"
    rm -rf /var/lib/rpm/__*
    touch /var/lib/rpm/* 
    rpm --rebuilddb
    rpm -qa
    yum -y install vim-minimal
```

but it fails to bootstrap a CentOS-5 container on the same CentOS-7 host:

```
Executing Postbootstrap module
+ echo 'Hello from inside the container'
Hello from inside the container
+ rm -rf '/var/lib/rpm/__*'
+ touch /var/lib/rpm/Basenames /var/lib/rpm/Conflictname /var/lib/rpm/Dirnames /var/lib/rpm/Group /var/lib/rpm/Installtid /var/lib/rpm/Name /var/lib/rpm/Obsoletename /var/lib/rpm/Packages /var/lib/rpm/Providename /var/lib/rpm/Requirename /var/lib/rpm/Sha1header /var/lib/rpm/Sigmd5 /var/lib/rpm/Triggername
+ rpm --rebuilddb
rpmdb: /var/lib/rpm/Packages: unsupported hash version: 9
error: cannot open Packages index using db3 - Invalid argument (22)
ERROR: Aborting with RETVAL=255
```

**Comment by gmkurtzer** [comment] 2016-10-04 17:44
We can include the removing of the DB lock files (/var/lib/rpm/__*), touch, and rebuilding of the DB in the redhat module, but the truly portable fix is to dump the DB's and re-import.

Have you played with yumbootstrap (https://github.com/dozzie/yumbootstrap)?

**Comment by truatpasteurdotfr** [comment] 2016-10-04 17:45
trying the same trick on jessie host/c7 container yields:

```
Executing Postbootstrap module
+ echo 'Hello from inside the container'
Hello from inside the container
+ rm -rf '/var/lib/rpm/__*'
+ touch '/var/lib/rpm/*'
+ ls /var/lib/rpm/
*
+ rpm --rebuilddb
+ rpm -q centos-release
warning: Generating 12 missing index(es), please wait...
package centos-release is not installed
ERROR: Aborting with RETVAL=255
package centos-release is not installed

tru@jessie:~$ sudo singularity shell -w singularity-2.2-centos-local-http.img Singularity: Invoking an interactive shell within container...

Singularity.singularity-2.2-centos-local-http.img> ls  /var/lib/rpm
*         __db.001  Dirnames    Name      Providename  Sigmd5
Basenames     __db.002  Group       Obsoletename  Requirename  Triggername
Conflictname  __db.003  Installtid  Packages      Sha1header
Singularity.singularity-2.2-centos-local-http.img> ls -l /var/lib/rpm
total 404
-rw-r--r-- 1 root root      0 Oct  4 17:32 *
-rw-r--r-- 1 root root   8192 Oct  4 17:32 Basenames
-rw-r--r-- 1 root root   8192 Oct  4 17:32 Conflictname
-rw-r--r-- 1 root root 270336 Oct  4 17:32 __db.001
-rw-r--r-- 1 root root  81920 Oct  4 17:32 __db.002
-rw-r--r-- 1 root root 107048 Oct  4 17:32 __db.003
-rw-r--r-- 1 root root   8192 Oct  4 17:32 Dirnames
-rw-r--r-- 1 root root   8192 Oct  4 17:32 Group
-rw-r--r-- 1 root root   8192 Oct  4 17:32 Installtid
-rw-r--r-- 1 root root   8192 Oct  4 17:32 Name
-rw-r--r-- 1 root root   8192 Oct  4 17:32 Obsoletename
-rw-r--r-- 1 root root  12288 Oct  4 17:32 Packages
-rw-r--r-- 1 root root   8192 Oct  4 17:32 Providename
-rw-r--r-- 1 root root   8192 Oct  4 17:32 Requirename
-rw-r--r-- 1 root root   8192 Oct  4 17:32 Sha1header
-rw-r--r-- 1 root root   8192 Oct  4 17:32 Sigmd5
-rw-r--r-- 1 root root   8192 Oct  4 17:32 Triggername

```

as if /var/lib/rpm was not fully populated when the %post was run.

**Comment by akkornel** [comment] 2017-03-22 22:37
Hello!

I was planning on making a new issue for this, but then @vsoch pointed me here!  I'm also experiencing the same issue: If a Yum-based system is bootstrapped from a Debian-family OS (Debian, Ubuntu, etc.), then the RPM database doesn't appear in the right place.

I'm working with a Singularity built from Git commit 17cad8a682368e1035b341ef4cce3edc81d07947, but I've also seen this issue on Singularity 2.2.1.  The only option I'm passing to `./configure` is a custom `--prefix`.

Here's an example bootstrap file that exposes this problem:

```BootStrap: yum
OSVersion: 7
MirrorURL: http://yum.stanford.edu/mrepo/centos%{OSVERSION}-x86_64/RPMS.all/
Include: perl

%setup
	curl -o ${SINGULARITY_ROOTFS}/tmp/epel-release.rpm 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
	curl -o ${SINGULARITY_ROOTFS}/tmp/epel-release.gpg 'https://getfedora.org/static/352C64E5.txt'

%post
	rm /var/lib/rpm/__*
	touch /var/lib/rpm/*
	rpm --rebuilddb
	rpm --import /tmp/epel-release.gpg
	rpm --install /tmp/epel-release.rpm
	rm /tmp/epel-release.gpg /tmp/epel-release.rpm
	yum install perl-Email-Simple
```

And here's a asciinema that shows what happens when you bootstrap the above using Singularity commit 17cad8a682368e1035b341ef4cce3edc81d07947 on Ubuntu 16.10:

https://asciinema.org/a/88rnb31zl6qjtb7xrvyi6jyeb

It took almost a day of hunting around, but I found the issue.  The problem is that Debian (and therefore Ubuntu) have intentionally changed the `_dbpath` RPM setting, which tells RPM where the database files live.

Here's what `rpm --showrc | grep -E ":\s_dbpath\s" | cut -f2` returns on stock CentOS and Fedora:

- CentOS 6: `%{_var}/lib/rpm` (and `%{_var}` resolves to `/var`)
- CentOS 7: Same as CentOS 6
- Fedora 25: Same as CentOS 6

And if you first run `apt-get -y install rpm`, here's what `rpm --showrc | grep -E ":\s_dbpath\s" | cut -f2` returns on stock Debian and Ubuntu:

- Debian 7: `%(echo $HOME/.rpmdb)`
- Debian 8: `%(bash -c 'echo ~/.rpmdb')`
- Ubuntu 14.04: Same as Debian 7
- Ubuntu 16.04: Same as Debian 8
- Ubuntu 16.10: Same as Debian 8

(It's worth noting that I checked for the `_var` RPM variable in Ubuntu 14.04 and 16.10; it is defined, and set to `/var`.  On Ubuntu 16.04, `_var` is not defined.)

(props to [dply.co](https://dply.co) for letting me spin up things quickly for testing!)

The above asciinema recording confirms, `yum` dumped the RPM database files into a sub-directory of my home directory, _in the container_.  My actual home directory isn't being touched, because Singularity is using the `--installroot` option for `yum`.

Here is the original Debian bug for the change: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=551669#34
And here is an RPM project bug pointing back to the Debian bug, when people started wondering why they had weird `.rpmdb` directories appearing everywhere: https://bugs.launchpad.net/rpm/+bug/1069350

**Comment by vsoch** [comment] 2017-03-22 23:01
Thanks @akkornel ! I'm going to close the other issue so it can be represented here without confusion.

**Comment by akkornel** [comment] 2017-03-22 23:19
Thanks @vsoch!

The commit referenced above adds a check to the yum bootstrap script, catching this issue, and asking the user to create an `.rpmmacros` file that fixes the problem.  Here's what happens if I try the bootstrap again, using the same bootstrap script from [my comment above](https://github.com/singularityware/singularity/issues/241#issuecomment-288561589):

https://asciinema.org/a/59dbj39cxwnymlrk5haj9yujj

We're close!  It seems like Ubuntu's `yum` did not create the BerkeleyDB files that are causing the problem, so my bootstrap still failed, but the source files are there.

Let's try a slightly-modified bootstrap:

```BootStrap: yum
OSVersion: 7
MirrorURL: http://yum.stanford.edu/mrepo/centos%{OSVERSION}-x86_64/RPMS.all/
Include: perl rpm yum

%setup
	curl -o ${SINGULARITY_ROOTFS}/tmp/epel-release.rpm 'https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm'
	curl -o ${SINGULARITY_ROOTFS}/tmp/epel-release.gpg 'https://getfedora.org/static/352C64E5.txt'

%post
	[ -f /var/lib/rpm/__* ] && rm /var/lib/rpm/__*
	touch /var/lib/rpm/*
	rpm --rebuilddb
	rpm --import /tmp/epel-release.gpg
	rpm --install /tmp/epel-release.rpm
	rm /tmp/epel-release.gpg /tmp/epel-release.rpm
	yum install --assumeyes perl-Email-Simple
```

Here's what happens:

https://asciinema.org/a/44nbnrktxxn5r6sglnmn3ndx4

That looks *much* better!  `rpm` still wants to write to the BerkeleyDB files every time it runs (which was the source of the Debian complaints), but at least the database is intact.

For reference, I was using an Ubuntu 16.10 host.

Please let me know if you'd like me to make any changes to the patch, or initiate a pull request, or if you have any comments/questions.  Thanks!

**Comment by vsoch** [comment] 2017-03-22 23:56
If you would like to contribute you are always free to open a PR and it will be reviewed! When you open a PR, if it fixes or closes an issue you can reference itand when mergedwill automatically close. Thanks!

**Comment by gmkurtzer** [comment] 2017-03-25 01:30
The PR has been merged. Can this be closed?

Thanks!

**Comment by vsoch** [comment] 2017-03-25 01:40
done!

**Comment by vsoch** [comment] 2017-03-25 01:41
@akkornel in the future, when you do a PR you can write "This will fix/close #2222 (where 2222 is the number of the issue) and it willclose automatically. You can do this with commits too! Thanks for your contribution!

**Closed as completed by vsoch** 2017-03-25 01:40 UTC

**Comment by akkornel** [comment] 2017-03-25 20:51
@vsoch Hmmmmm, that's weird, because here's what I had in my original pull request text:

>Fixes #241

(That's the default text from https://github.com/singularityware/singularity/blob/master/.github/PULL_REQUEST_TEMPLATE)

I wonder, is `development` marked as the default branch for this repo?  According to https://github.com/blog/1506-closing-issues-via-pull-requests…

>…the referenced issue will automatically be closed when the PR is merged
into the default branch.

Maybe that's why it didn't auto-close?

**Comment by vsoch** [comment] 2017-03-25 21:00
ah right, that's it! In that case, we are just impatient about closing issues (@gmkurtzer has been on a rampage these last few days, lol)

**Comment by gmkurtzer** [comment] 2017-03-26 16:42
Yep, issue closing rampages! Trying to get everything lined up and prepared for the 2.3 release. :)

**Comment by bafonso** [comment] 2018-02-22 13:15
I was able to bootstrap a base scientific linux 6 on ubuntu but any subsequent call to yum fails, whether in post or interactive shell.

`Singularity dev.simg:~> yum install vim-minimal
/var/lib/rpm/Name: unexpected file type or format
error: cannot open Name index using db3 - Invalid argument (22)
/var/lib/rpm/Providename: unexpected file type or format
error: cannot open Providename index using db3 - Invalid argument (22)
You need to be root to perform this command.`

**Comment by bafonso** [comment] 2018-02-22 13:44
I was able to install the sc6 using the @truatpasteurdotfr recipe but if I try to use yum in the shell I get:

`[root@localhost singularity-vm]# singularity shell dev.simg 
Singularity: Invoking an interactive shell within container...

Singularity dev.simg:~> yum grouplist
Cannot open logfile /var/log/yum.log
Could not create lock at /var/run/yum.pid: [Errno 30] Read-only file system: '/var/run/yum.pid' 
Another app is currently holding the yum lock; waiting for it to exit...
  The other application is: yum
    Memory :  20 M RSS (306 MB VSZ)
    Started: Thu Feb 22 08:41:39 2018 - 00:01 ago
    State  : Running, pid: 25688
`

For the time being should I try to get my stuff compiled on ubuntu based solutions?
