### ISSUE TITLE
plugin install --name does not work

### ISSUE THREAD

**Issue by jscook2345** [apptainer/singularity#3453] opened 2019-04-30 00:16 UTC
## Version of Singularity:
3.2.0rc2

```
$ sudo singularity plugin install --name TP examples/plugins/test-plugin/test-plugin.sif
$ singularity plugin list
ENABLED  NAME
    yes  sylabs.io/test-plugin
```

I would expect the name to be something like `TP`.

**Comment by tri-adam** [comment] 2019-10-18 23:11
Stumbled across this while reviewing #4642. I believe #4639 is a duplicate of this, which is my bad. I'll mark this as being closed by #4642 so they're both closed when that is merged.

**Closed as completed** 2019-10-19 09:55 UTC
Labels: Bug, Release 3.3.0, Plugin
