### ISSUE TITLE
arch definition needs to be updated?

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#454] opened 2017-01-15 19:04 UTC
I got a segmentation fault when I tried bootstrapping [this guy](https://github.com/singularityware/singularity/blob/master/examples/arch.def)

**Comment by gmkurtzer** [comment] 2017-03-26 02:11
@czka ping?

**Comment by czka** [comment] 2017-03-26 07:00
@gmkurtzer

I told you you broke the arch.def, long time ago, in https://github.com/singularityware/singularity/issues/261. You closed that ticket recently. Please re-open, fix and all should be OK.

**Comment by vsoch** [comment] 2017-03-26 07:34
Sorry that your fixes got dropped! @gmkurtzer is pretty terrible with Github, but give him a chance he is getting better, haha. I don't know anything about arch, but I can help try to resolve this. Here is how far I got - I had to create an archlinux docker image with Singularity to start debugging. Here is steps for that:

```bash
docker run -it --privileged pritunl/archlinux bash
pacman -S -y git autoconf libtool automake gcc python make sudo vim
git clone https://github.com/singularityware/singularity
cd singularity
git checkout -b development
git pull origin development
./autogen.sh
./configure --prefix=/usr/local

pacman -S arch-install-scripts
pacman -S arch-install-scripts wget
singularity create arch.img
sudo singularity bootstrap arch.img arch.def
```

Then here is a start for a bootstrap arch spec:

```bash
Bootstrap: arch
%setup

ln -s /usr/share/zoneinfo/UTC /etc/localtime
echo 'en_US.UTF-8 UTF-8' > "$SINGULARITY_ROOTFS"/etc/locale.gen
echo 'pl_PL.UTF-8 UTF-8' >> "$SINGULARITY_ROOTFS"/etc/locale.gen
locale-gen
echo 'LANG=en_US.UTF-8' > "$SINGULARITY_ROOTFS"/etc/locale.conf
echo 'Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch' > "$SINGULARITY_ROOTFS"/etc/pacman.d/mirrorlist
echo 'Server = https://archlinux.honkgong.info/$repo/os/$arch' >> "$SINGULARITY_ROOTFS"/etc/pacman.d/mirrorlist

%post
pacman install -y vim bash-completion
paccache -r -k0
```

and the bug I hit is:

```bash
sudo singularity bootstrap arch.img arch.def 
Building from bootstrap definition recipe
Adding label: 'SINGULARITY_CONTAINER_UUID' = 'e6964dbb-318d-494b-8524-496e2bad53b1'
Adding label: 'SINGULARITY_DEFFILE' = 'arch.def'
Adding label: 'SINGULARITY_BOOTSTRAP_VERSION' = '2.2.99'
Adding label: 'SINGULARITY_DEFFILE_BOOTSTRAP' = 'arch'
Adding base Singularity environment to container
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
2017-03-26 07:29:49 URL:https://git.archlinux.org/svntogit/packages.git/plain/trunk/pacman.conf.x86_64?h=packages/pacman [2898/2898] -> "/tmp/pacman.conf.22071" [1]
==> Creating install root at /var/lib/singularity/mnt/source
mount: mount point /var/lib/singularity/mnt/source/dev/shm is a symbolic link to nowhere
==> ERROR: failed to setup chroot /var/lib/singularity/mnt/source
ERROR: `/usr/sbin/pacstrap' failed.
ERROR: Aborting with RETVAL=255
```

@gmkurtzer one note - I noticed that the bootstrap spec can't handle comments in the form of `#` - this probably is a bug? Any ideas on the symbolic link to nowhere? (the twighlight zone? lol)

**Comment by vsoch** [comment] 2017-03-26 07:36
And did I infer correctly that arch linux bootstrap must have archlinux host? when i type pacman on my ubuntu I get:

![image](https://cloud.githubusercontent.com/assets/814322/24329446/2d30c77e-11bc-11e7-8a3f-ee4a9fe7c30e.png)

pretty fabulous, if you ask me :) :space_invader:

**Comment by vsoch** [comment] 2017-03-26 07:45
or we could just skip over all this and use layers that are already done :)

     singularity shell docker://pritunl/archlinux

and put that into a Bootstrap, you can install and do additional stuffs,

    Bootstrap: docker
    From: pritunl/archlinux
 
or just run with sudo and `--writable` to make changes... 

     sudo singularity shell --writable docker://pritunl/archlinux

this seems like an easier solution than trying to install singularity in a docker arch image, and then going through the headache of installing dependencies, etc. Many ways to skin a cat, I suppose!

**Comment by czka** [comment] 2017-03-26 12:39
Just get gmkurtzer to revert his commits that broke arch.def. It was pretty much fine as it was before then. If he wanted to add/fix something along with his changes that broke the file, it's up to him to decide about that. In the end - let him do it. I don't read minds, and I don't think you do, either.

**Comment by vsoch** [comment] 2017-03-26 12:52
Yes, I am quite terrible at that :_)

@gmkurtzer let me know if we've broken anything in the `arch.def` with some of the new changes, and I'd be happy to test things out! From the little testing I did, it seems like we might have a problem with comments? Is the format with Bootstrap, Setup, still "best practices" (good to know while I'm writing these new docs, lol). I'm happy to do the testing needed to get @czka contribution back into it's previously working state.

Thanks again @czka, apologies for the merge conflicts that messed up your work!

**Comment by gmkurtzer** [comment] 2017-03-26 19:50
Hi @czka,

I believe I fixed the merging errors a long time ago as well (here is the one for the arch.def fixup: https://github.com/singularityware/singularity/commit/d5ebe2b11f80e54cec23fa009f0631fd33a1804a). If I missed others, please point me to them, and I will resolve.

Considering we are not getting a segmentation fault on any of the other bootstrap code (that we have seen), having your insight on Arch would be helpful (thus the ping).

If you can take a look at the 'development' branch and let us know what you find, that would be fantastic.

Thanks,
Greg

**Comment by gmkurtzer** [comment] 2017-03-26 20:05
@czka On a quick look, it appears that the arch.def is the boostrap format v1 which will be obsoleted by 2.3 (2.2 supported both). Additionally, @vsoch was trying to update it for the v2 format, but was having some problems. Neither her nor I are experts in Arch Linux and will require assistance.

I am shooting to lock the code in about a week (beginning of April) and prepare for the release. If you can lend a hand for the Arch support before then, it would be much appreciated.

Thank you!

**Comment by czka** [comment] 2017-03-26 20:48
@gmkurtzer 

I did provide the arch.def in the new format, in September - here: https://github.com/czka/singularity/blob/master/examples/arch.def.

I did issue a pull request for that - https://github.com/singularityware/singularity/pull/208. And you merged it. Cool.

arch.def was still OK on master as of https://github.com/singularityware/singularity/blob/60ae951ae97cb8e2095db5246d42d15c00c37009/examples/arch.def.

Then you introduced errors into it, in https://github.com/singularityware/singularity/blob/44e24affad2a039ae27b2350fb6c2912fe83dbd8/examples/arch.def.

I have already tried to explain this to you back in https://github.com/singularityware/singularity/issues/261.

https://github.com/singularityware/singularity/blob/d5ebe2b11f80e54cec23fa009f0631fd33a1804a/examples/arch.def did not fix anything. You merely removed the 2 lines that indicated the merge error.

**No any expertise in Arch Linux is required. Just please review the history of changes in arch.def (https://github.com/singularityware/singularity/commits/master/examples/arch.def), identify your errors, fix them and it will be fine again.**

Given the merge error you introduced, I'd assume you might have intended some changes into arch.def that I'm not aware of. I can't guess what you wanted to achieve at that point and I haven't been following Singularity development since my last commits in September, so I'm in no position to fix that for you.

**Comment by vsoch** [comment] 2017-03-26 22:28
I got this working, and I'll add to the development branch. Thanks everyone!

**Comment by gmkurtzer** [comment] 2017-03-26 23:03
@vsoch Fantastic, thank you!

@czka It will take a bit more time then I have now to figure out what happened, but I would guess it happened due to a dead end master branch that we incurred due to migration from a CVS style development style to GitFlow (e.g. master is latest stable, and not trunk). In either case, as long as the right bits are committed somewhere, I/we will do our best to maintain it as the code base changes and matures. With that said, without a committed Arch Linux maintainer, I can not guarantee support for features that I can not test (thus it will be released broken or removed).

Thanks!

**Comment by czka** [comment] 2017-06-04 16:01
@vsoch 
Arch example is still broken, both on [master](https://github.com/singularityware/singularity/blob/master/examples/arch/Singularity) and the latest [2.3 release](https://github.com/singularityware/singularity/blob/2.3/examples/arch/Singularity). Still a mix of the old and the new format, which originates from @gmkurtzer merge error months ago, as explained above. This ticket should be re-opened.

I will fix this and update it for the current Arch Linux install process. Next weekend or the following, maybe. Just please promise you won't break my balls again ;).

**Comment by vsoch** [comment] 2017-06-04 16:13
will (or won't :P) do! Reopening issue.

**Comment by gmkurtzer** [comment] 2017-06-04 16:15
@czka I can not promise that I, or anyone else, won't break pieces of this code with updates or reorganizations, that is why we need help to move forward! But it won't happen intentionally.

Again, I think the cause of much of this was that you had it fixed in the 'master' branch, but the master branch was an unfortunate dead end. It is fixed now, but nobody should be submitting PR's against master anyway.

Thanks and I look forward to having this fixed!

**Comment by czka** [comment] 2017-06-04 16:47
@gmkurtzer No, it was just a merge error on your side. I explained it twice at least. Sure I don't think it was intentional. But I expected you would finally fix it. That did not happen. Too bad.

**Comment by gmkurtzer** [comment] 2017-06-04 17:55
It does not help to continuously blame me for a merging error, what does help is a PR. Since your last commit (8'ish months ago), we have had significant changes to the underlying bootstrap architecture, and neither @vsoch nor myself have the means or necessity to test or debug running Arch Linux on the host side, so until we get help, it will remain untested and broken.

**Comment by czka** [comment] 2017-06-04 18:23
I'm not blaming but stating a fact. Please don't take it personal, don't skew the facts and please don't lecture me. That's not encouraging.

**Comment by gmkurtzer** [comment] 2017-06-05 03:02
The deffile has been updated to what you have current in your branch. Sorry this got missed and thanks for the pointer.

As I've stated, I can't test any other aspects of the Arch bootstrap code because I'm not running Arch, and `pacstrap` is not packaged for Debian/Ubuntu. Please test and if you find that anything else is broken, open a new issue or better yet, submit a PR.

And since I don't like being accused of skewing facts, your last commit to this project was 8 months, 22 days ago and as I mentioned, the underlying bootstrap code has changed considerably since then.

**Closed as completed by gmkurtzer** 2017-06-05 03:02 UTC

**Comment by czka** [comment] 2017-06-06 11:28
> As I've stated, I can't test any other aspects of the Arch bootstrap

I didn't ask for that. This is is moot in the context here.

> And since I don't like being accused of skewing facts

Facts:
- In my PRs I provided everything needed for both the legacy and the actual Arch bootstrap setup as of few months ago.  
- You merged my PRs. All was fine.
- You made some other merges on your own to the files I provided, not initiated by me, which broke the Arch bootstrap setup.
- For the following few months you did not acknowledge and did not fix your merge error even though I described it in detail twice at least.
- You (and/or vsoch) claimed it was fixed, when it wasn't, and closed the related tickets. 

The latter 2 points are the skew I referred to. Please accept that I'm not accusing, but stating facts.

> your last commit to this project was 8 months, 22 days ago

I can read Git log alright ;).
