### ISSUE TITLE
singularity shell/exec fails when $PWD contains path component with symlink

### ISSUE THREAD

**Issue by mgjf** [apptainer/singularity#4869] opened 2019-12-17 12:08 UTC
### Version of Singularity:
```
 $ singularity version
3.5.1
```
### Expected behavior

Assume that we have a container image `ubu.sif` in a directory `/scratch/myuser/sub` that was reached via a symlink `/home/myuser/Scratch -> /scratch/myuser` such that `$PWD=/home/myuser/Scratch/sub`.

When we run a container shell or command (e.g. `singularity exec ubu.sif ls -l`) in this subdirectory we expect the container to perform its intended action, e.g. the output of the ls command
```
total 25284
-rwxr-xr-x 1 myuser myuser 25890816 Dec 17 10:35 ubu.sif
```

### Actual behavior

The command fails with
```
FATAL:   container creation failed: hook function for tag sessiondir returns error: failed to read symlink /home/myuser/Scratch/sub: readlink /home/myuser/Scratch/sub: invalid argument
```

After resolving the symlink with `cd $(/bin/pwd)`, which eliminates all symlink components from `$PWD`, the command runs fine (workaround - however, I'd prefer not having to teach this to our users).

The problem does not exist in Singularity 3.4.2.

### Steps to reproduce this behavior

Do the following with an unmodified Singularity 3.5.1 installation (tested on a new Ubuntu 18.04.3 server installation and on our production CentOS 7 system)
```
cd $HOME
sudo mkdir -p /scratch/myuser
sudo chown $USER /scratch/myuser
mkdir /scratch/myuser/sub
ln -s /scratch/myuser Scratch
cd Scratch/sub
singularity --version
singularity build ubu.sif docker://ubuntu
echo $PWD
singularity exec ubu.sif ls -l
#### Output: error message ####
cd $(/bin/pwd)
echo $PWD
singularity exec ubu.sif ls -l
#### Expected output ####
```

### What OS/distro are you running

Test machine
```
myuser@ubuntu18043server:/scratch/myuser/sub$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
Production machine
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Singularity

On the test system (fresh Ubuntu 18.04.3 server installation), as described in [https://sylabs.io/guides/3.5/user-guide/quick_start.html](https://sylabs.io/guides/3.5/user-guide/quick_start.html), substituting `VERSION=3.5.1`.

**Comment by cclerget** [comment] 2019-12-17 14:07
Hi @mgjf , I'm closing the issue as a duplicate of #4836 and was fixed by #4838. You can pull latest changes from branch `release-3.5` or wait a bit for 3.5.2 which should be out today.

**Closed as completed by cclerget** 2019-12-17 14:08 UTC

**Comment by mgjf** [comment] 2019-12-17 14:49
Thanks - great!

**Comment by cousins** [comment] 2019-12-19 21:15
I'm seeing this same issue with  #4871 . For example my /home : 

```
[cousins@viz3 user-tests]$ ls -al /home/ |grep cousins
lrwxrwxrwx 1 root   root         18 Dec 11  2017 cousins -> /nfs5-home/cousins

[cousins@viz3 user-tests]$ pwd
/home/cousins/user-tests

[cousins@viz3 user-tests]$ singularity exec test.simg ls /
FATAL:   container creation failed: hook function for tag sessiondir returns error: failed to read symlink /home/cousins/user-tests: readlink /home/cousins/user-tests: invalid argument

[cousins@viz3 user-tests]$ cd /nfs5-home/cousins/user-tests/

[cousins@viz3 user-tests]$ singularity exec test.simg ls /
bin   dev	   etc	 lib	media  nfs5-home  proc	run   singularity  sys	usr
boot  environment  home  lib64	mnt    opt	  root	sbin  srv	   tmp	var
```

Also:

```
[root@viz3 singularity]# git show
commit 3f63807f77ce8beff8b2605d6b0c827a2c13219b
Merge: 54a90cd 2a9ac3a
Author: David Trudgian <david.trudgian@sylabs.io>
Date:   Tue Dec 17 09:56:54 2019 -0600

    Merge pull request #4871 from dctrud/merge352
    
    Merge `release-3.5` to master for 3.5.2
```

Did this fix get lost between #4838 and #4871 ?

**Comment by cousins** [comment] 2019-12-19 22:00
@cclerget : you probably saw this but I'm tagging you anyway now since this is a Closed issue.

**Comment by cousins** [comment] 2019-12-20 16:35
@cclerget : Nevermind. Sorry for the noise. I had two versions of 3.5.1 installed. One in /usr/local/bin (my first attempt) which had the problem. I did a checkout of v3.5.2 and installed it elsewhere but the /usr/local/bin one continued to be used. Now I see that 3.5.2 does indeed fix the problem.
