### ISSUE TITLE
Ignoring user bind request: host does not support PR_SET_NO_NEW_PRIVS

### ISSUE THREAD

**Issue by chrisreidy** [apptainer/singularity#362] opened 2016-11-29 00:25 UTC
Hi

My IBM iDataPlex has the same issue as the Cray at IU.  RHEL 6.4 2.6.32-431.el6.x86_64
My singularity image built on a different system: CentOS Linux release 7.2.1511 
Running any command like this one:
singularity exec centos-mpi.img ls /
returns:
WARNING: Not mounting current directory: host does not support PR_SET_NO_NEW_PRIVS

So I added this to the config:
bind path = /extra
and changed this:
user bind control = no

My testing is working as the image mounts /extra but I am constantly getting:
WARNING: Not mounting current directory: user bind control is disabled by system administrator
Even if I run the command from my home directory and not /extra
Is my configuration still incorrect?  

Thanks
Chris

**Comment by bauerm97** [comment] 2016-11-29 09:19
Hi Chris,

It looks like your configuration is correct. When running an image, Singularity attempts to mount the current working directory into the container as a `userbind`. However since you have `user bind control = no`, Singularity will warn you that it cannot mount your current working directory into the container. Perhaps when `user bind control = no` is set in the configuration, we should not attempt to bind mound the current working directory (hence suppressing the warning).

As far as the PR_SET_NO_NEW_PRIVS, I'm not sure if there is anything we can do to safely enable arbitrary bind points without this flag. We've looked into a few solutions (see #260) but we couldn't yet settle on a safe option.

**Comment by chrisreidy** [comment] 2016-11-29 15:16
Thanks
I can advise users to ignore this warning.  I wanted to be sure that I am maintaining a secure environment, hence the use of Singularity over Docker.

**Comment by gmkurtzer** [comment] 2016-11-29 15:51
Do you always get this warning even when you are in the users home directory or /extra? If so, we should reopen this issue and treat that as a bug. 

Thanks!

**Comment by chrisreidy** [comment] 2016-11-29 18:00
Hi Greg

Yes.  I have a simple test case that I am using:

[chrisreidy@elgato singularity]$ singularity exec centos-mpi.img cat /etc/redhat-release
WARNING: Not mounting current directory: user bind control is disabled by system administrator
CentOS Linux release 7.2.1511 (Core)
[chrisreidy@elgato singularity]$ pwd
/home/u13/chrisreidy/singularity

Thanks
Chris

======================
Chris Reidy
HPC Systems Administrator, Senior
Supercomputing
University Information Technology
University of Arizona
(520) 621-0502

On Nov 29, 2016, at 8:51 AM, Gregory M. Kurtzer <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you always get this warning even when you are in the users home directory or /extra? If so, we should reopen this issue and treat that as a bug.

Thanks!

**Comment by bauerm97** [comment] 2016-11-29 18:37
I think this is a pretty simple fix, we just need to remove the current directory from the list of directories that are to be mounted if the `user bind control = no` is set (or rather never add it to the list, not sure what is better)

**Comment by gmkurtzer** [comment] 2016-11-29 18:43
@chrisreidy will you test [master de63095] please?

@bauerm97 Yep, a pretty easy fix. I just implemented quick to check for device/inode IDs of cwd and container's cwd. If they are the same, don't do anything quietly. lol

Thanks!

**Comment by bauerm97** [comment] 2016-11-29 19:12
@gmkurtzer would you mind explaining to me why you're comparing the inodes of the cwd's? My understanding of this problem is simply that when `user bind control = no`, we shouldn't warn the user that we can't mount the cwd into the container. It appears like your fix will simply check to see if the cwd is already a mounted directory and stop if it is. 

However, if the admin doesn't want cwd mounted in, has `user bind control =no` they will still receive this warning, when it should probably be in debug (or be more descriptive). The block that I believe is causing this is directly above the #ifndef in cwd.c, I believe the warning message should simply be changed in that line to `Warning: not mounting working directory because user bind control is disabled` or something to that effect

**Comment by gmkurtzer** [comment] 2016-11-29 19:16
I did it like this because the behavior should always be what the user expects. And having the current working directory available within the container should be the expected behavior. So if that can't be accomplished, we should print a warning or notification.

In my mind, the bug was not the printing of the message, it was the printing of the message when in fact the CWD is available within the container. The cwd.c module should have quit before giving the user a useless warning (useless because it was not necessary).

**Comment by bauerm97** [comment] 2016-11-29 19:18
Ok I see what you mean. At the same time, I still think the warning message should be more descriptive. Right now it doesn't give a hint as to what the problem is, or whether a user should be worried.

**Comment by gmkurtzer** [comment] 2016-11-29 19:20
I am open to that, what do you suggest?

**Comment by bauerm97** [comment] 2016-11-29 19:21
Some variant of what I wrote up above in that message I think will do it. Just so the user knows what happened, why, and who to blame (not us!)

**Comment by chrisreidy** [comment] 2016-11-29 20:46
Re: @chrisreidy will you test [master de63095] please?
I changed the three files and remade Singularity.  When running "singularity exec" from my home path I get the NO_NEW_PRIVS message.  So far so good.  I change singularity.conf and I still get the message:
WARNING: Not mounting current directory: user bind control is disabled by system administrator

**Comment by gmkurtzer** [comment] 2016-11-29 20:50
If you are still getting the message that means that the directory you are currently located in (the `pwd`/cwd) is not available within the container. If that is indeed the case, then the warning is appropriate. Can you confirm?

Thanks!

**Comment by chrisreidy** [comment] 2016-11-29 21:02
Do you mean like this?

[chris@elgato ~]$ singularity exec centos-TFlow.img echo $PWD
WARNING: Not mounting current directory: user bind control is disabled by system administrator
/home/u13/chris
[chris@elgato ~]$ pwd
/home/u13/chris

**Comment by gmkurtzer** [comment] 2016-11-29 21:20
Can you test now with [master d5985df] and rerun with the --debug option? I've made some additional debugging output and changed the order of some checks.

Thanks and sorry for the back and forth.

**Comment by bauerm97** [comment] 2016-11-29 21:24
@gmkurtzer I haven't tested but these changes look good to me. I maybe didn't articulate well what I was worried about, but I think you've covered everything that needs to be covered now.

**Comment by gmkurtzer** [comment] 2017-03-25 15:38
This seems to be fixed in the development branch. Closing this issue, but let me know if it needs to be reopened.

**Closed as completed by gmkurtzer** 2017-03-25 15:38 UTC
