### ISSUE TITLE
failure to find next loop device

### ISSUE THREAD

**Issue by loveshack** [apptainer/singularity#32] opened 2016-05-10 10:37 UTC
At least in centos 6, if I have an existing loop mount, bootstrap fails:

```
$ sudo losetup -f
/dev/loop1
$ sudo singularity bootstrap c6.img singularity/examples/centos.def 
ERROR: Failed to associate image to loop
ERROR: Could not associate c6.img to loop device /dev/loop0
```

If it's not obvious, I can probably debug it eventually.

**Comment by gmkurtzer** [comment] 2016-05-10 12:27
Can you do a ls -l /dev/loop*; I have a feeling loop0 is wrong.

**Comment by loveshack** [comment] 2016-05-10 13:44
You wrote: 

> Can you do a ls -l /dev/loop*; I have a feeling loop0 is wrong. 

Wrong in what way?  I'd set up a loop mount of another image on loop0 in
a fairly clean VM to reproduce what I was seeing it on login node:

  $ sudo mount -o loop x.img /mnt
  $ sudo singularity bootstrap c6.img singularity/examples/centos.def 
  ERROR: Failed to associate image to loop
  ERROR: Could not associate c6.img to loop device /dev/loop0
  $ sudo losetup -a
  /dev/loop0: [fd00]:915724 (/home/vagrant/x.img)
  $ ls -l /dev/loop*
  brw-rw----. 1 root disk 7, 0 May 10 13:36 /dev/loop0
  brw-rw----. 1 root disk 7, 1 May 10 13:36 /dev/loop1
  brw-rw----. 1 root disk 7, 2 May 10 13:36 /dev/loop2
  brw-rw----. 1 root disk 7, 3 May 10 13:36 /dev/loop3
  brw-rw----. 1 root disk 7, 4 May 10 13:36 /dev/loop4
  brw-rw----. 1 root disk 7, 5 May 10 13:36 /dev/loop5
  brw-rw----. 1 root disk 7, 6 May 10 13:36 /dev/loop6
  brw-rw----. 1 root disk 7, 7 May 10 13:36 /dev/loop7

**Comment by gmkurtzer** [comment] 2016-05-10 13:53
Ahh, I was guessing that the ioctl was failing. But what you found should be easy to fix (knocks wood). I'll hammer on it when I get to keyboard. 

Thanks

**Comment by gmkurtzer** [comment] 2016-05-10 18:30
I was able to reproduce this. Please test master 1af820d.

Thanks!

**Comment by loveshack** [comment] 2016-05-11 09:46
"Gregory M. Kurtzer" notifications@github.com writes:

> I was able to reproduce this. Please test master 1af820d.

It fixes the mount problem, but bootstrap now fails differently for me.
I'll raise another issue.

**Comment by gmkurtzer** [comment] 2016-05-11 16:57
Closing this issue as it seems unrelated to the new issue (specific for RHEL?). Let me know if I am incorrect in this assumption. Thanks!

**Comment by mxmlnkn** [comment] 2019-02-18 13:30
I have the same problem in singularity 3.0.2. Was there a regression?

Steps to reproduce:
```bash
dd if=/dev/zero of=tomount.img bs=1M count=$(( 256 )) &&
yes | mkfs.ext4 tomount.img &&
mkdir -p mounted &&
mounted -o loop "$_"{.img,} &&
singularity -d build --sandbox sandbox debian.sif
```
Output:
```
WARNING [U=0,P=13559]      sylabsToken()                 Authentication token file not found : Only pulls of public images will succeed
DEBUG   [U=0,P=13559]      func1()                       Registering plugin as type BuildPlugin
DEBUG   [U=0,P=13559]      Init()                        Entering image format intializer
DEBUG   [U=0,P=13559]      Init()                        Check for image format sif
DEBUG   [U=0,P=13559]      Init()                        sif format initializer returns: SIF magic not found
DEBUG   [U=0,P=13559]      Init()                        Check for image format sandbox
DEBUG   [U=0,P=13559]      Init()                        sandbox format initializer returns: not a directory image
DEBUG   [U=0,P=13559]      Init()                        Check for image format squashfs
DEBUG   [U=0,P=13559]      Init()                        squashfs format initializer returns: not a valid squashfs image
DEBUG   [U=0,P=13559]      Init()                        Check for image format ext3
DEBUG   [U=0,P=13559]      NewBundle()                   Created temporary directory for bundle /tmp/sbuild-600187955
INFO    [U=0,P=13559]      Full()                        Starting build...
DEBUG   [U=0,P=13559]      Init()                        Entering image format intializer
DEBUG   [U=0,P=13559]      Init()                        Check for image format sif
DEBUG   [U=0,P=13559]      Init()                        sif format initializer returns: SIF magic not found
DEBUG   [U=0,P=13559]      Init()                        Check for image format sandbox
DEBUG   [U=0,P=13559]      Init()                        sandbox format initializer returns: not a directory image
DEBUG   [U=0,P=13559]      Init()                        Check for image format squashfs
DEBUG   [U=0,P=13559]      Init()                        squashfs format initializer returns: not a valid squashfs image
DEBUG   [U=0,P=13559]      Init()                        Check for image format ext3
DEBUG   [U=0,P=13559]      GetLocalPacker()              Packing from Ext3
DEBUG   [U=0,P=13559]      unpackExt3()                  Mounting loop device /dev/loop0 to /tmp/sbuild-600187955/mnt670815734
ERROR   [U=0,P=13559]      unpackExt3()                  Mount Failed: device or resource busy
ERROR   [U=0,P=13559]      Pack()                        unpackExt3 Failed: device or resource busy
FATAL   [U=0,P=13559]      run()                         While performing build: packer failed to pack: device or resource busy
```

Loop devices:

```
la /dev/loop*
    brw-rw---- 1 root disk  7,   0 Feb 18 14:21 /dev/loop0
    brw-rw---- 1 root disk  7,   1 Feb 18 14:22 /dev/loop1
    brw-rw---- 1 root disk  7,   2 Feb 18 14:18 /dev/loop2
    crw-rw---- 1 root disk 10, 237 Feb 18 14:00 /dev/loop-control
```

Workaround: Use /dev/loop1 for mounting the other image so that /dev/loop0 is unused for singularity:
```
umount mounted && mounted -o loop=/dev/loop1 "$_"{.img,} 
singularity -d build --sandbox sandbox debian.sif
```

Output:
```
WARNING [U=0,P=13607]      sylabsToken()                 Authentication token file not found : Only pulls of public images will succeed
DEBUG   [U=0,P=13607]      func1()                       Registering plugin as type BuildPlugin
DEBUG   [U=0,P=13607]      Init()                        Entering image format intializer
DEBUG   [U=0,P=13607]      Init()                        Check for image format sif
DEBUG   [U=0,P=13607]      Init()                        sif format initializer returns: SIF magic not found
DEBUG   [U=0,P=13607]      Init()                        Check for image format sandbox
DEBUG   [U=0,P=13607]      Init()                        sandbox format initializer returns: not a directory image
DEBUG   [U=0,P=13607]      Init()                        Check for image format squashfs
DEBUG   [U=0,P=13607]      Init()                        squashfs format initializer returns: not a valid squashfs image
DEBUG   [U=0,P=13607]      Init()                        Check for image format ext3
DEBUG   [U=0,P=13607]      NewBundle()                   Created temporary directory for bundle /tmp/sbuild-000111507
INFO    [U=0,P=13607]      Full()                        Starting build...
DEBUG   [U=0,P=13607]      Init()                        Entering image format intializer
DEBUG   [U=0,P=13607]      Init()                        Check for image format sif
DEBUG   [U=0,P=13607]      Init()                        sif format initializer returns: SIF magic not found
DEBUG   [U=0,P=13607]      Init()                        Check for image format sandbox
DEBUG   [U=0,P=13607]      Init()                        sandbox format initializer returns: not a directory image
DEBUG   [U=0,P=13607]      Init()                        Check for image format squashfs
DEBUG   [U=0,P=13607]      Init()                        squashfs format initializer returns: not a valid squashfs image
DEBUG   [U=0,P=13607]      Init()                        Check for image format ext3
DEBUG   [U=0,P=13607]      GetLocalPacker()              Packing from Ext3
DEBUG   [U=0,P=13607]      unpackExt3()                  Mounting loop device /dev/loop0 to /tmp/sbuild-000111507/mnt936499670
DEBUG   [U=0,P=13607]      unpackExt3()                  Copying filesystem from /tmp/sbuild-000111507/mnt936499670 to /tmp/sbuild-000111507/fs in Bundle
```

I also want to mention that it seems like sending sigint / pressing ctrl+c to singularity will result in the mounted `/tmp/sbuild-000111507/` directory not being dismounted. Because of my trial and errors, I had several orphaned singularity mounts left over ...

**Comment by jscook2345** [comment] 2019-02-20 21:11
Reopening per user comment.

**Comment by cclerget** [comment] 2019-12-02 15:47
@mxmlnkn Closing the issue, not reproducible with newer versions of Singularity. Feel free to ping to re-open the issue if required.

**Closed as completed by cclerget** 2019-12-02 15:47 UTC
Labels: Question, Regression
