### ISSUE TITLE
Container does not have a valid `/bin/sh`

### ISSUE THREAD

**Issue by ankghost0912** [apptainer/singularity#474] opened 2017-01-30 20:44 UTC
Hi, 

I'm trying to build a singularity image using `singularity 2.2`. From my reading the docs, I've created the shell script describing the name and the size of the image. Here's how it looks:
```
sudo rm -f $1
sudo singularity create $1
sudo singularity expand --size 8192 $1
sudo singularity bootstrap $1  $2
sudo singularity exec -B `pwd`:/mnt -w $1 sh /mnt/install_igits.sh
```
When I run this script I get the error: `Container does not have a valid /bin/sh`. Can anyone point me to what I'm doing wrong? 
EDIT: `$1` is the image name and `$2` is the name of the definition file

**Comment by vsoch** [comment] 2017-01-30 23:43
hey @ankghost0912, glad to try and help! Could you please either share the script(s)y, or the complete debug output? The easiest thing to do is have what you have, and first try to reproduce the error, and go from there

**Comment by ankghost0912** [comment] 2017-01-31 15:47
hey @vsoch , I got around this error. Apparently, the bootloader in the definition file was somehow not available. However, once the image is installed with the proper software, I seem not to be able to use `sudo apt-get` (I installed a debian OS), the error message is `sudo command not found`. Do we have to manually set up `sudo` after the image's installation?

**Comment by gmkurtzer** [comment] 2017-01-31 16:15
Hi @ankghost0912. To install apps inside the container as root, you must first be root outside the container, so the `sudo` command must prefix the Singularity command. For example:

```bash
$ sudo singularity shell --writable $1
```

This is because once you have invoked a command within the container, it is disallowed to escalate your privileges even if you have the root password, or sudo installed.

**Comment by vsoch** [comment] 2017-01-31 17:16
@ankghost0912 great news! You should be able to put install commands in the `%post` section of the bootstrap, and this is recommended over using `--writable` after to preserve a record of changes that you made to the container. If you are still having trouble, if you want to share your build specification file, I'd be happy to see if I can reproduce the error.

**Comment by ankghost0912** [comment] 2017-01-31 18:51
Hi @gmkurtzer, all the software given under the `%post` scriptlet is installed properly, but whenever I try to install any specific software that I want in the system, I get the same error (i.e. `sudo: not found`). Following your suggestion, I created an elevated singularity shell , but the error still persists.

**Comment by ankghost0912** [comment] 2017-01-31 22:32
Thanks @vsoch, I presume that is the "best practices" way of installing programs using singularity?

**Comment by vsoch** [comment] 2017-01-31 23:19
Yeah! The basic idea is that, let's say someone stumbles on your container somewhere down the line, and they want to understand how it was made. Without a build specification file, there might be tricks to reverse engineering the build based on the file system, but it would be hard. Let's say that they want to do the exact things you did, but maybe subtract or add a few steps. They would also want a build file for that. The reason we have something like [singularity hub](singularity-hub.org) is because it captures those two things, frozen at a point in time - specifically an image, and a specific version of a build file. As long as an image can be associated with the file, it's completely transparent in that regard.

**Comment by ankghost0912** [comment] 2017-02-01 15:32
Ah thanks for the answer. Just a small question before I close the issue, is there a way to just run the `%post` scriptlet once again on an image after it's created, or do you have to create the image all over again?

**Comment by gmkurtzer** [comment] 2017-02-01 16:21
@ankghost0912 I can't say without more details why you are getting `sudo: not found`. Is it the program `sudo ` itself that isn't found, or is it that `sudo` can't find the program you are trying to launch? What is the location of the program you are trying to run within the container, and what is `$PATH' set to?

It might also be helpful if you copy paste the command(s) you are running as well as the errors.

If you want to run `%post` again, you can remove/comment out everything else in the definition file and then rerun the bootstrap.

**Comment by vsoch** [comment] 2017-02-01 18:16
@ankghost0912 `%post` is intended for one time installation of things. If you want to have regular tests of the container, I would use the `%test` section. For the container's primary running function, you would want to use `%runscript`. If you want to have something that will perform some function that you can call, I would add a simple script to the container that you can target to call with exec.

**Comment by ankghost0912** [comment] 2017-02-02 16:07
Hey thanks @vsoch for pointing that out. @gmkurtzer I believe it is the

**Comment by ankghost0912** [comment] 2017-02-02 16:17
I apologize for closing the issue before I read @gmkurtzer 's comment. I believe it is the case of the former. Since you asked for the command, here's what I've got in the image creation script: `sudo singularity exec -B `pwd`:/mnt -w digits.img sh /mnt/install_digits.sh `. Now the script `install_digits.sh` has these lines: 
```
sudo apt-get --force-yes update
sudo apt-get --force-yes install digits
```
Here's where the error pops up. So, my guess is that the shell within singularity doesn't get the path to `sudo`. And thanks @vsoch your comments helped me to get an initial version of the image running.

**Comment by gmkurtzer** [comment] 2017-03-20 04:48
@ankghost0912 Do you have `sudo` installed inside the container? It is not a standard program installed within a container because it is purposeless (sudo can't work inside a Singularity container). Because of that, I would recommend not installing it inside the container, nor would I include calls to it in your script `install_digits.sh` inside the container.

Hope that helps!

**Comment by gmkurtzer** [comment] 2017-03-26 03:16
Closing this issue. Comment and let me know if it needs to be reopened.

**Closed as completed by gmkurtzer** 2017-03-26 03:16 UTC

**Comment by alanakbik** [comment] 2017-05-10 11:12
Running 'apt-get install sudo' in the container solved this issue for me.
(The torch installation script has many sudo calls so it was necessary.)

**Comment by wisabd** [comment] 2024-08-29 00:59
Foe me there's no command found error for apt-get, sudo as well as yum inside the %post section. Any ideas ?
