### ISSUE TITLE
latest release 2.3 FTBS when building deb 

### ISSUE THREAD

**Issue by Trophime** [apptainer/singularity#699] opened 2017-06-01 13:06 UTC
## Version of Singularity:

2.3

### Expected behavior

build debian package

### Actual behavior

The build crashes first in the configure step because of missing ```python```
After adding ```python-dev``` to ```Build-Depends``` in ```debian/control``` (see attached)
it crashes again:
```
Making all in etc
make[2]: Entering directory '/build/singularity-container-2.3/etc'
./configure_transform.py --defaults ../src/util/config_defaults.h --infile singularity.conf.in --outfile singularity.conf
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /nonexistent/.singularity
Traceback (most recent call last):
  File "./configure_transform.py", line 30, in <module>
    from sutils import (
  File "../libexec/python/sutils.py", line 25, in <module>
    from defaults import (
  File "../libexec/python/defaults.py", line 110, in <module>
    os.mkdir(SINGULARITY_CACHE)
OSError: [Errno 2] No such file or directory: '/nonexistent/.singularity'
```

### Steps to reproduce behavior

I use pdebuild to rebuild the package to make the build in a "proper" way with a clean and minimal debian dist.

**Comment by Trophime** [comment] 2017-06-01 13:08
Here is the ```debian/control``` file I use (from Debian archive):
```
Source: singularity-container
Section: admin
Priority: optional
Maintainer: NeuroDebian Team <team@neuro.debian.net>
Uploaders:
 Dave Love <fx@gnu.org>,
 Mehdi Dogguy <mehdi@debian.org>,
 Yaroslav Halchenko <debian@onerussian.com>,
Build-Depends:
 debhelper (>= 9),
 dh-autoreconf,
 help2man,
 **python-dev (>= 2.6.6-3~)**
# python3.5-dev
Standards-Version: 3.9.8
**X-Python-Version: current**
#X-Python3-Version: >= 3.5
Homepage: http://gmkurtzer.github.io/singularity
Vcs-Git: https://anonscm.debian.org/git/collab-maint/singularity-container.git
Vcs-Browser: https://anonscm.debian.org/git/collab-maint/singularity-container.git

# "singularity" is a packaged game (but the contents don't clash)
Package: singularity-container
Architecture: any
Depends: ${misc:Depends}, ${shlibs:Depends}, python
Description: container platform focused on supporting "Mobility of Compute"
 Mobility of Compute encapsulates the development to compute model
 where developers can work in an environment of their choosing and
 creation and when the developer needs additional compute resources,
 this environment can easily be copied and executed on other platforms.
 Additionally as the primary use case for Singularity is targeted
 towards computational portability, many of the barriers to entry of
 other container solutions do not apply to Singularity making it an
 ideal solution for users (both computational and non-computational)
 and HPC centers.
```

My changes are the lines ```** xxxx **```

**Comment by gmkurtzer** [comment] 2017-06-01 19:33
Looks good, thank you! Can you send a PR with these changes?

**Comment by Trophime** [comment] 2017-06-02 06:15
Yes I can but I still have trouble.
I need to export ```SINGULARITY_CACHEDIR=$(PKGDIR)/var/singularity/cache``` in ```debian/rules``` and comment out the tests which are now run automatically when building the package. 
The tests fail because the script is not able to find ```singularity``` in the path (defined in the script) which only looks for the "usual" directories and not in the "prefixed" directory (I mean sometihng like ``../debian/singularity-container/usr/bin``` and so on) 

Would there be a way to run the tests during the building of the package?

**Comment by vsoch** [comment] 2017-06-02 06:23
Yes, if you write a %test section in your bootstrap spec you can run some tests during the build. Is this what you are looking to do?

**Comment by vsoch** [comment] 2017-06-02 06:24
See http://singularity.lbl.gov/bootstrap-image#test

**Comment by Trophime** [comment] 2017-06-02 06:37
That's not what I was talking about.
I meant in debian now when you build a package it tries to run some tests.
 
In the case of singularity it tries to run: ```sh ./test.sh``` (```test.sh``` is created from ```test.sh.in``` during the build step ```make```) .

Hope I was more clear

**Comment by Trophime** [comment] 2017-06-02 07:04
Here is the exact error you get when building debian package:
```
dh_auto_test
	make -j1 test VERBOSE=1
make[2]: Entering directory '/build/singularity-container-2.3'
sh ./test.sh
Building/Installing Singularity to temporary directory
Reinvoking in a clean shell
ERROR: Could not locate singularity program at: /usr/bin/singularity
Makefile:828: recipe for target 'test' failed
```

A quick work-around could be to change the ```PATH``` in ```test.sh.in```
if there is no "side effects" on the "installed" singularity

**Comment by vsoch** [comment] 2017-06-02 07:10
ahh sorry now I'm looking farther back in time at the original error message - in terms of disabling the tests I think that could definitely work. What we could do to address this:

```
VERBOSE2 SINGULARITY_CACHEDIR found as /nonexistent/.singularity
Traceback (most recent call last):
  File "./configure_transform.py", line 30, in <module>
    from sutils import (
  File "../libexec/python/sutils.py", line 25, in <module>
    from defaults import (
  File "../libexec/python/defaults.py", line 110, in <module>
    os.mkdir(SINGULARITY_CACHE)
OSError: [Errno 2] No such file or directory: '/nonexistent/.singularity'
```
is to simply have some other flag to indicate that the import from defaults is doing some kind of test (and thus not try to create the cache. If you set `SINGULARITY_DISABLE_CACHE` to True then it will set it to be tmp, but again we still wouldn't want any directory to be created. Let's ask @gmkurtzer if we can just disable this entirely, I'm not sure.

**Comment by Trophime** [comment] 2017-06-02 07:48
I tried to follow my idea of changing paths in ```test.sh```
Now I get:
```
sh ./test.sh
Building/Installing Singularity to temporary directory
Reinvoking in a clean shell

################################################################################
Checking environment (script: 01-sanity.sh, testdir: /tmp/stest.yeDeki)

 + sudo true                                                                                     (retval=0) OK
 + sudo false                                                                                    (retval=1) OK
 + which singularity                                                                             (retval=0) OK
 + test -f /tmp/buildd/singularity-container-2.3/debian/singularity-container/etc/singularity    (retval=0) OK

################################################################################
Running Flawfinder (script: 02-flawfinder.sh, testdir: /tmp/stest.pv8HaV)

 + which flawfinder                                                                              (retval=0) OK
 + sh -c flawfinder -SQ --minlevel=3 ../src > '/tmp/stest.pv8HaV/ff.out'                         (retval=0) OK

################################################################################
Checking Python unit tests (script: 05-python-units.sh, testdir: /tmp/stest.xOk31f)

 + python2 -m unittest tests.test_json                                                           (retval=0) OK
 + python2 -m unittest tests.test_helpers                                                        (retval=1) ERROR
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /root/.singularity
VERBOSE2 SINGULARITY_ENVIRONMENT found as None/.singularity.d/environment
VERBOSE2 SINGULARITY_RUNSCRIPT found as None/singularity
VERBOSE2 SINGULARITY_TESTFILE found as None/.singularity.d/test
VERBOSE2 SINGULARITY_DEFFILE found as None/.singularity.d/Singularity
VERBOSE2 SINGULARITY_ENVBASE found as None/.singularity.d/env
VERBOSE2 SINGULARITY_LABELFILE found as None/.singularity.d/labels.json
VERBOSE2 SINGULARITY_INCLUDECMD found as False
VERBOSE2 SINGULARITY_PULLFOLDER found as /build/singularity-container-2.3/libexec/python
VERBOSE2 SHUB_NAMEBYHASH not defined (None)
VERBOSE2 SHUB_NAMEBYCOMMIT not defined (None)
VERBOSE2 SHUB_CONTAINERNAME not defined (None)
VERBOSE2 SINGULARITY_CONTENTS found as None/.singularity.d/.layers
VERBOSE2 SINGULARITY_PYTHREADS found as 9
FF
======================================================================
FAIL: test_docker_size (tests.test_helpers.TestJson)
test the function to return Docker size
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_helpers.py", line 77, in test_docker_size
    self.assertEqual(result['return_code'],0)
AssertionError: 1 != 0

======================================================================
FAIL: test_shub_size (tests.test_helpers.TestJson)
test the function to return Singularity Hub Image Size
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_helpers.py", line 101, in test_shub_size
    self.assertEqual(result['return_code'],0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 2 tests in 1.150s

FAILED (failures=2)
*** PYTHON VERSION 2 UTIL HELPERS TESTING START ***

---START----------------------------------------
Testing Docker Size
SINGULARITY_CACHE=/root/.singularity
---END------------------------------------------

---START----------------------------------------
Testing Singularity Hub Size
---END------------------------------------------
Full output in: /tmp/stest.xOk31f
ERROR: Failed running test: 05-python-units.sh
Makefile:828: recipe for target 'test' failed
make: *** [test] Error 1
```

**Comment by vsoch** [comment] 2017-06-02 15:07
what is the full output for the test error?

**Comment by Trophime** [comment] 2017-06-02 15:22
```
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /root/.singularity
VERBOSE2 SINGULARITY_ENVIRONMENT found as None/.singularity.d/environment
VERBOSE2 SINGULARITY_RUNSCRIPT found as None/singularity
VERBOSE2 SINGULARITY_TESTFILE found as None/.singularity.d/test
VERBOSE2 SINGULARITY_DEFFILE found as None/.singularity.d/Singularity
VERBOSE2 SINGULARITY_ENVBASE found as None/.singularity.d/env
VERBOSE2 SINGULARITY_LABELFILE found as None/.singularity.d/labels.json
VERBOSE2 SINGULARITY_INCLUDECMD found as False
VERBOSE2 SINGULARITY_PULLFOLDER found as /build/singularity-container-2.3/libexec/python
VERBOSE2 SHUB_NAMEBYHASH not defined (None)
VERBOSE2 SHUB_NAMEBYCOMMIT not defined (None)
VERBOSE2 SHUB_CONTAINERNAME not defined (None)
VERBOSE2 SINGULARITY_CONTENTS found as None/.singularity.d/.layers
VERBOSE2 SINGULARITY_PYTHREADS found as 9
FF
======================================================================
FAIL: test_docker_size (tests.test_helpers.TestJson)
test the function to return Docker size
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_helpers.py", line 77, in test_docker_size
    self.assertEqual(result['return_code'],0)
AssertionError: 1 != 0

======================================================================
FAIL: test_shub_size (tests.test_helpers.TestJson)
test the function to return Singularity Hub Image Size
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_helpers.py", line 101, in test_shub_size
    self.assertEqual(result['return_code'],0)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 2 tests in 0.713s

```

**Comment by vsoch** [comment] 2017-06-02 15:26
could you tell me the steps for how to reproduce this (eg using the debian install?) it looks like it works ok on circle (tests pass) so if I can debug it locally I can see why the return code is 1 (indicating error) and not 0.

**Comment by Trophime** [comment] 2017-06-02 15:40
In debian/rules you just have to comment out the only ```override_dh_auto_test```.
If you try to build the package with pbuilder, first create a pbuilder image (see [this guide](https://wiki.ubuntu.com/PbuilderHowto#Troubleshooting_.22pbuilder_create.22) if you are not familiar with that) in my case I use Debian/stretch.

Then you can simply generate the package with ```DIST=stretch pdebuild```
It actually try to build the package in a chroot env.

At this point the package will FTBS when running the test  (in ```make -j1 test``` actually)

To understand what was going wrong I patched test.sh:
```
Index: singularity-container-2.3/test.sh.in
===================================================================
--- singularity-container-2.3.orig/test.sh.in
+++ singularity-container-2.3/test.sh.in
@@ -22,11 +22,11 @@
 # 
 
 
-prefix="@prefix@"
+prefix="${destdir}/@prefix@"
 exec_prefix="@exec_prefix@"
 libexecdir="@libexecdir@"
-sysconfdir="@sysconfdir@"
-localstatedir="@localstatedir@"
+sysconfdir="${destdir}/@sysconfdir@"
+localstatedir="${destdir}/@localstatedir@"
 bindir="@bindir@"
 
 SINGULARITY_OVERLAY_FS="@OVERLAY_FS@"
@@ -41,12 +41,14 @@ export SINGULARITY_libexecdir SINGULARIT
 
 
 
-if [ -z "$CLEAN_SHELL" ]; then
-    /bin/echo "Building/Installing Singularity to temporary directory"
-    /bin/echo "Reinvoking in a clean shell"
-    sleep 1
-    exec env -i CLEAN_SHELL=1 PATH="$SINGULARITY_PATH:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin" bash "$0" "$@"
-fi
+# if [ -z "$CLEAN_SHELL" ]; then
+#     /bin/echo "Building/Installing Singularity to temporary directory"
+#     /bin/echo "Reinvoking in a clean shell"
+#     sleep 1
+#     exec env -i CLEAN_SHELL=1 PATH="$SINGULARITY_PATH:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin" bash "$0" "$@"
+# fi
+
+export PATH=$SINGULARITY_PATH:$PATH
 
 if [ ! -f "autogen.sh" ]; then
     /bin/echo "ERROR: Run this from the singularity source root"
```

and still in the chroot env I relaunch ```destdir=$(PWD)/Debian/singularity-conainer make test```

Tried to be clear but may be it's not...
Tell me if you need more details

**Comment by Trophime** [comment] 2017-06-02 15:43
in short:
* uncomment the ```override_dh_auto_test``` in ```debian\rules```
* try to rebuild the package with ```pbuilder```
* in the chrooted pbuilder environment change the path to ```singularity``` and ```etc``` directory in ```test.sh```
* run ```make test.sh```

**Comment by yarikoptic** [comment] 2017-06-02 18:47
ah -- great to see activity/contributions in updating debian packaging!  note that "official" packaging repository was setup separately from the "upstream" (this) repository to facilitate contributions/maintenance by other debian developers/maintainers.   I just ran into this CACHE mkdir behavior (imho nothing should mkdir while purely importing a module), and indeed running tests should be disabled since they require full sudo access, and package should build fine through fakeroot as well.  I hope to push out new package within few hours

edit -- url to the packaging repo: http://git.debian.org/?p=collab-maint/singularity-container.git

**Comment by vsoch** [comment] 2017-06-02 20:37
thanks @yarikoptic !

**Comment by gmkurtzer** [comment] 2017-06-03 00:42
I would personally not do the test automatically from the builder (I don't do it in the RPM SPEC). This is because the `make test` command currently calls Singularity from the installed path, and the Singularity internals will fail on many levels as due to the SUID nature of the program (among other things), various paths are hard coded in the binaries. This means that an install to `DESTDIR`, and a test from there, or even the compiled source tree itself, won't work.

Does that make sense?

**Comment by Trophime** [comment] 2017-06-03 09:27
Yes that sounds reasonable then to not perform tests in the builder.

**Comment by gmkurtzer** [comment] 2017-06-04 02:21
Excellent. Closing the issue, but feel free to comment to let me know if I missed something.

(I love closing issues!) lol

**Closed as completed by gmkurtzer** 2017-06-04 02:21 UTC
