### ISSUE TITLE
Problem importing Bioconductor

### ISSUE THREAD

**Issue by verdurin** [apptainer/singularity#862] opened 2017-08-06 07:59 UTC
## Version of Singularity:

2.3.1

### Expected behavior

Import the Docker container provided by `Bioconductor`

### Actual behavior

Size of the image not detected, and the `size.py` script doesn't work either

### Steps to reproduce behavior
```
export SINGULARITY_CONTAINER=docker://bioconductor/release_sequencing
export SINGULARITY_CONTENTS=./blob.txt
$EBROOTSINGULARITY/libexec/singularity/python/size.py
VERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_FIX_PERMS found as False
VERBOSE2 SINGULARITY_COLORIZE not defined (None)
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /home/camp/huffmaa/.singularity
VERBOSE2 SINGULARITY_ENVIRONMENT found as None/.singularity.d/environment
VERBOSE2 SINGULARITY_RUNSCRIPT found as None/singularity
VERBOSE2 SINGULARITY_TESTFILE found as None/.singularity.d/test
VERBOSE2 SINGULARITY_DEFFILE found as None/.singularity.d/Singularity
VERBOSE2 SINGULARITY_ENVBASE found as None/.singularity.d/env
VERBOSE2 SINGULARITY_LABELFILE found as None/.singularity.d/labels.json
VERBOSE2 SINGULARITY_INCLUDECMD found as False
VERBOSE2 SINGULARITY_PULLFOLDER found as /camp/home/huffmaa/singularity
VERBOSE2 SHUB_NAMEBYHASH not defined (None)
VERBOSE2 SHUB_NAMEBYCOMMIT not defined (None)
VERBOSE2 SHUB_CONTAINERNAME not defined (None)
VERBOSE2 SINGULARITY_CONTENTS found as ./blob.txt
VERBOSE2 SINGULARITY_PYTHREADS found as 9
VERBOSE2 SINGULARITY_CONTAINER found as docker://bioconductor/release_sequencing
DEBUG Found uri docker://
DEBUG Found uri docker://
DEBUG Docker sizes will be written to: ./blob.txt
VERBOSE2 SINGULARITY_DOCKER_USERNAME not defined (None)
VERBOSE2 SINGULARITY_DOCKER_PASSWORD found
DEBUG Starting Docker SIZE, will get size from manifest
VERBOSE Docker image: bioconductor/release_sequencing
DEBUG Headers found: Content-Type,Accept
VERBOSE Registry: index.docker.io
VERBOSE Namespace: bioconductor
VERBOSE Repo Name: release_sequencing
VERBOSE Repo Tag: latest
VERBOSE Version: None
VERBOSE Obtaining tags: https://index.docker.io/v2/bioconductor/release_sequencing/tags/list
DEBUG GET https://index.docker.io/v2/bioconductor/release_sequencing/tags/list
DEBUG Http Error with code 401
DEBUG GET https://auth.docker.io/token?service=registry.docker.io&expires_in=9000&scope=repository:bioconductor/release_sequencing:pull
DEBUG Headers found: Content-Type,Authorization,Accept
VERBOSE3 Response on obtaining token is None.
VERBOSE Obtaining manifest: https://index.docker.io/v2/bioconductor/release_sequencing/manifests/latest
DEBUG GET https://index.docker.io/v2/bioconductor/release_sequencing/manifests/latest
VERBOSE2 Writing file ./blob.txt with mode w.
```

**Comment by vsoch** [comment] 2017-08-06 08:59
This is expected behavior for images with manifest version 1 -  we can't estimate the size, because It's just not there. 

To debug, please try this on an image with a known version 2 manifest and report back if there is still error. For bioconductor images, you would do best to specify a size with '--size'.

**Comment by verdurin** [comment] 2017-08-07 09:48
@vsoch okay, I'll contact the Bioconductor upstream to see if they'll consider changing their images.

**Comment by vsoch** [comment] 2017-10-18 03:30
hey @verdurin have you tried this with singularity 2.4? The image format is squashfs so you shouldn't need to change / know the size.

**Comment by verdurin** [comment] 2017-10-30 18:18
@vsoch - tried a few times with `2.4` and it certainly doesn't show that error, thanks.

However, after parsing the manifest it doesn't seem to proceed in downloading the layers:
```
[vagrant@localhost ~]$ singularity -d -vvv pull docker://bioconductor/release_metabolomics2
Enabling debugging
Increasing verbosity level (8)
Ending argument loop
Singularity version: 2.4-dist
Exec'ing: /usr/libexec/singularity/cli/pull.exec
Singularity Image: ./release_metabolomics2.imgWARNING: pull for Docker Hub is not guaranteed to produce the
WARNING: same image on repeated pull. Use Singularity Registry
WARNING: (shub://) to pull exactly equivalent images.
Docker image path: index.docker.io/bioconductor/release_metabolomics2:latest
Cache folder set to /home/vagrant/.singularity/docker
[1/26] ||----------------------------------|   0.0%
```
That could be an artifact of running within a Vagrant box. I'll try directly on a Linux box, too.

**Comment by verdurin** [comment] 2017-10-30 18:37
Okay, must be upstream slowness. The layers are downloading now.

**Comment by vsoch** [comment] 2017-10-30 21:01
Yeah since the counter goes up per layer, if one takes a really long time it doesn't look like it's moving. Let us know if it works!

**Comment by GodloveD** [comment] 2017-10-31 10:40
I'm going to close this since I think it is an issue with Docker Hub.  But feel free to re-open if there are any more issues.

**Closed as completed by GodloveD** 2017-10-31 10:40 UTC

**Comment by verdurin** [comment] 2017-10-31 17:38
For the sake of completeness, I was able to run this again just now and it worked fine with the new `Bioconductor` images, using `2.4`.
