### ISSUE TITLE
authentication is not working (per our example) for private repos on docker registry

### ISSUE THREAD

**Issue by vsoch** [apptainer/singularity#435] opened 2017-01-02 21:44 UTC
@flx42 could you again test your working example? I can't get it working locally with our old docs. My thinking is that there might be some change to the docker registry API, and if this is the case, I need to dig in to figure out the new criteria/headers/etc.

**Comment by flx42** [comment] 2017-01-03 00:24
I'll try to take a look tomorrow, but not sure if I'll have time. Probably some catch up to do at work after the holidays.

**Comment by vsoch** [comment] 2017-01-03 00:36
awesome thanks! Totally no worries or rush. Happy New Year @flx42 ! :D

**Comment by flx42** [comment] 2017-01-03 20:28
Thanks! Happy New year @vsoch!

It's weird, it seems to be working fine for me:
```
export SINGULARITY_DOCKER_AUTH='--username flx42 --password mygreatpassword'
singularity import cuda-samples docker://flx42/cuda-samples
```
I used latest commit on [master](https://github.com/singularityware/singularity/commit/c99bba71583bfb83f74f4812ab1996c84950e1cb)

**Comment by vsoch** [comment] 2017-01-03 21:00
Ok, I can confirm using the latest commit on master as well! Could it be something about the repository? Just to confirm - this is a private repo hosted on docker hub? For one of my private repos I do:

     sudo singularity create image.img
     sudo singularity import image.img docker://vanessa/levelmoney
     ERROR:python:Error obtaining tags: https://index.docker.io/v2/vanessa/levelmoney/tags/list
     ERROR: Aborting with RETVAL=1

Did you not need sudo for the second command? I think to debug - is there a private repo that you have, that you could add me to, that you can confirm works on your end, and I might try it on mine? I had a user here at Stanford that needs this functionality badly, and we weren't able to get it working! Fingers crossed we messed something up about the repo on docker hub itself!

**Comment by vsoch** [comment] 2017-01-03 21:01
and here is the debug bits to confirm it's about the tags:

      *** STARTING PYTHON CLIENT PORTION ****
      INFO:python:Root file system defined as /var/lib/singularity/mnt/final
      INFO:python:Including Docker command as Runscript? False
      INFO:python:Docker image: vanessa/levelmoney
      INFO:python:Docker image path: vanessa/levelmoney:latest
      INFO:python:Obtaining manifest: https://index.docker.io/v2/vanessa/levelmoney/manifests/latest
      INFO:python:Obtaining tags: https://index.docker.io/v2/vanessa/levelmoney/tags/list
      ERROR:python:Error obtaining tags: https://index.docker.io/v2/vanessa/levelmoney/tags/list

**Comment by vsoch** [comment] 2017-01-03 21:02
repo has one tag: 
![image](https://cloud.githubusercontent.com/assets/814322/21622951/e8214db2-d1b4-11e6-86f0-35923b7f5ae5.png)

**Comment by flx42** [comment] 2017-01-03 21:05
It's indeed a private repo on DockerHub. All commands were ran as root.

**Comment by vsoch** [comment] 2017-01-03 21:50
To fix this, for the next round of updates to the python bits I'll add more debug statements. We've tested between python2 and 3, and with the same repo, and I've also done this on two different machines, but I can't get it to work. I think added some debug statements in the auth function will at least give us insight for next steps.

**Comment by gregcouch** [comment] 2017-02-16 04:15
I get the same error trying to use the official Python docker image for building linux binaries:
```
% sudo singularity --verbose import python-build.img docker://quay.io/pypa/manylinux1_x86_64
increasing verbosity level (2)
Exec'ing: /usr/local/libexec/singularity/cli/import.exec python-build.imgVERBOSE: Set messagelevel to: 2
VERBOSE: Initialize configuration file: /usr/local/etc/singularity/singularity.conf
VERBOSE: Obtaining container name from environment variable
VERBOSE: Calculating image offset
VERBOSE: Found available loop device: /dev/loop0
VERBOSE: Using loop device: /dev/loop0
VERBOSE: Mounting image in read/write
VERBOSE: Setting SINGULARITY_ROOTFS to '/var/lib/singularity/mnt/final'
INFO:python:
*** STARTING PYTHON CLIENT PORTION ****
INFO:python:Root file system defined as /var/lib/singularity/mnt/final
INFO:python:Including Docker command as Runscript? False
INFO:python:Docker image: quay.io/pypa/manylinux1_x86_64
INFO:python:Repo Name: pypa
INFO:python:Repo Tag: latest
INFO:python:Namespace: quay.io
INFO:python:Docker image path: quay.io/pypa:latest
INFO:python:Obtaining manifest: https://index.docker.io/v2/quay.io/pypa/manifests/latest
INFO:python:Obtaining tags: https://index.docker.io/v2/quay.io/pypa/tags/list
ERROR:python:Error obtaining tags: https://index.docker.io/v2/quay.io/pypa/tags/list
ERROR: Aborting with RETVAL=1
VERBOSE: Cleaning sessiondir: /tmp/.singularity-session-0.2069.6029624
```

**Comment by vsoch** [comment] 2017-02-16 15:00
I again see [unauthorized](https://index.docker.io/v2/quay.io/pypa/manifests/latest). Could you pleaes share how you are doing authentication? The debug above should print out some information about this, and I don't see it.

**Comment by flx42** [comment] 2017-02-16 21:30
@vsoch this is not on DockerHub, quay.io is a Docker Registry implementation from CoreOS.
So the problem is here:
```
INFO:python:Obtaining manifest: https://index.docker.io/v2/quay.io/pypa/manifests/latest
```
To change the repository for `singularity import`, it's a bit clumsy:
```
export SINGULARITY_DOCKER_REGISTRY='--registry quay.io'
```
And then it should work.

**Comment by gregcouch** [comment] 2017-02-16 23:01
Thank you.

sudo env SINGULARITY_DOCKER_REGISTRY='--registry quay.io' singularity
import $IMAGE_NAME docker://pypa/manylinux1_x86_64

worked.

**Comment by vsoch** [comment] 2017-02-16 23:22
great! A note - we are going to make this a bit easier for the lib refactor. @gregcouch if you are good, feel free to close the issue.

**Comment by gmkurtzer** [comment] 2017-03-25 19:06
Closing this issue as I think it is resolved. Feel free to comment and let me know if it should be reopened. Thanks!

**Closed as completed by gmkurtzer** 2017-03-25 19:06 UTC
