### ISSUE TITLE
Zypper bootstrap on SLES11

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#2980] opened 2019-03-21 01:00 UTC
## Version of Singularity:

3.1

### Expected behavior

Been able to build from a zypper bootstrap on a SLES11 host

### Actual behavior

```
-bash-3.2$ sudo singularity build zypper.img opensuse.def 
eduardo's password:
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Adding repository 'repo-oss' [done]
Repository 'repo-oss' successfully added
Enabled: Yes
Autorefresh: No
GPG check: Yes
URI: http://download.opensuse.org/distribution/leap/42.3/repo/oss/

Retrieving repository 'repo-oss' metadata [\]

Automatically importing the following key:
Key ID: B88B2FD43DBDC284
Key Name: openSUSE Project Signing Key <opensuse@opensuse.org>
Key Fingerprint: 22C07BA534178CD02EFE22AAB88B2FD43DBDC284
Key Created: Mon May  5 08:37:40 2014
Key Expires: Thu May  2 08:37:40 2024
Repository: repo-oss

Retrieving repository 'repo-oss' metadata [done]
Building repository 'repo-oss' cache [done]
All repositories have been refreshed.
Unknown option '--releasever=42.3'
FATAL:   While performing build: conveyor failed to get: While bootstrapping from zypper: exit status 2
```

### Steps to reproduce behavior
Use the zypper example on the singularity source tree
```
singularity build my_suse.sif examples/opensuse/Singularity
```

**Comment by ikaneshiro** [comment] 2019-03-28 17:39
This issue is caused by `--releasever` not existing for that version of `zypper`. That flag was added with this commit: https://github.com/openSUSE/zypper/commit/7c1b2612fe6cef95461cdfccc28bda3d99706b9f and introduced in version `1.11.20`. So host must have a `zypper` of `1.11.20` in order to use the `Zypper Bootstrap` from definitions. Otherwise `zypper` can be installed using `scratch` with `%setup` or from an existing `library` or `registry` image.

**Comment by jscook2345** [comment] 2019-03-30 20:48
We won't be fixing this, so we should document it!

I opened https://github.com/sylabs/singularity-userdocs/issues/123 to do just that.

Thanks for your work on this @ArangoGutierrez @ikaneshiro

**Closed as completed by jscook2345** 2019-03-30 20:48 UTC
Labels: wontfix, Documentation, ImageBuilding
