### ISSUE TITLE
Error in building RPM on Singularity 3.2.0

### ISSUE THREAD

**Issue by sgabenov** [apptainer/singularity#3581] opened 2019-05-20 17:22 UTC
## Version of Singularity:
3.2.0

### Expected behavior

sudo -E rpmbuild -tb singularity-3.2.0.tar.gz 
should build an rpm

### Actual behavior
$go version
go version go1.12.5 linux/amd64

error: Failed build dependencies:
        golang is needed by singularity-3.2.0-1.el7.centos.x86_64

Previous versions of Singularity can be build with this Go binary, error only on the latest Singularity

if i disable check of golang in singularity.spec i got such error:
import cycle not allowed

### Steps to reproduce behavior

sudo -E rpmbuild -tb singularity-3.2.0.tar.gz

**Comment by jscook2345** [comment] 2019-05-21 14:30
We use the EPEL golang RPM to build the centos RPMs on centos. That is why you are seeing that error.

You can try with `rpmbuild --no-deps` if you know you have all of the dependencies available.

**Comment by sgabenov** [comment] 2019-05-22 11:20
Thank you. I was able to build the rpm with --nodeps.
But now i can do this only from root account. If i do the build with sudo or sudo -E
it always throws a go error: "import cycle not allowed"

**Comment by jscook2345** [comment] 2019-05-23 13:34
Can you include all of the commands you used and their output here so we can help you debug? There should not be a go error

**Comment by sgabenov** [comment] 2019-06-06 10:17
```
bash-4.2$ sudo -E rpmbuild --nodeps -tb ./singularity-3.2.1.tar.gz
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.lMAFcq
+ umask 022
+ cd /usr/src/redhat/BUILD
+ rm -rf singularity-3.2.1
+ mkdir singularity-3.2.1
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.uajeSC
+ umask 022
+ cd /usr/src/redhat/BUILD
+ cd singularity-3.2.1
+ mkdir -p gopath/src/github.com/sylabs/singularity
+ tar -C gopath/src/github.com/sylabs/ -xf /scratch/jenkins_slave/workspace/utility-rpmbuild-singularity-v3/singularity-3.2.1.tar.gz
+ export GOPATH=/usr/src/redhat/BUILD/singularity-3.2.1/gopath
+ GOPATH=/usr/src/redhat/BUILD/singularity-3.2.1/gopath
+ export PATH=/usr/src/redhat/BUILD/singularity-3.2.1/gopath/bin:/sbin:/bin:/usr/sbin:/usr/bin
+ PATH=/usr/src/redhat/BUILD/singularity-3.2.1/gopath/bin:/sbin:/bin:/usr/sbin:/usr/bin
+ cd /usr/src/redhat/BUILD/singularity-3.2.1/gopath/src/github.com/sylabs/singularity
+ ./mconfig -V 3.2.1-1.el7.centos --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info
Configuring for project `singularity' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host C compiler option -Wall... yes
 checking: host C compiler option -Werror... yes
 checking: host C compiler option -Wfatal-errors... yes
 checking: host C compiler option -Wno-unknown-warning-option... yes
 checking: host C compiler option -Wstrict-prototypes... yes
 checking: host C compiler option -Wpointer-arith... yes
 checking: host C compiler option -Wbad-function-cast... yes
 checking: host C compiler option -Woverlength-strings... yes
 checking: host C compiler option -Wframe-larger-than=2047... yes
 checking: host C compiler option -Wno-sign-compare... yes
 checking: host C compiler option -Wclobbered... yes
 checking: host C compiler option -Wempty-body... yes
 checking: host C compiler option -Wmissing-parameter-type... yes
 checking: host C compiler option -Wtype-limits... yes
 checking: host C compiler option -Wunused-parameter... yes
 checking: host C compiler option -Wunused-but-set-parameter... yes
 checking: host C compiler option -Wno-discarded-qualifiers... yes
 checking: host C compiler option -Wno-incompatible-pointer-types... yes
 checking: host C compiler option -pipe... yes
 checking: host C compiler option -fmessage-length=0... yes
 checking: host C compiler option -fPIC... yes
 checking: host `ar' path... ar
 checking: host `ld' path... ld
 checking: host `ranlib' path... ranlib
 checking: host `objcopy' path... objcopy
 checking: target C compiler... cc
 checking: target C++ compiler... c++
 checking: target `ar' path... ar
 checking: target `ld' path... ld
 checking: target `ranlib' path... ranlib
 checking: target `objcopy' path... objcopy
 checking: host compiles static binaries... yes
 checking: target compiles static binaries... yes
 checking: host os type... unix
 checking: host architecture... x86_64
 checking: target architecture... x86_64
 checking: host architecture word size... 64
 checking: target architecture word size... 64
 checking: project version... 3.2.1-1.el7.centos
 checking: project short version... 3.2.1
 checking: golang compiler version... 1.11
=> running post-basechecks project specific checks ...
 checking: namespace: CLONE_NEWPID... yes
 checking: namespace: CLONE_FS... yes
 checking: namespace: CLONE_NEWNS... yes
 checking: namespace: CLONE_NEWUSER... yes
 checking: namespace: CLONE_NEWIPC... yes
 checking: namespace: CLONE_NEWNET... yes
 checking: namespace: CLONE_NEWUTS... yes
 checking: namespace: CLONE_NEWCGROUP... no
 checking: feature: NO_NEW_PRIVS... yes
 checking: feature: MS_SLAVE... yes
 checking: feature: MS_REC... yes
 checking: feature: MS_PRIVATE... yes
 checking: user capabilities... yes
 checking: header linux/securebits.h... yes
 checking: header linux/capability.h... yes
 checking: function setns... yes
 checking: libssl+headers... yes
 checking: libuuid+headers... yes
 checking: libseccomp+headers... yes
=> generating fragments ...
=> building Makefile ...
=> generating singularity.spec ...
=> project singularity setup with :
    - host arch: x86_64
    - host wordsize: 64-bit
    - host C compiler: cc
    - host system: unix
      ---
    - target arch: x86_64
    - target wordsize: 64-bit
    - target C compiler: cc
      ---
    - config profile: release
      ---
    - SUID install: yes
    - Network plugins: yes
      ---
    - verbose: no
      ---
    - version: 3.2.1-1.el7.centos
=> /usr/src/redhat/BUILD/singularity-3.2.1/gopath/src/github.com/sylabs/singularity/builddir/Makefile ready, try:
   $ cd /usr/src/redhat/BUILD/singularity-3.2.1/gopath/src/github.com/sylabs/singularity/builddir
   $ make
+ cd builddir
+ make old_config=
flag provided but not defined: -deps
usage: list [-e] [-f format] [-json] [build flags] [packages]

List lists the packages named by the import paths, one per line.

The default output shows the package import path:

    bytes
    encoding/json
    github.com/gorilla/mux
    golang.org/x/net/html

The -f flag specifies an alternate format for the list, using the
syntax of package template.  The default output is equivalent to -f
'{{.ImportPath}}'. The struct being passed to the template is:

    type Package struct {
        Dir           string // directory containing package sources
        ImportPath    string // import path of package in dir
        ImportComment string // path in import comment on package statement
        Name          string // package name
        Doc           string // package documentation string
        Target        string // install path
        Shlib         string // the shared library that contains this package (only set when -linkshared)
        Goroot        bool   // is this package in the Go root?
        Standard      bool   // is this package part of the standard Go library?
        Stale         bool   // would 'go install' do anything for this package?
        StaleReason   string // explanation for Stale==true
        Root          string // Go root or Go path dir containing this package
        ConflictDir   string // this directory shadows Dir in $GOPATH
        BinaryOnly    bool   // binary-only package: cannot be recompiled from sources

        // Source files
        GoFiles        []string // .go source files (excluding CgoFiles, TestGoFiles, XTestGoFiles)
        CgoFiles       []string // .go sources files that import "C"
        IgnoredGoFiles []string // .go sources ignored due to build constraints
        CFiles         []string // .c source files
        CXXFiles       []string // .cc, .cxx and .cpp source files
        MFiles         []string // .m source files
        HFiles         []string // .h, .hh, .hpp and .hxx source files
        FFiles         []string // .f, .F, .for and .f90 Fortran source files
        SFiles         []string // .s source files
        SwigFiles      []string // .swig files
        SwigCXXFiles   []string // .swigcxx files
        SysoFiles      []string // .syso object files to add to archive
        TestGoFiles    []string // _test.go files in package
        XTestGoFiles   []string // _test.go files outside package

        // Cgo directives
        CgoCFLAGS    []string // cgo: flags for C compiler
        CgoCPPFLAGS  []string // cgo: flags for C preprocessor
        CgoCXXFLAGS  []string // cgo: flags for C++ compiler
        CgoFFLAGS    []string // cgo: flags for Fortran compiler
        CgoLDFLAGS   []string // cgo: flags for linker
        CgoPkgConfig []string // cgo: pkg-config names

        // Dependency information
        Imports      []string // import paths used by this package
        Deps         []string // all (recursively) imported dependencies
        TestImports  []string // imports from TestGoFiles
        XTestImports []string // imports from XTestGoFiles

        // Error information
        Incomplete bool            // this package or a dependency has an error
        Error      *PackageError   // error loading package
        DepsErrors []*PackageError // errors loading dependencies
    }

Packages stored in vendor directories report an ImportPath that includes the
path to the vendor directory (for example, "d/vendor/p" instead of "p"),
so that the ImportPath uniquely identifies a given copy of a package.
The Imports, Deps, TestImports, and XTestImports lists also contain these
expanded imports paths. See golang.org/s/go15vendor for more about vendoring.

The error information, if any, is

    type PackageError struct {
        ImportStack   []string // shortest path from package named on command line to this one
        Pos           string   // position of error (if present, file:line:col)
        Err           string   // the error itself
    }

The template function "join" calls strings.Join.

The template function "context" returns the build context, defined as:

        type Context struct {
                GOARCH        string   // target architecture
                GOOS          string   // target operating system
                GOROOT        string   // Go root
                GOPATH        string   // Go path
                CgoEnabled    bool     // whether cgo can be used
                UseAllFiles   bool     // use files regardless of +build lines, file names
                Compiler      string   // compiler to assume when computing target paths
                BuildTags     []string // build constraints to match in +build lines
                ReleaseTags   []string // releases the current release is compatible with
                InstallSuffix string   // suffix to use in the name of the install dir
        }

For more information about the meaning of these fields see the documentation
for the go/build package's Context type.

The -json flag causes the package data to be printed in JSON format
instead of using the template format.

The -e flag changes the handling of erroneous packages, those that
cannot be found or are malformed.  By default, the list command
prints an error to standard error for each erroneous package and
omits the packages from consideration during the usual printing.
With the -e flag, the list command never prints errors to standard
error and instead processes the erroneous packages with the usual
printing.  Erroneous packages will have a non-empty ImportPath and
a non-nil Error field; other information may or may not be missing
(zeroed).

For more about build flags, see 'go help build'.

For more about specifying packages, see 'go help packages'.
flag provided but not defined: -deps
usage: list [-e] [-f format] [-json] [build flags] [packages]

List lists the packages named by the import paths, one per line.

The default output shows the package import path:

    bytes
    encoding/json
    github.com/gorilla/mux
    golang.org/x/net/html

The -f flag specifies an alternate format for the list, using the
syntax of package template.  The default output is equivalent to -f
'{{.ImportPath}}'. The struct being passed to the template is:

    type Package struct {
        Dir           string // directory containing package sources
        ImportPath    string // import path of package in dir
        ImportComment string // path in import comment on package statement
        Name          string // package name
        Doc           string // package documentation string
        Target        string // install path
        Shlib         string // the shared library that contains this package (only set when -linkshared)
        Goroot        bool   // is this package in the Go root?
        Standard      bool   // is this package part of the standard Go library?
        Stale         bool   // would 'go install' do anything for this package?
        StaleReason   string // explanation for Stale==true
        Root          string // Go root or Go path dir containing this package
        ConflictDir   string // this directory shadows Dir in $GOPATH
        BinaryOnly    bool   // binary-only package: cannot be recompiled from sources

        // Source files
        GoFiles        []string // .go source files (excluding CgoFiles, TestGoFiles, XTestGoFiles)
        CgoFiles       []string // .go sources files that import "C"
        IgnoredGoFiles []string // .go sources ignored due to build constraints
        CFiles         []string // .c source files
        CXXFiles       []string // .cc, .cxx and .cpp source files
        MFiles         []string // .m source files
        HFiles         []string // .h, .hh, .hpp and .hxx source files
        FFiles         []string // .f, .F, .for and .f90 Fortran source files
        SFiles         []string // .s source files
        SwigFiles      []string // .swig files
        SwigCXXFiles   []string // .swigcxx files
        SysoFiles      []string // .syso object files to add to archive
        TestGoFiles    []string // _test.go files in package
        XTestGoFiles   []string // _test.go files outside package

        // Cgo directives
        CgoCFLAGS    []string // cgo: flags for C compiler
        CgoCPPFLAGS  []string // cgo: flags for C preprocessor
        CgoCXXFLAGS  []string // cgo: flags for C++ compiler
        CgoFFLAGS    []string // cgo: flags for Fortran compiler
        CgoLDFLAGS   []string // cgo: flags for linker
        CgoPkgConfig []string // cgo: pkg-config names

        // Dependency information
        Imports      []string // import paths used by this package
        Deps         []string // all (recursively) imported dependencies
        TestImports  []string // imports from TestGoFiles
        XTestImports []string // imports from XTestGoFiles

        // Error information
        Incomplete bool            // this package or a dependency has an error
        Error      *PackageError   // error loading package
        DepsErrors []*PackageError // errors loading dependencies
    }

Packages stored in vendor directories report an ImportPath that includes the
path to the vendor directory (for example, "d/vendor/p" instead of "p"),
so that the ImportPath uniquely identifies a given copy of a package.
The Imports, Deps, TestImports, and XTestImports lists also contain these
expanded imports paths. See golang.org/s/go15vendor for more about vendoring.

The error information, if any, is

    type PackageError struct {
        ImportStack   []string // shortest path from package named on command line to this one
        Pos           string   // position of error (if present, file:line:col)
        Err           string   // the error itself
    }

The template function "join" calls strings.Join.

The template function "context" returns the build context, defined as:

        type Context struct {
                GOARCH        string   // target architecture
                GOOS          string   // target operating system
                GOROOT        string   // Go root
                GOPATH        string   // Go path
                CgoEnabled    bool     // whether cgo can be used
                UseAllFiles   bool     // use files regardless of +build lines, file names
                Compiler      string   // compiler to assume when computing target paths
                BuildTags     []string // build constraints to match in +build lines
                ReleaseTags   []string // releases the current release is compatible with
                InstallSuffix string   // suffix to use in the name of the install dir
        }

For more information about the meaning of these fields see the documentation
for the go/build package's Context type.

The -json flag causes the package data to be printed in JSON format
instead of using the template format.

The -e flag changes the handling of erroneous packages, those that
cannot be found or are malformed.  By default, the list command
prints an error to standard error for each erroneous package and
omits the packages from consideration during the usual printing.
With the -e flag, the list command never prints errors to standard
error and instead processes the erroneous packages with the usual
printing.  Erroneous packages will have a non-empty ImportPath and
a non-nil Error field; other information may or may not be missing
(zeroed).

For more about build flags, see 'go help build'.

For more about specifying packages, see 'go help packages'.
import cycle not allowed
package main
        imports bufio
        imports bytes
        imports errors
        imports runtime
        imports internal/bytealg
        imports internal/cpu
        imports runtime
config_gen.go:8: running "go": exit status 1
make: *** [/usr/src/redhat/BUILD/singularity-3.2.1/gopath/src/github.com/sylabs/singularity/internal/pkg/buildcfg/config.go] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.uajeSC (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.uajeSC (%build)```

**Comment by jmstover** [comment] 2019-06-06 16:20
@sgabenov 

Can you run both:
```
go version
sudo go version
```
The error:  "flag provided but not defined: -deps" ... should be from go 1.10.x. To me it looks like theres a Go version conflict somewhere

**Comment by mem** [comment] 2019-09-24 20:44
1.12 should be fine; the message suggests that the go version that is running does not support the -deps flag to `go list`, which means that it's an older go version (I believe the flag was added in 1.11).

The specific error you are quoting means that the "golang" package is not installed, even if the "go" program is available in your PATH. To build RPM packages, it's necessary to have the golang package installed, as the .spec file says.

Later singularity releases show the path to the go binary that it's going to be used as part of the mconfig output.

I believe this bug has been fixed, or at least newer versions of singularity will display a better error message. I'm closing it on those grounds. If you can reproduce the issue, please reopen this with additional information.

**Closed as completed by mem** 2019-09-24 20:44 UTC
Labels: Release 3.2.0
