### ISSUE TITLE
bad variable name with singularity import

### ISSUE THREAD

**Issue by jokedurnez** [apptainer/singularity#719] opened 2017-06-03 20:59 UTC
## Version of Singularity:
2.3

### Expected behavior
I'm trying to create a singularity image from a docker container:
```
[jdurnez@sh-101-58]$ singularity create --size 20000 $SINGULARITY
[jdurnez@sh-101-58]$ singularity import $SINGULARITY docker://joke/cnp_task_analysis
Docker image path: index.docker.io/joke/cnp_task_analysis:latest
Cache folder set to /home/users/jdurnez/.singularity/docker
[32/32] |===================================| 100.0%
Importing: base Singularity environment
...
Importing: /home/users/jdurnez/.singularity/metadata/sha256:dbda4988c86376f77fb0ebfc4aadf6f5087acc58bf920df723ea935a197bfd21.tar.gz
```

### Actual behavior
It seems like the singularity container is generated, but when I try to access it:
```
[jdurnez@sh-101-58]$ singularity shell $SINGULARITY
Singularity: Invoking an interactive shell within container...

/.singularity.d/actions/shell: 35: export: /opt/mcr/v85/: bad variable name
```

However, with docker2singularity, it works.
```
[ec2-user@ip-172-31-3-3 CNP_task_analysis]$ docker run -v /var/run/docker.sock:/var/run/docker.sock -v /home/ec2-user/singularity:/output --privileged -t --rm singularityware/docker2singularity joke/cnp_task_analysis
...
(9/9) Moving the image to the output folder...
 11,954,815,008 100%   61.77MB/s    0:03:04 (xfr#1, to-chk=0/1)
[ec2-user@ip-172-31-3-3 singularity]$ singularity shell joke_cnp_task_analysis-2017-06-03-1246c19080c1.img
Singularity: Invoking an interactive shell within container...

ec2-user@ip-172-31-3-3:~/singularity$ python -c "import nipype"
ec2-user@ip-172-31-3-3:~/singularity$
```

**Comment by vsoch** [comment] 2017-06-03 22:49
I've been trying for a few hours to download the layers (albeit my internet is awful). How big of an image is this? I can go to campus later (with a better connection) to test. Based on the error message, here are my first gut feelings about what might be going on. 1) is that somewhere in the environment you might have something that looks like this:

```
export PATH=/bla/bla:$PATH
```
You aren't technically supposed to put the export and variable definition on the same line (I think that is called a "bashism") and it can lead to that "bad variable name" error. I would look in the container's `/singularity.d/env/*` (which are combined to be `/environment` so look there too). And look for statements like that. If you find any, try doing something more like this:

```
PATH=/bla/bla:$PATH
export PATH
```
(two lines)

The second thing that comes to mind is the `SHELL` itself. I would see what shell is being called when you shell in, and then try setting `SINGULARITY_SHELL` to be explicitly `/bin/bash`. Actually, if you have one of said "bashisms" and the error is happening because the shell is `/bin/sh` that might fix it.

Then the third thing that comes to mind (related to the above too) is the top part of any of those files, I've seen that kind of error when I call a script but the top has this bit:

```
#!/bin/sh
```
shabang, whatever it's called, wrong. And again, the shell that you use going in might have influence here. The reason I bring these things up is because if we look at the `actions/shell` we see that all that it does is figure out the shell to use, and source a bunch of files. I'll split this up and add some commentary:

so here we see the default it's using is `/bin/sh`, and this makes sense for older systems support maybe:
```
#!/bin/sh
```

here we see why we want to check the environment files - it just loop de loops through them and sources. So if a shebang / export / is weird, it could cause that error. I would look specifically for the path it mentioned - something about opt?

```
for script in /.singularity.d/env/*.sh; do
    if [ -f "$script" ]; then
        . $script
    fi
done

```
here is why I recommended setting `SINGULARITY_SHELL` - if it's set then we use it, and exit this script

```
if test -n "$SINGULARITY_SHELL" -a -x "$SINGULARITY_SHELL"; then
    exec $SINGULARITY_SHELL "$@"

    echo "ERROR: Failed running shell as defined by '\$SINGULARITY_SHELL'" 1>&2
    exit 1
```

otherwise, we try to do our best to guess, based on what we sniff and find:

```
elif test -x /bin/bash; then
    SHELL=/bin/bash
    PS1="Singularity $SINGULARITY_CONTAINER:\\w> "
    export SHELL PS1
    exec /bin/bash --norc "$@"
elif test -x /bin/sh; then
    SHELL=/bin/sh
    export SHELL
    exec /bin/sh "$@"
else
    echo "ERROR: /bin/sh does not exist in container" 1>&2
fi
exit 1
```
Anyhoo - I would look at those specific things:
 - variables in environment files
 - declarations in environment files
 - selected and used shell given those things

If you can't figure it out from that, then run with `--debug` and see if you can figure out where in the action/shell script the error is happening. If you can't figure it out then, then I'll try to reproduce the error when I can download that monstrous image later. I'm not even looking at it, but I'm almost certain based on the number of layers and time that the base is that fatty mriqc :P

**Comment by vsoch** [comment] 2017-06-04 02:25
ok, I found the issue. In one of your Docker environment files you have this:

```
cat .singularity.d/env/10-docker.sh 
export PATH=/usr/local/miniconda/bin:/usr/lib/ruby/gems/2.3/bin:/bin::/usr/lib/fsl/5.0:/usr/lib/afni/bin:/opt/freesurfer/bin:/opt/freesurfer/tktools:/opt/freesurfer/mni/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
export DEBIAN_FRONTEND=noninteractive
export FS_OVERRIDE=0
export OS=Linux
export FSF_OUTPUT_FORMAT=nii.gz
export FIX_VERTEX_AREA=
export FREESURFER_HOME=/opt/freesurfer
export MNI_DIR=/opt/freesurfer/mni
export SUBJECTS_DIR=/opt/freesurfer/subjects
export PERL5LIB=/opt/freesurfer/mni/share/perl5
export MNI_PERL5LIB=/opt/freesurfer/mni/share/perl5
export MINC_BIN_DIR=/opt/freesurfer/mni/bin
export MINC_LIB_DIR=/opt/freesurfer/mni/lib
export MNI_DATAPATH=/opt/freesurfer/mni/data
export FSL_DIR=/usr/share/fsl/5.0
export FSLDIR=/usr/share/fsl/5.0
export FSLOUTPUTTYPE=NIFTI_GZ
export FSLMULTIFILEQUIT=TRUE
export POSSUMDIR=/usr/share/fsl/5.0
export LD_LIBRARY_PATH=/usr/lib/fsl/5.0:
export FSLTCLSH=/usr/bin/tclsh
export FSLWISH=/usr/bin/wish
export AFNI_MODELPATH=/usr/lib/afni/models
export AFNI_IMSAVE_WARNINGS=NO
export AFNI_TTATLAS_DATASET=/usr/share/afni/atlases
export AFNI_PLUGINPATH=/usr/lib/afni/plugins
export ANTSPATH=/opt/ants
export C3DPATH=/opt/c3d/
export GEM_HOME=/usr/lib/ruby/gems/2.3
export BUNDLE_PATH=/usr/lib/ruby/gems/2.3
export BUNDLE_BIN=/usr/lib/ruby/gems/2.3/bin
export BUNDLE_SILENCE_ROOT_WARNING=1
export BUNDLE_APP_CONFIG=/usr/lib/ruby/gems/2.3
export MATLABCMD=/opt/mcr/v85/toolbox/matlab
export SPMMCRCMD=/opt/spm12/run_spm12.sh /opt/mcr/v85/ script
export FORCE_SPMMCR=1
export LANG=C.UTF-8
export LC_ALL=C.UTF-8
export ACCEPT_INTEL_PYTHON_EULA=yes
export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=1
```

and specifically, this line is the bug:

```
export SPMMCRCMD=/opt/spm12/run_spm12.sh /opt/mcr/v85/ script
```

Having the export on the same line, and that entire thing without any " I think is tripping it up.

**Comment by gmkurtzer** [comment] 2017-06-04 02:33
This doesn't sound like a bug with Singularity. :)

**Comment by vsoch** [comment] 2017-06-04 02:34
Heeeey @gmkurtzer you can't close an issue until @jokedurnez has been resolved! The lines that are written to generate that file live in our python code, so there could be something we need to fix here. I'll just reopen this :)

**Comment by gmkurtzer** [comment] 2017-06-04 02:35
OK, as you wish! :)

**Comment by gmkurtzer** [comment] 2017-06-04 02:36
Sorry, I'm on an issue closing rampage!

**Comment by jokedurnez** [comment] 2017-06-04 19:07
Thanks for figuring this out Vanessa !
Although in the original docker file, it's a command with ".
```
ENV MATLABCMD="/opt/mcr/v85/toolbox/matlab" \
    SPMMCRCMD="/opt/spm12/run_spm12.sh /opt/mcr/v85/ script" \
    FORCE_SPMMCR=1
```

And it's the fatty nipype image :-p .  I don't know what to do with this, I linked it to an issue with nipype.

**Comment by satra** [comment] 2017-06-04 19:07
@vsoch and @gmkurtzer - it seems like the environment variable extractor doesn't respect spaces in the string.

**Comment by satra** [comment] 2017-06-04 19:07
in the docker shell those are completely valid environment variables because they are in "quotes"

**Comment by vsoch** [comment] 2017-06-04 20:23
@satra it's actually on Docker's end - the variable that is provided in the manifest does not have any quotes!

```

   u'MATLABCMD=/opt/mcr/v85/toolbox/matlab',
   u'SPMMCRCMD=/opt/spm12/run_spm12.sh /opt/mcr/v85/ script',

```

**Comment by vsoch** [comment] 2017-06-04 20:29
I found this in the docs, although it is for exec:

>> Note: The exec form is parsed as a JSON array, which means that you must use double-quotes (“) around words not single-quotes (‘).

It looks like the section with the ENV variables (History) might also be parsed as a json array? --> https://github.com/docker/distribution/blob/master/manifest/schema1/config_builder.go#L82

**Comment by vsoch** [comment] 2017-06-04 20:30
Maybe we could try double quotes for the Dockerfile?

**Comment by satra** [comment] 2017-08-04 17:21
@jokedurnez - temporarily we are using an shell script to make the docker container with spm compatible with singularity. here is an example to generate such a dockerfile

```
docker run --rm kaczmarj/neurodocker generate -b neurodebian:stretch-non-free -p apt \
--spm version=12 matlab_version=R2017a \
--instruction="RUN sed -i '\$iexport SPMMCRCMD=\"/opt/spm12/run_spm12.sh /opt/mcr/v92/ script\"' \$ND_ENTRYPOINT" \
--user=neuro \
--miniconda python_version=3.6 \
            env_name="neuro" \
            pip_install="https://github.com/nipy/nipype/tarball/master" \
--workdir /home/neuro \
--no-check-urls > Dockerfile
```

@vsoch - perhaps you can check the value with a unix variable regex. if it matches don't double-quote it, if it doesn't then put it in double quotes. wdyt?

**Comment by vsoch** [comment] 2017-08-04 18:11
@satra check what value? Are you suggesting to hard code this particular SPM environment variable into the software?

**Comment by satra** [comment] 2017-08-04 18:22
@vsoch - no hard coding, just handling string values of variables from the manifest properly. the value that your query from docker returns. you were saying that returned variable is a string. if that string has space in it, it should be escaped with the appropriate shell quotes.

```
    u'SPMMCRCMD=/opt/spm12/run_spm12.sh /opt/mcr/v85/ script',
...

key, value = split(environ_line, '=')
if ' ' in value:
    newexport = 'export {key}="{value}"'.format(key=key, value=value)
```

**Comment by vsoch** [comment] 2017-08-04 18:59
yes that is very reasonable I think! Before I make this fix, I filed the issue above to see if there is some resolution that can be done more upstream to the bug. If not, then we will be the fixer fishes!

**Comment by kaczmarj** [comment] 2017-08-04 23:34
@jokedurnez - neurodocker has been updated so the `--spm` flag will automatically add set SPMMCRCMD in the default entrypoint (/neurodocker/startup.sh). The `--instruction` flag is no longer necessary.

```shell
docker run --rm kaczmarj/neurodocker generate -b debian:stretch -p apt --spm version=12 matlab_version=R2017a
```

**Comment by vsoch** [comment] 2017-08-04 23:37
woot! @jokedurnez can the image use the flag instead?

**Comment by kaczmarj** [comment] 2017-08-05 14:39
@vsoch - it would be ideal to be able to write `ENV FOO="BAR BAZ"` in a dockerfile and have singularity accept it. At the moment, an ENV instruction with spaces prevents the singularity image from even starting. The change I made in neurodocker is a workaround for this bug.

**Comment by vsoch** [comment] 2017-08-05 15:55
It comes down to the fact that the Docker manifest itself doesn't honor the quotes. As I noted in the issue above, I think this would be better handled more upstream to the error (in the Docker manifest honoring and returning the quotes to our function) but if this is not possible it would be do-able on our end. The fix isn't hard, it's more about where is the right level to debug.

**Comment by jscook2345** [comment] 2018-10-23 18:59
It looks like a fix for this was merged into our 3.0 release. Is it possible to test with that version? There are a lot of other potential changes, so please let me know if you have any issues. Thanks!

**Comment by bauerm97** [comment] 2019-03-12 21:21
I'm going to close this unless @jokedurnez thinks this is still relevant

**Closed as completed by bauerm97** 2019-03-12 21:21 UTC

**Comment by vsoch** [comment] 2019-03-12 22:23
+1 - @jokedurnez @satra @kaczmarj please test with the 3.0 family and see if there is still an issue. If so, if you can provide a line to reproduce it I'd be glad to look into it again for you.
