### ISSUE TITLE
Unable to write to a container

### ISSUE THREAD

**Issue by sushma-98** [apptainer/singularity#3220] opened 2019-04-04 07:34 UTC
## Version of Singularity:

3.1-2

### Expected behavior

Being able to write to the container after executing it with -w flag.

### Actual behavior

`WARNING: While attempting to set up SIFOverlay: no SIF writable overlay partition found`
`ERROR: Unable to lock database: Read-only file system`
`ERROR: Failed to open apk database: Read-only file system`

### Steps to reproduce behavior

`sudo singularity exec -w alpine_3.9.2.sif apk add htop 
`

**Comment by cclerget** [comment] 2019-04-04 08:37
@sushma-98 It's the expected behaviour since SIF doesn't contain an overlay partition, actually singularity can handle this case but you need to manipulate your SIF image manually with `siftool` to make SIF image writable. By default SIF image contains only a squashfs filesystem partition, and squashfs is a read-only filesystem, you need to use `--writable-tmpfs` or a sandbox image. Closing the issue.

**Closed as completed by cclerget** 2019-04-04 08:37 UTC

**Comment by sushma-98** [comment] 2019-04-05 00:46
Thank you @cclerget Can you please give an example where -w is used? I have to test the `-w` flag
