### ISSUE TITLE
Invalid environment variable name prevents running container

### ISSUE THREAD

**Issue by benmishkanian** [apptainer/singularity#3978] opened 2019-07-23 20:40 UTC
## Version of Singularity:

3.1.0-1.el7.centos

### Expected behavior

According to IEEE Std 1003.1-2001, environment variables may contain any character except '=', even though some shells such as Bash do not support certain characters (such as '.') in environment variable names. Docker allows using '.' in the name of an `ENV` variable, even if the `ENTRYPOINT` is Bash. Running such a Docker container still works, and Bash does not crash. Singularity containers built from such Docker images should work correctly even if the container's shell does not support such environment variable names.

### Actual behavior

Singularity containers built from Docker images that have an `ENV` variable with a '.' character in the name crash when starting Bash.

### Steps to reproduce behavior

Create a Singularity container from the Docker image `jsreport/jsreport:2.5.0` (available on Docker Hub) and try to run it. It fails with the following error:

```-bash: export: `chrome:launchOptions:executablePath=abc': not a valid identifier```

**Comment by sashayakovtseva** [comment] 2019-09-09 15:36
@amjad you said this issue is fixed in https://github.com/sylabs/singularity/pull/4398#issuecomment-529466896, but I still can reproduce it by running

```
$ singularity shell docker://jsreport/jsreport:2.5.0
```

**Comment by Amjadhpc** [comment] 2019-10-03 15:35
@sashayakovtseva  Yes   i  just tested it .  Just a question can we use os.Setenv() while creating the docker2singularity.sh?   .What would be the implications of such step ? obviously export will not work ?

**Comment by carterpeel** [comment] 2021-05-15 16:17
Hello,

This is a templated response that is being sent out to all open issues.  We are working hard on 'rebuilding' the Singularity community, and a major task on the agenda is finding out what issues are still outstanding.


**Please consider the following:**

1. Is this issue a duplicate, or has it been fixed/implemented since being added?
2. Is the issue still relevant to the current state of Singularity's functionality?
3. Would you like to continue discussing this issue or feature request?


Thanks,
Carter

**Comment by pedroalvesbatista** [comment] 2021-07-16 00:52
@benmishkanian Still getting this problem ? Have this been solved already ? If yes, what work around have you followed and applied ?

We're looking into the issue carefully, soon will bring to community and discuss ways to better solve as well address this. Thankyou for keeping the interest in the subject.

**Comment by benmishkanian** [comment] 2021-07-16 07:20
I don't know. I stopped using Singularity a long time ago and no longer have access to an HPC cluster.

**Comment by kmuriki** [comment] 2022-10-17 03:54
Singularity repo is now retired as the code base is now moved to Apptainer. We are closing all the old issues under the old Singularity repo. For further assistance please open a new issue under the new Apptainer repo. Thanks for your support.

**Closed as completed by kmuriki** 2022-10-17 03:54 UTC
Labels: Bug, ImageBuilding
