### ISSUE TITLE
Making man pages seems to be broken

### ISSUE THREAD

**Issue by GodloveD** [apptainer/singularity#2335] opened 2018-11-01 16:14 UTC
## Version of Singularity:

3.0.1 

### Expected behavior

`make man` creates man pages that can be installed 

### Actual behavior

```
root@ubuntu-bionic:~/go/src/github.com/sylabs/singularity/builddir# make man
FATAL   [U=0,P=2372]       main()                        Given directory does not exist or is not writable by calling user.
exit status 255
Makefile:390: recipe for target 'man' failed
make: *** [man] Error 1
```

There needs to be a test in place to make sure this regression doesn't happen again.

**Comment by jscook2345** [comment] 2018-11-04 03:15
I could reproduce that, but only if I tried to do it as a non-root user, which should not work.

Which directories do not exist? This error should probably be improved so we know which directories don't exist.

I added the statement `sylog.Infof("dir = %s", dir)` to `src/docs/makeDocs/makeDocs.go` right before the unix file check for debugging.

<pre>
[vagrant@localhost builddir]$ sudo env GOPATH=/home/vagrant/go make man
INFO    [U=0,P=6259]       main()                        dir = /usr/local/share/man/man1
INFO    [U=0,P=6259]       main()                        Creating Singularity man pages at /usr/local/share/man/man1
</pre>

**Comment by bauerm97** [comment] 2018-11-27 19:13
Closing because this seems to be resolved

**Closed as completed by bauerm97** 2018-11-27 19:13 UTC
Labels: Bug, Testing
