### ISSUE TITLE
[CLI] Missing cmd apps 

### ISSUE THREAD

**Issue by ArangoGutierrez** [apptainer/singularity#2115] opened 2018-09-27 19:41 UTC
## Version of Singularity:

`v3.0.0-beta.1-34-g87afec7a`

### Expected behavior

```shell
singularity apps image_with_apps.sif

bar

foo
```

### Actual behavior

```shell
[eduardo@rhel7 singularity]$ singularity apps image_with_apps.sif

Linux container platform optimized for High Performance Computing (HPC) and
Enterprise Performance Computing (EPC)

Usage:
  singularity [global options...]

Description:
  Singularity containers provide an application virtualization layer enabling
  mobility of compute via both application and environment portability. With
  Singularity one is capable of building a root file system and running that
  root file system on any other Linux system where Singularity is installed.

Options:
  -d, --debug              Print debugging information
  -h, --help               help for singularity
  -q, --quiet              Suppress all normal output
  -s, --silent             Only print errors
      --tokenfile string   path to the file holding your sylabs
                           authentication token (default
                           "/root/.singularity/sylabs-token")
  -v, --verbose            Increase verbosity +1
      --version            version for singularity

Available Commands:
  build       Build a new Singularity container
  capability  Manage Linux capabilities on containers
  exec        Execute a command within container
  help        Help about any command
  inspect     Display metadata for container if available
  instance    Manage containers running in the background
  keys        Manage OpenPGP key stores
  pull        Pull a container from a URI
  push        Push a container to a Library URI
  run         Launch a runscript within container
  run-help    Display help for container if available
  search      Search the library
  shell       Run a Bourne shell within container
  sign        Attach cryptographic signatures to container
  test        Run defined tests for this particular container
  verify      Verify cryptographic signatures on container
  version     Show application version

Examples:
  $ singularity help <command>
      Additional help for any Singularity subcommand can be seen by appending
      the subcommand name to the above command.


For additional help or support, please visit https://www.sylabs.io/docs/
```

### Steps to reproduce behavior

Build a container with apps on the definition file and run
```shell
singularity apps image_with_apps.sif
```

**Comment by WestleyK** [comment] 2019-08-06 01:06
Closing. Looks like this was fixed long ago by: https://github.com/sylabs/singularity/pull/2623 :smile:

**Closed as completed by WestleyK** 2019-08-06 01:06 UTC
Labels: Bug

**Comment by alexiswl** [comment] 2019-12-15 06:46
This is an ongoing issue, I can reproduce this behaviour in singularity versions 3.4.1, 3.4.2, and 3.5.1

```
$ singularity version
3.4.1-1

$ singularity apps
Usage:
  singularity [global options...] <command>

Available Commands:
  build       Build a Singularity image
  cache       Manage the local cache
  capability  Manage Linux capabilities for users and groups
  exec        Run a command within a container
  inspect     Show metadata for an image
  instance    Manage containers running as services
  key         Manage OpenPGP keys
  oci         Manage OCI containers
  plugin      Manage singularity plugins
  pull        Pull an image from a URI
  push        Upload image to the provided URI
  remote      Manage singularity remote endpoints
  run         Run the user-defined default command within a container
  run-help    Show the user-defined help for an image
  search      Search a Container Library for images
  shell       Run a shell within a container
  sif         siftool is a program for Singularity Image Format (SIF) file manipulation
  sign        Attach a cryptographic signature to an image
  test        Run the user-defined tests within a container
  verify      Verify cryptographic signatures attached to an image
  version     Show the version for Singularity

```

Please reopen this ticket.

Alexis.

**Comment by jmstover** [comment] 2019-12-15 14:36
@alexiswl

It looks like https://github.com/sylabs/singularity/pull/3390 merged the `apps` command with `inspect`.

So you should be able to get the apps by using `singularity inspect --list-apps` now.

-J

**Comment by alexiswl** [comment] 2019-12-16 05:54
Thank you @jmstover. I'd been using `singularity exec ${IMAGE} ls /scif/apps` as a work-around in the interim.
