### ISSUE TITLE
Verified reader size mismatch during pull/build of Docker image

### ISSUE THREAD

**Issue by agoose77** [apptainer/singularity#5799] opened 2021-01-25 20:15 UTC
Somewhere between 3.5.3 and 3.6.4, I am unable to build a Singularity image from a Docker image hosted on a private repo. I am not able to share the image itself unfortunately.

### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
singularity version 3.7.1
```
Also reproduces on 3.6.4, but does not reproduce on 3.5.3

### Expected behavior
`texat-runtime.sif` is built from a (private) Docker repo

### Actual behavior
Image build fails:
```
FATAL:   While performing build: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: discard trailing archive bits: expected 31101 bytes (only 31100 bytes in stream): verified reader size mismatch
```

### Steps to reproduce this behavior
```
singularity build -d texat-runtime.sif docker://docker.pkg.github.com/agoose77/texat/texat-runtime:latest         
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Singularity
Source

**Comment by dtrudg** [comment] 2021-01-25 21:27
Please post an affected container that exhibits the same issue at a public registry location that does not require login - the issue cannot otherwise be replicated. We can place it into a private registry - but we have no know issues with generically pulling containers from private registries.

Also, please verify that `singularity cache clean` and retrying does not correct this issue. Full debug output would be useful.

**Comment by dtrudg** [comment] 2021-01-25 21:30
Sorry - updated comment above due to missing that the image cannot be posted.

**Comment by agoose77** [comment] 2021-01-25 21:46
@dtrudg no problem - I edited the original comment, likely after you started reading :)

I tried clearing the cshce and it didn't change the issue. I'll re run tomorrow (I'm GMT) to obtain full debug output (apologies, I ought to have thought about that myself!)

**Comment by agoose77** [comment] 2021-01-26 10:27
@dtrudg here's the debug log file (gzip-ped txt file):
[log.txt.gz](https://github.com/hpcng/singularity/files/5872763/log.txt.gz)

**Comment by agoose77** [comment] 2021-02-05 10:13
@dtrudg is there anything more I can do here? :)

**Comment by dtrudg** [comment] 2021-02-05 15:03
> @dtrudg is there anything more I can do here? :)

@agoose77 not really without the image being possible to share. 

I did take a look at the log, and it locates the error, but doesn't really help find the underlying cause for this image. This error is coming out of the package we use to extract docker containers (https://github.com/opencontainers/umoci), rather than Singularity code:

https://github.com/opencontainers/umoci/blob/05c30365a67487176d42b4bf0fb5db9459dd54ec/oci/layer/unpack.go#L277

I haven't been able to replicate, and we need an image that causes it to be able to dig in. It's not really something we can ask about upstream to umoci without an example that causes it.

The reason it does not reproduce in older versions of Singularity is that we used a different library for unpacking images then. We switched to umoci, though, as it handles various other needs better that were often a problem with the previous solution.

**Comment by dtrudg** [comment] 2021-02-08 14:57
@agoose77 - I asked upstream and the maintainer of umoci has not seen this before.

How was the docker image created? What software was used to build it, e.g. docker / buildah / something else?

Can you do a `singularity cache clean` and then pull it, and check the sha sums in the `~/.singularity/cache/blob/blobs/sha256` directory as described in the link above? I.e. 

```
08:55 AM $ find ~/.singularity/cache/blob/blobs/sha256 -type f -print0 | xargs -0 sha256sum
4c0d98bf9879488e0407f897d9dd4bf758555a78e39675e72b5124ccf12c2580  /home/dave/.singularity/cache/blob/blobs/sha256/4c0d98bf9879488e0407f897d9dd4bf758555a78e39675e72b5124ccf12c2580
5cd2cdbe75bff5e661a3ac8e3174403996ab571e6420b523cb3ac66e0fcf0472  /home/dave/.singularity/cache/blob/blobs/sha256/5cd2cdbe75bff5e661a3ac8e3174403996ab571e6420b523cb3ac66e0fcf0472
e2a8572846157b37916ac1c9141b618998dc08b1808c2af4a4931adc479d5922  /home/dave/.singularity/cache/blob/blobs/sha256/e2a8572846157b37916ac1c9141b618998dc08b1808c2af4a4931adc479d5922
```

The filename sha (on the right) should match the computed sha (on the left).

**Comment by dtrudg** [comment] 2021-04-05 15:09
@agoose77 - please could you test with the code that's at https://github.com/hpcng/singularity/pull/5904 ?

The umoci maintainer @cyphar has kindly merged what is hopefully a fix to their master branch and is asking if it could be checked. They are planning to do a release tomorrow.

**Comment by dtrudg** [comment] 2021-04-14 14:42
This is expected to be fixed in Singularity 3.7.3 as it uses the new version of umoci to extract images. Please reopen if you continue to have issues on 3.7.3.

**Closed as completed by dtrudg** 2021-04-14 14:42 UTC
Labels: NeedsMoreInfo

**Comment by nickp60** [comment] 2023-11-29 21:50
Hello, hope its ok to comment here.  I am running into the same issue, also with a private repo, which makes reproducing difficult. I am running Singularity 3.8.7-1.el7 and still encountering this issue.  How can I determine which version of umoci is being called?  I don't know Go but looking at oci_unpack.go it doesn't look like it is pinned to a specific version or something.  What could I provide to help diagnose this issue?


```
/opt/local/singularity/3.8.7/bin/singularity  run [private image on enterprise github]
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob 578acb154839 skipped: already exists
Copying blob ac65017cfc56 skipped: already exists
Copying blob 146269b80f9c skipped: already exists
Copying blob b51bc62cc3ca skipped: already exists
Copying blob 4ba34dd48a55 skipped: already exists
Copying blob c5d6922dceee skipped: already exists
Copying blob 4300e3de5e54 skipped: already exists
Copying blob 4f4fb700ef54 skipped: already exists
Copying blob 1837e6bbb3c1 skipped: already exists
Copying blob cc25c0bc0da7 skipped: already exists
Copying config 9707921c7e done
Writing manifest to image destination
Storing signatures
2023/11/29 16:49:36  info unpack layer: sha256:578acb154839e9d0034432e8f53756d6f53ba62cf8c7ea5218a2476bf5b58fc9
2023/11/29 16:49:38  info unpack layer: sha256:ac65017cfc5699a3ab0e5ed6e11c321fc0c664fd6b4c8744cda7914e74897c47
2023/11/29 16:49:38  info unpack layer: sha256:146269b80f9cf49d0a8468344c664ea4368c54f4a53f9aa61ebf626adf0d2836
FATAL:   Unable to handle docker://github.mskcc.org/microbiome/isabl_io/dbutils:0.0.4h uri: while building SIF from layers: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: discard trailing archive bits: expected 12379703 bytes (only 12379702 bytes in stream): verified reader size mismatch


find ~/.singularity/cache/blob/blobs/sha256 -type f -print0 | xargs -0 sha256sum
1837e6bbb3c1018ea3e9b901cfb4ceb4e5a0589fccf03667fa24a2de5d64a402  /home/watersn/.singularity/cache/blob/blobs/sha256/1837e6bbb3c1018ea3e9b901cfb4ceb4e5a0589fccf03667fa24a2de5d64a402
578acb154839e9d0034432e8f53756d6f53ba62cf8c7ea5218a2476bf5b58fc9  /home/watersn/.singularity/cache/blob/blobs/sha256/578acb154839e9d0034432e8f53756d6f53ba62cf8c7ea5218a2476bf5b58fc9
b51bc62cc3ca2211d3e3882aba56cf7054c9773c535f198676c0ce429d29ef78  /home/watersn/.singularity/cache/blob/blobs/sha256/b51bc62cc3ca2211d3e3882aba56cf7054c9773c535f198676c0ce429d29ef78
4ba34dd48a55b7d0c548e1c74b1d1e4b2145c50f4ae760378734c13ae4529c50  /home/watersn/.singularity/cache/blob/blobs/sha256/4ba34dd48a55b7d0c548e1c74b1d1e4b2145c50f4ae760378734c13ae4529c50
c5d6922dceee0e12c432030f0f9c504dad7cd67f55db79092e5cbd5f9daf3a9f  /home/watersn/.singularity/cache/blob/blobs/sha256/c5d6922dceee0e12c432030f0f9c504dad7cd67f55db79092e5cbd5f9daf3a9f
9707921c7e625809abed7e4e9eb1452ab42a7f95c0a0200e9eeb097d5dd2be50  /home/watersn/.singularity/cache/blob/blobs/sha256/9707921c7e625809abed7e4e9eb1452ab42a7f95c0a0200e9eeb097d5dd2be50
ac65017cfc5699a3ab0e5ed6e11c321fc0c664fd6b4c8744cda7914e74897c47  /home/watersn/.singularity/cache/blob/blobs/sha256/ac65017cfc5699a3ab0e5ed6e11c321fc0c664fd6b4c8744cda7914e74897c47
4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1  /home/watersn/.singularity/cache/blob/blobs/sha256/4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
4300e3de5e54810d16453b9bd6413b3d5af6d286a3550cf3517679b7ab291dfd  /home/watersn/.singularity/cache/blob/blobs/sha256/4300e3de5e54810d16453b9bd6413b3d5af6d286a3550cf3517679b7ab291dfd
146269b80f9cf49d0a8468344c664ea4368c54f4a53f9aa61ebf626adf0d2836  /home/watersn/.singularity/cache/blob/blobs/sha256/146269b80f9cf49d0a8468344c664ea4368c54f4a53f9aa61ebf626adf0d2836
b110c35839f1ad0a27542fbdaa0c3f3fdb54c9509bdebf5906353811d1236c2a  /home/watersn/.singularity/cache/blob/blobs/sha256/b110c35839f1ad0a27542fbdaa0c3f3fdb54c9509bdebf5906353811d1236c2a
cc25c0bc0da7f47b40cdd9c3bacae8e62d24da8b32bd1c3805b54c3b1b725a5a  /home/watersn/.singularity/cache/blob/blobs/sha256/cc25c0bc0da7f47b40cdd9c3bacae8e62d24da8b32bd1c3805b54c3b1b725a5a

```

**Comment by DrDaveD** [comment] 2023-12-04 16:25
The versions of dependent modules in go programs are specified in go.mod.

In any case, I strongly encourage you to upgrade to a newer version of Apptainer (or SingularityCE) for security reasons.  This repository is closed, so if you have any more problems please follow up with a new issue under https://github.com/apptainer/apptainer, even if it relates to singularity 3.8.7 (or older).
