### ISSUE TITLE
Problem during installation.

### ISSUE THREAD

**Issue by NikosDelijohn** [apptainer/singularity#5001] opened 2020-01-31 11:26 UTC
I am trying to install the latest version of singularity on Ubuntu 18.04.3 LTS by following the user guide ( https://sylabs.io/guides/3.5/user-guide.pdf  ). After installing Golang and setting up everything , I try to install singularity but I get the error found in the attached image. 

I am using this command to install
```
 ./mconfig && \
make -C builddir && \
sudo make -C builddir install

```

![installation_error](https://user-images.githubusercontent.com/17165298/73535647-5c85b780-4424-11ea-85ae-92d4a3cb9f16.png)

**Comment by cclerget** [comment] 2020-01-31 15:43
Hi @NikosDelijohn , how did you install source ?

**Comment by NikosDelijohn** [comment] 2020-02-01 02:28
> Hi @NikosDelijohn , how did you install source ?

Hello @cclerget !! I made a script with the commands written in the documentation of Singularity. 

```
export VERSION=3.5.2 && 
wget https://github.com/sylabs/singularity/releases/download/v${VERSION}/singularity-${VERSION}.tar.gz &&
tar -xzf singularity-${VERSION}.tar.gz &&
# then follows the compilation code of the release.

```
But by source? What do you mean?

**Comment by jmstover** [comment] 2020-02-01 14:50
@NikosDelijohn 
`cmd/internal/cli/plugin_create_linux.go`? I don't have that file in the 3.5.2 tree ... 

```
cd /tmp
wget https://github.com/sylabs/singularity/releases/download/v3.5.2/singularity-3.5.2.tar.gz
tar xvf singularity-3.5.2.tar.gz
cd singularity
find . -name "plugin_create_linux.go"
```

I do find that file in the git master branch though. It looks like you may have a mix of files from different revisions laying around.

**Comment by cclerget** [comment] 2020-02-03 22:10
Like @jmstover said, you are extracting on top of existing singularity directory where master was cloned, reproducible with :

```
cd /tmp
git clone https://github.com/sylabs/singularity
wget https://github.com/sylabs/singularity/releases/download/v3.5.2/singularity-3.5.2.tar.gz
tar xvf singularity-3.5.2.tar.gz
./mconfig && make -C builddir
```

Just removing the existing singularity directory fix the issue. I'm closing the issue as resolved.

**Closed as completed by cclerget** 2020-02-03 22:10 UTC
